### ISSUE TITLE
CustomRenderer sample doesn't compile

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/xamarin-forms-samples#100]
I am testing the Custom Renderer sample in WinPhone8.1 and get the following two errors:
1) CameraPageRenderer.OnElementChanged (VisualElementChangedEventArgs): no suitable method found to override 
2) Argument 1: cannot convert from 'Xamarin.Forms.Platform.WinRT.VisualElementChangedEventArgs' to 'Xamarin.Forms.Platform.WinRT.ElementChangedEventArgs<Xamarin.Forms.Page>'	CustomRenderer.WinPhone81

Changing the method signature to match the method in Xamarin.Forms.Platform.WinRT.PageRenderer which is 
"OnElementChanged (ElementChangedEventArgs<Page> e)" doesn't help either.

This is a general issue I am experiencing with custom renderers not just this sample. I am using Xamarin.Forms v2.2.0.31 which is the version used in the sample as well :( I have tried the latest pre-release too, no difference

**Comment by Rajneesh360Logica** [comment]
Hi @HelenMamalaki 
Thanks for reporting this issue. This issue was perviously filed, and now it is fixed too. You can track this issue on Bugzilla.
https://bugzilla.xamarin.com/show_bug.cgi?id=37027

So as of now I am closing this issue. Please let me know if I am missing something.

Thanks..!
