### ISSUE TITLE
Firebase use in Xamarin

### ISSUE THREAD

**Issue by mcmiguelac** [xamarin/xamarin-forms-samples#102]
Implement the use of Firebase, a widespread tool, in Xamarin form. [https://firebase.google.com](url)

**Comment by jemaineosia** [comment]
Yes, we need this.

**Comment by conceptdev** [comment]
This has been a big job - there are pre-release Nugets available at

https://www.nuget.org/packages/Xamarin.Firebase.Common/32.940.0-beta3
