### ISSUE TITLE
Images 404 in examples

### ISSUE THREAD

**Issue by zabullet** [xamarin/xamarin-forms-samples#104]
http://xamarin.com/images/index/ide-xamarin-studio.png has been moved and 404's 

e.g. ImageDemoPage.cs:22

Happy to do a PR if you can provide me with the new location of the image.

@charlespetzold Annotate's got your name on it :wink: 

zb.

**Comment by Rajneesh360Logica** [comment]
Hi @zabullet thanks for filing the issue. I have checked and observed that same behavior, so I have filed the following issue in bugzilla.
https://bugzilla.xamarin.com/show_bug.cgi?id=42201

thanks..!

**Comment by olegoid** [comment]
Let's continue discussion of this bug in bugzilla
