### ISSUE TITLE
WorkingWithBehaviors UWP App does not change TextColor

### ISSUE THREAD

**Issue by apacha** [xamarin/xamarin-forms-samples#105]
The UWP-App in the WorkingWithBehaviors does not change the color (visually) when entering invalid data, although the code runs fine and sets the color in the behavior.

Not even setting the TextColor property in the xaml changes the color. Maybe something is wrong with the Entry control on UWP-platform?

![capture](https://cloud.githubusercontent.com/assets/594497/15619122/744b73a0-2452-11e6-8a76-518fa8572e53.PNG)

**Comment by apacha** [comment]
Seems that no one really cares about UWP ;-). The bug still persists.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that in the latest stable release of Xamarin.Forms, this sample sets the TextColor to red on UWP as expected.
