### ISSUE TITLE
Metadata.xml: Is it Beginner or Beginning?

### ISSUE THREAD

**Issue by spankr** [xamarin/xamarin-forms-samples#106]
I've been going through the sample projects and I am seeing multiple values for the same Level of  Beginning. Most say _"Beginner"_ but the README.md states _"Beginning"_.

> **Level** - Beginning, Intermediate, or Advanced: this is the intended audience level for the sample. only the getting started samples are Beginning, as they are intended for people who are just starting with the platform. most samples are Intermediate, and a few, that dive deep into difficult APIs, should be Advanced.

Should these values be consistent across the beginning projects?

* [beginning-projects.txt](https://github.com/xamarin/xamarin-forms-samples/files/292759/beginning-projects.txt)

Sorry if I seem a little OCD. It's just that I wrote a small traversal app so I can go through the samples in difficulty order and I noticed the discrepancy.

**Comment by olegoid** [comment]
This is a good catch @spankr. I'll change all the tags to match the description given in README.

**Comment by leouslion** [comment]
#106
