### ISSUE TITLE
i was problem in nested listview with horizontal scroll is working but vertical scroll is also working, i dont want vertical scroll

### ISSUE THREAD

**Issue by BasuHuddar** [xamarin/xamarin-forms-samples#108]
[Nested.txt](https://github.com/xamarin/xamarin-forms-samples/files/315916/Nested.txt)
<ListView x:Name="listview" HorizontalOptions="Center" HasUnevenRows="False"  RowHeight="150" ItemsSource="{Binding Products.products}">
      <ListView.ItemTemplate >
        <DataTemplate>
          <ViewCell>
            <ViewCell.View>
              
                           
                <StackLayout Orientation="Vertical">
                  <StackLayout  BackgroundColor="White" >
                  <Label Text="{Binding title}" HorizontalOptions="Center" TextColor="Black" FontSize="Large" FontAttributes="Bold" BackgroundColor="White" ></Label>
                  
                    </StackLayout>
                   <ScrollView Orientation="Vertical">
                     <ListView ItemsSource="{Binding products}"  Rotation="90" HorizontalOptions="Center" HasUnevenRows="True" RowHeight="150"   >
                      <ListView.ItemTemplate>
                        <DataTemplate>
                          <ViewCell>
                            <ViewCell.View>
                              <ScrollView Orientation="Horizontal">
                               <Grid Rotation="-90" HorizontalOptions="Start">
                                <Grid.RowDefinitions > 
                                  <RowDefinition Height="Auto" ></RowDefinition>
                                </Grid.RowDefinitions>
                                <Grid.ColumnDefinitions>
                                  <ColumnDefinition Width="*"></ColumnDefinition>
                                </Grid.ColumnDefinitions>
                                 
                                 <Image Source="{Binding imageSource}"  Aspect="AspectFit"  HeightRequest="100" WidthRequest="100" >
								                  <Image.GestureRecognizers>
                                   <TapGestureRecognizer
                                       NumberOfTapsRequired="1" Tapped="OnProductTapped"/>
                                  </Image.GestureRecognizers>
                                 </Image>
                                
                               </Grid>
                             </ScrollView>
                            </ViewCell.View>
                          </ViewCell>
                        </DataTemplate>
                      </ListView.ItemTemplate>
                    </ListView>
                  </ScrollView>
                </StackLayout>
                    
                
               
            </ViewCell.View>
          </ViewCell>
        </DataTemplate>
      </ListView.ItemTemplate>
    </ListView>
  </StackLayout>

**Comment by olegoid** [comment]
Hello @BasuHuddar, I have to close this "issue" since it's not a sample bug or a bug in Xamarin.Forms SDK. If you still have this problem please start discussion on Xamarin Forums: https://forums.xamarin.com/categories/xamarin-forms
