### ISSUE TITLE
cannot build. Cannot find annotation method 'anyOf()' in type 'RequiresPermission'

### ISSUE THREAD

**Issue by Mete0** [xamarin/xamarin-forms-samples#111]
Im getting the following error when trying to build the app. How do I fix this?

Severity	Code	Description	Project	File	Line	Suppression State
Error		A fatal exception has occurred. Program will exit.	WorkingWithMaps.Android			
Error		Could not create the Java Virtual Machine.	WorkingWithMaps.Android		
Warning		Cannot find annotation method 'anyOf()' in type 'RequiresPermission': class file for android.support.annotation.RequiresPermission not found	WorkingWithMaps.Android	C:\Users\username\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Maps\8.4.0\embedded\classes.jar(com/google/android/gms/maps/GoogleMap.class)

**Comment by Parmendrak** [comment]
Thanks for filled the issue, This issue working fine when changing its Heap size.
Please goto Advanced Android Build Setting  (Right chick Android project->Property->Android Options->Advanced) and set 'Java Max Heap Size' to 1G.
