### ISSUE TITLE
Wrong preprocessor directive

### ISSUE THREAD

**Issue by luccasclezar** [xamarin/xamarin-forms-samples#121]
I think the directive WINDOWS_PHONE is wrong in this file: https://github.com/xamarin/xamarin-forms-samples/blob/master/XamFormsImageResize/XamFormsImageResize/ImageResizer.cs

As the default directive for Windows 8.1 is WINDOWS_APP and for Windows Phone is WINDOWS_PHONE_APP, I think there's an error in the lines that correspond to each platform. 

I'm beginner in Xamarin.Forms and C#, so I didn't want to make a PR right away. Is this an error or its supposed to be this way?

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

The WINDOWS_PHONE directive was for Windows Phone 7, which the sample was originally written for. The sample has since been updated to include compiler directives for later Windows platforms.
