### ISSUE TITLE
Todo (PCL)

### ISSUE THREAD

**Issue by Steviey** [xamarin/xamarin-forms-samples#123]
Single Builds:

Todo.Android (Warnings):-------------------------------------

Severity    Code    Description Project File    Line    Suppression State
Warning CS0618  'TextToSpeech.Speak(string, QueueMode, IDictionary<string, string>)' is obsolete: 'deprecated'  Todo.Android    C:\a\Todo\PCL\Todo.Android\TextToSpeech_Android.cs  28  Active
Warning     The referenced component 'Todo' could not be found. Todo.Android  
Warning     Failed to resolve all project references for 'Todo'. The package restore result for 'C:\a\Todo\PCL\Todo.UWP\Todo.UWP.csproj' may be incomplete.         0   

Todo.UWP  (Warnings):-------------------

Severity    Code    Description Project File    Line    Suppression State
Warning     Certificate file 'Todo.UWP_TemporaryKey.pfx' not found. Todo.UWP  
Warning     The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.   Todo.UWP  
Warning     The referenced component 'Todo' could not be found. Todo.UWP  
Warning     Failed to resolve all project references for 'Todo.UWP'. The package restore result for 'C:\a\Todo\PCL\Todo.UWP\Todo.UWP.csproj' may be incomplete.         0   

Todo.WindowsPhone (Error):-------------------------

System.Exception was unhandled by user code
  HResult=-2146233088
  Message=Something went wrong in the build configuration.  This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.  Reference the appropriate platform assembly instead.
  Source=SQLitePCL.raw
  StackTrace:
       at SQLitePCL.SQLite3Provider_bait.SQLitePCL.ISQLite3Provider.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String vfs)
       at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
       at SQLite.SQLiteConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks)
       at Todo.WinPhone.SQLite_WinPhone.GetConnection()
       at Todo.TodoItemDatabase..ctor()
       at Todo.App.get_Database()
       at Todo.TodoItemListX.OnAppearing()
       at Xamarin.Forms.Page.Xamarin.Forms.IPageController.SendAppearing()
       at Xamarin.Forms.Platform.WinPhone.PageRenderer.<OnElementChanged>b__0_0(Object sender, RoutedEventArgs args)
       at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
       at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)
  InnerException: 

Comment: pointed to:

var sqliteFilename = "TodoSQLite.db3";
string path = Path.Combine(ApplicationData.Current.LocalFolder.Path, sqliteFilename);
var conn = new SQLite.SQLiteConnection(path);<---path not found???

from debug:

path    "C:\Data\Users\DefApps\AppData\{5D1404EC-45B7-4BFB-94B0-D2F09B4DBC0C}\local\TodoSQLite.db3"  string

After updating several recommended SQlite-Packages....

Severity    Code    Description Project File    Line    Suppression State
Error       Could not copy the file "C:\a\Todo\PCL\packages\SQLitePCL.cppinterop.0.9.2\build\native\sqlite3\v110_wp80\x86\sqlite3.dll" because it was not found.    Todo.WinPhone

**Comment by Steviey** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\a\PSL-TEMP\Todo\PCL\Todo\bin\Debug\QuickTodo.dll' could not be found	Todo.WinPhone	C:\a\PSL-TEMP\Todo\PCL\Todo.WinPhone\CSC	1	Active
Warning		The referenced component 'Todo' could not be found.	Todo.WinPhone			
Warning		No way to resolve conflict between "SQLitePCL.raw, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null" and "SQLitePCL.raw, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null". Choosing "SQLitePCL.raw, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily.	Todo.WinPhone

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

This sample was recently updated and I can confirm that it now works as expected.
