### ISSUE TITLE
Warning IDE0006 Error encountered while loading the project.

### ISSUE THREAD

**Issue by JLugarEE** [xamarin/xamarin-forms-samples#124]
Saw similar error from other beginner recently. I had initial install on 8/5 working, then on about 8/11 it died with an update of Xamarin.Forms.2.3.1.114. I had uninstalled manually a lot and ripped out perhaps too much. Originally had about 6 IDE0006 errors as follows:

Warning IDE0006 Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled. Todo.WinPhone 1 Active
 Warning This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Xamarin.Forms.2.3.1.114\build\portable-....
# 

After reinstall of VS Community 2015 Version 14.0.25425.01 update 3 then Xamarin 4.1.2.18 it seems a little better but I get no compiles YET!

For "FormsGallery" (Portable) Output I get:
1>------ Build started: Project: FormsGallery, Configuration: Debug Any CPU ------
1>  FormsGallery -> C:\Users\John\Documents\MobilAppDev\XAML\FormsGallery\FormsGallery\FormsGallery\bin\Debug\FormsGallery.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
For "FormsGallery" (Portable) "error list" I get:
Severity    Code    Description Project File    Line    Source  Suppression State
a) Warning      @(Content) build action is not supported    FormsGallery.Android    C:\Users\John\Documents\MobilAppDev\XAML\FormsGallery\FormsGallery\FormsGallery.Android\Properties\AndroidManifest.xml      Build  
b) Severity Code    Description Project File    Line    Source  Suppression State
Warning     Cannot find annotation method 'anyOf()' in type 'RequiresPermission': class file for android.support.annotation.RequiresPermission not found    FormsGallery.Android    C:\Users\John\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Maps\8.4.0\embedded\classes.jar(com/google/android/gms/maps/GoogleMap.class)     Build  
c) Severity Code    Description Project File    Line    Source  Suppression State
Warning     iCCP: Not recognizing known sRGB profile that has been edited   FormsGallery.Android    C:\Users\John\Documents\MobilAppDev\XAML\FormsGallery\FormsGallery\FormsGallery.Android\obj\Debug\res\drawable-hdpi\icon.png        Build  
... (9 nearly identical lines)
m) Severity Code    Description Project File    Line    Source  Suppression State
Warning     iCCP: Not recognizing known sRGB profile that has been edited   FormsGallery.Android    C:\Users\John\Documents\MobilAppDev\XAML\FormsGallery\FormsGallery\FormsGallery.Android\obj\Debug\res\drawable-xxhdpi\icon.png      Build

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

The FormsGallery sample has recently been updated and I can confirm that it works as expected.
