### ISSUE TITLE
Native2Forms

### ISSUE THREAD

**Issue by vamsi439** [xamarin/xamarin-forms-samples#125]
Every time getting object refernce not instance of an object while navigating native page to forms page.

it works on ios to forms

but it not works on 

forms to ios (working) then ios to forms is not working

**Comment by shah-smit** [comment]
@vamsi439 so does it work for you on Android as well (native2forms) ?

**Comment by vamsi439** [comment]
Yes Its working on Android.

**Comment by davidbritch** [comment]
Apologies for the delayed response. This sample has been completely re-written and now works fine on every platform.
