### ISSUE TITLE
CCGameView.ViewCreated Handler not being called

### ISSUE THREAD

**Issue by arienofx** [xamarin/xamarin-forms-samples#129]
Hello,

Im trying to follow the tutorial **https://developer.xamarin.com/guides/cross-platform/game_development/cocossharp/first_game/part1/**
but no matter I do, the event associated with handler is not being called.

Here's my code (following the code template create automatically):

```
protected override void OnCreate(Bundle bundle)
{
    base.OnCreate(bundle);

    // Set our view from the "main" layout resource
    SetContentView(Resource.Layout.Main);

    // Get our game view from the layout resource,
    // and attach the view created event to it
    CCGameView gameView = (CCGameView)FindViewById(Resource.Id.GameView);
    gameView.ViewCreated += LoadGame;
    //<-- the breakpoint reaches here
}

void LoadGame(object sender, EventArgs e)
{//<- I put a breakpoint here
    // but this code never reached
    ... rest of the code
}
```

Im missing something or it's a actual issue?

Here's my setup:
VS 2015 (x64)
CocosSharp 1.7.1 (last release)
JDK 1.8.0_101 (x64)
NDK r11c

My best reggards,
Arie

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

This issue, if it still exists, should be filed at https://github.com/xamarin/mobile-samples/ as that's where the sample lives.
