### ISSUE TITLE
UsingResxLocalization throws error : 

### ISSUE THREAD

**Issue by hkaraoglu** [xamarin/xamarin-forms-samples#132]
Hi , I made all and created all classes of UsingResxLocalization in my project. But Visual studio throws me an error like this : 
**System.TypeLoadException: Could not load type 'Xamarin.Forms.Xaml.XamlServiceProvider' from assembly 'Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.**

**Comment by lodestarfly** [comment]
Follow this URL       https://developer.xamarin.com/guides/android/getting_started/installation/windows/
maybe java, SDK, NDK have lost file or needed update.

**Comment by jamesmundy** [comment]
+ 1 @Revenge94 
I just posted on the Xamarin Forums: http://forums.xamarin.com/discussion/78120/missingmanifestresourceexception-in-windows-phone-8-1-app#latest

I get a similar error with a different project that uses the same code.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that with the latest stable release of Xamarin.Forms, this sample builds without errors.
