### ISSUE TITLE
Navigation:MasterDetailPage sample no longer shows hamburger icon

### ISSUE THREAD

**Issue by jamesmundy** [xamarin/xamarin-forms-samples#146]
https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/MasterDetailPage

In the latest stable build of Xamarin.Forms the hamburger menu icon does not work in iOS. The Navigation bar is completely blank.

**Comment by BenDevelopment** [comment]
The hamburger icon does not shows on UWP neither.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that the hamburger icon works on both iOS and UWP in the latest stable release of Xamarin.Forms.
