### ISSUE TITLE
How to Implement pagination using Option C of WorkingWithListviewNative

### ISSUE THREAD

**Issue by shuklajay** [xamarin/xamarin-forms-samples#147]
Hi, I am using C option of WorkingWithListviewNative and i want to try pagination in both ios and android  but unable to find way to implement it. Can you please share your thoughts

Thanks

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
