### ISSUE TITLE
How to implement user sessions?

### ISSUE THREAD

**Issue by hanu412** [xamarin/xamarin-forms-samples#149]
Hey There!

Is there a sample project in which user sessions have been implemented? 

If not, can I get a guideline on how I can do this? 

Thanks for the help!

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
