### ISSUE TITLE
system reflection targetinvocationexception

### ISSUE THREAD

**Issue by ibragh** [xamarin/xamarin-forms-samples#151]
in Theme project:
https://github.com/xamarin/xamarin-forms-samples/tree/master/Themes/ThemesDemo

the app cannot be run.. this is the issue
http://i.imgur.com/6AnkOgO.png

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that this sample runs correctly with the latest stable release of Xamarin.Forms.
