### ISSUE TITLE
Webservices/TodoAWSAuth not compatible with new oauth requirements`

### ISSUE THREAD

**Issue by dreamtheater39** [xamarin/xamarin-forms-samples#154]
Google no longer allows login flows to work out of webcontrols and needs to use the default browser. The current samples and internals do not follow this - and the sample needs to change

**Comment by bbougot** [comment]
+1

**Comment by mauricioross** [comment]
So, if I'm using page render, and I open browsers on ios or android to do oauth, will I have problems?

**Comment by davidbritch** [comment]
Thanks for opening the issue, and apologies for the delayed response to it.

Following an internal discussion, and now that Amazon has content on using the [AWS Mobile SDK for .NET and Xamarin](https://docs.aws.amazon.com/mobile/sdkforxamarin/developerguide/Welcome.html), we've decided to retire our AWS content. Therefore, I'm closing this issue.
