### ISSUE TITLE
OnElementChangedEventArgs issue : Convert View to Map

### ISSUE THREAD

**Issue by Umar3x** [xamarin/xamarin-forms-samples#158]
Hello, 

I used the code in this project to customize the map, but I encounter a probleme with the project given in this repository.

When I pass the argument View, gives the following error : 

impossible to convert 'Xamarin.Forms.Platform.Android.ElementChangedEventArgs<Xamarin.Forms.View>' to 'Xamarin.Forms.Platform.Android.ElementChangedEventArgs<Xamarin.Forms.Maps.Map>'	Project.Droid	D:\folder\folder\projects\ProjectXamarin\Project\Project.Droid\CustomMapRenderer\CustomMapRenderer.cs	

I tried to pass what it attempts, a map, but then my customPins are null, at this line

`protected override void OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs<Map> e)`

And I dont know how to fix that, any idea or ppl metting the same prob ?
 

Thanks

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
