### ISSUE TITLE
TodoAzure crashes on assignment of todoList.ItemsSource

### ISSUE THREAD

**Issue by justanotheranonymoususer** [xamarin/xamarin-forms-samples#159]
I have the following problem: [this assignment](https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoAzure/TodoAzure/TodoList.xaml.cs#L49) crashes sometimes, but not always, with the following error:

> An exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.ni.dll but was not handled in user code
> 
> Additional information: This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1).
> 
> If there is a handler for this exception, the program may be safely continued.

Is it a bug of the code? What can be done about it? I'm new to Xamarin and C#. Thanks.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that in the latest stable release of Xamarin.Forms that the assignment doesn't crash.
