### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by SleeplessByte** [xamarin/xamarin-forms-samples#16]
All the samples fail with the same migration error 

    The application which this project type is based on was not found. 
    Please try this link for further information: [non-resolving-link]

 [non-resolving-link](http://go.microsoft.com/fwlink/?prd=12395&pver=11&sbp=ProjectTypeDeprecated&plcid=0x409&clcid=0x409&ar=MSDN&sar=ProjectCompatibility&o1=EFBA0AD7-5A72-4C68-AF49-83D382785DCF)

So I just created a new Android project, and tried copying over the project type guid, but they already match. How to I get the samples working in Visual Studio 2013?

**Comment by conceptdev** [comment]
These types of questions are best posted to the forums

http://forums.xamarin.com/

either in the Xamarin.Forms and Android sections.
