### ISSUE TITLE
WebServices > TodoAzureAuthADB2CClientFlow : SignUp process leads to Bad Request

### ISSUE THREAD

**Issue by bcolas** [xamarin/xamarin-forms-samples#161]
After trying to replicate the mechanism to authenticate against Azure Directory B2C in my project without success, I downloaded the sample TodoAzureAuthADB2CClientFlow, put it in Visual Studio, built it and deploy it on Android Emulator
==> Got the same error after SignUp Process : Blank page with message Bad Request

In class Constants, I put 

    public static readonly string ApplicationURL = @"http://xxxxxxxxxxxxxxxxxxx.azurewebsites.net";
    
    public static readonly string ApplicationID = "9bc3f5a6-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
    public static readonly string[] Scopes = { ApplicationID };
    public static readonly string SignUpSignInPolicy = "B2C_1_SignUpSignIn";
    public static readonly string Authority = "https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxx.onmicrosoft.com/";

Do you have any idea how I can make it work ?
Thanks for help

![image](https://cloud.githubusercontent.com/assets/8590669/21388819/5c33e64c-c77e-11e6-9b1b-3e1d77e4ee8b.png)

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

This sample has been updated since you logged your issue, and is working without any problems.
