### ISSUE TITLE
WorkingWithImages embedded image does not work in release mode for UWP.

### ISSUE THREAD

**Issue by chadbryant** [xamarin/xamarin-forms-samples#166]
The embedded image does not show in release mode.  Debug mode works.

**Comment by davidbritch** [comment]
Apologies for the much delayed response, and thanks for pointing out the issue.

I've just fixed this via https://github.com/xamarin/xamarin-forms-samples/commit/54f3cf1098886a99a87b2a51922fee1051740e00

A doc update will be forthcoming.
