### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by idarous** [xamarin/xamarin-forms-samples#168]
Hello,

I use Linux mint and I develop with C#, Unity3D and Asp.net core on Linux. All my C# project works fine.

I searched on the web some instructions that explain how to use Xamarin.forms on Linux with Visual Studio Code, but I found nothing.
However on the Github repository of Xamarin.form when reading the Makefile I see some instructions about Linux, so I suppose this OS is supported.

Can someone give me the instructions to build and use Xamarin.form on Linux ?

**Comment by sander1095** [comment]
I googled it and I do not think it is possible:

https://forums.xamarin.com/discussion/59305/xamarin-forms-on-linux
https://forums.xamarin.com/discussion/1599/xamarin-studio-in-linux
https://www.google.com/search?q=xamarin+forms+linux+site:forums.xamarin.com

**Comment by nodoid** [comment]
Hi,

> I googled it and I do not think it is possible:

Given this is a community based project and forms is open sourced now,
it should *theoretically* be possible to bind Forms to one of the
various UI kits on Linux. Just takes someone with the time and
inclination to do it.

PFJ

-- 
Out now from Packt Publishing - "Xamarin Mobile Application Development
for iOS" and "Cross Platform UI Development with Xamarin.Forms" - Both
from Packt Publishing
http://www.packtpub.com/xamarin-mobile-application-development-for-ios/book
|
https://www.packtpub.com/application-development/cross-platform-ui-development-xamarinforms

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. A Linux backend has been added to Xamarin.Forms and is currently in preview. For more information, see https://github.com/jsuarezruiz/forms-gtk-progress
