### ISSUE TITLE
iOS deeplinking not working

### ISSUE THREAD

**Issue by imuller** [xamarin/xamarin-forms-samples#175]
Hello!

When I use the iOS deeplink example it isn't working. The "OnAppLinkRequestReceived" method inside the App class never gets called. The native method "OpenUrl" inside the AppDelegate.cs of iOS works fine..

**Comment by leouslion** [comment]
#175

**Comment by davidbritch** [comment]
Hi @imuller 

Apologies for the delay in dealing with this issue. I've just updated the sample and the issue should now be resolved.
