### ISSUE TITLE
Forms2Native : How to handle click event

### ISSUE THREAD

**Issue by KratiChauhan** [xamarin/xamarin-forms-samples#179]
Hello

I was trying to extend your Form2Native approach by adding a radiobutton group. However i am facing below issues

1. I am not able to add a radio group
2. How can we handle the click event in this approach. E.g. I want to handle the radiobutton click event. How can i do that ?

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
