### ISSUE TITLE
xamarin.social missing and cannot be installed

### ISSUE THREAD

**Issue by Scherady** [xamarin/xamarin-forms-samples#180]
I am trying to run EmployeeDirectory in xamarin studio on my Mac.
1. I did not find xamarin.social in the packages and I get the error:

> The type or namespace name 'Social' does not exist in the namespace 'Xamarin'. Are you missing an assembly reference? (CS0234) (EmployeeDirectory.iOS)

2. Trying to install xamarin.social I get the error:

> Could not install package 'Xamarin.Social 1.1.7'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

What to do?
Thank you

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

This sample was updated towards the end of last week, and I can confirm that it now runs on both iOS and Android from Visual Studio for Mac.
