### ISSUE TITLE
Todo Sample

### ISSUE THREAD

**Issue by StanleyBroo** [xamarin/xamarin-forms-samples#181]
#pragma warning disable CS0618 // Type or member is obsolete
                    speaker.Speak(toSpeak, QueueMode.Flush, p);

**Comment by Terni** [comment]
all sample dont working !!!!!

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

This sample has recently been updated and I can confirm that it runs on each platform, and that the deprecated `Speak` API has been removed.
