### ISSUE TITLE
This sample doesn't work 

### ISSUE THREAD

**Issue by mpbalshetwar** [xamarin/xamarin-forms-samples#187]
There interdependency of nugget packages and it can not be resolved. I took help from MS guy also and he suggested me to file an issue here.

Support Ticket # - 
[REG:117041815616264] Unable to resolve dependency

Please provide me with workable code.

**Comment by davidhedelin** [comment]
Try to get the 1.2.1 version of the package and then update "SQLitePCLRaw.bundle_green" by itself and it should work.

**Comment by davidbritch** [comment]
Apologies for the delayed response. Which sample doesn't work?

**Comment by davidbritch** [comment]
I've not heard back from you so I'm going to close this issue. Thanks for taking the time to raise an issue.
