### ISSUE TITLE
Map center don't jum to a point in Android (Map/Polyline sample)?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/xamarin-forms-samples#190]
in Android, this sample center of Map don't jum to a point. but it's working fine on UWP
`customMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(centerPoint.Latitude, centerPoint.Longtitude), Distance.FromKilometers(0.3)));`

**Comment by davidbritch** [comment]
Apologies for the delayed response to the issue. The Android map renderers have been updated several times in the past year, in response to changes in the underlying platform, and now function correctly on each platform.

Therefore I'm going to close this issue.
