### ISSUE TITLE
CustomRenderers/Map/Pin in Android does not add pin or MoveToRegion 

### ISSUE THREAD

**Issue by jesusgarza** [xamarin/xamarin-forms-samples#193]
This is recent, because it used to work on iOS and Android. I suppose it is related to #190
I am running the sample with Xamarin.Forms 2.3.4.231 on both Xamarin Studio and Visual Studio for Mac. I have tried the sample on Emulator and a Device and its the same result: I can see the map, but there is no pin added and it does not MoveToRegion.
I reissued the API Key, I cleaned the solution and Rebuild All, but I get the same result. In the Emulator I am using Android 4.1.1 and in the Device I have 5.1.
I tried the sample WorkingWithMaps and it does work on Android, both adding pins and recentering the map, so it could be something to do with the implementation of the Android Renderer.

Any ideas?
Thanks.

**Comment by ep2016** [comment]
I believe it is relative to the usage of bool isDrawn. I've built something similar based on this sample "Customizing a Map Pin" and used exactly the same strategy. A few months ago, this was working. Now, I face the behavior you described. Debugging the code, I realized that OnElementPropertyChanged method is NEVER triggered for e.PropertyName = "VisibleRegion" and therefore isDrawn never becomes true. As a consequence, no further code gets executed to display something on the map (the collection of custom pins in this sample). My guess is that the latest Xamarin.Forms build or Google itself has changed something relative to "VisibleRegion" Property. Have a look at:
https://forums.xamarin.com/discussion/92565/android-ionmapreadycallback-forms-2-3-4
and
https://forums.xamarin.com/discussion/95326/what-happened-with-google-maps-on-forms

**Comment by jesusgarza** [comment]
Hey, Thanks for the tip!! I used the code from the first link and now its working again.

**Comment by davidbritch** [comment]
Apologies for the delayed response to the issue. The Android map renderers have been updated several times in the past year, in response to changes in the underlying platform, and now function correctly on each platform.

Therefore I'm going to close this issue.

**Comment by ngalicoco** [comment]
I downloaded the latest Customizing Pin Sample from here https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin

It works great on iOS, but on android it just shows an empty map with Zoom controls that are not functional.

**Work Space Information:**

Microsoft Visual Studio Professional 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02556

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.


Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.752 (0faa808ee)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.8.1.28 (3979d08)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- I haven't updated any nuget packages for the solution.

- Does this application require any specific Android SDK tools that should be configured through Android SDK manager?
