### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by fh-thudson** [xamarin/xamarin-forms-samples#194]
Does this technique work with a website? (Like a live URL https)  As in, I have a website that my customer signs up on.  I would like the app to use what I have already created slash I would like to pre-populate some fields from the app's other views.  Is this even possible or should u just build the whole process in the app?

Regards,
Ty.

**Comment by davidbritch** [comment]
What sample do you have an issue with?

**Comment by davidbritch** [comment]
I've not heard back from you so I'm going to close this issue. Thanks for taking the time to raise an issue.
