### ISSUE TITLE
TouchTrackingEffectDemos.Droid won't start, iOS is OK

### ISSUE THREAD

**Issue by blmiles** [xamarin/xamarin-forms-samples#195]
Hello,

Just downloaded the latest as directed off Xamarin.
Running on a Mac Mini and using Xamarin Studio.

Droid sample builds, no errors, deploys, **won't run, no errors cited**.
iOS sample works without issue.

Any help would be great.

Further help on this would also be great!
_https://forums.xamarin.com/discussion/95175/using-skiasharp-in-a-xamarin-cross-platform-app-with-a-shared-project-not-in-pcl/p1?new=1_

Thanks

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I've just built and ran the latest version of this sample on Android, with no problems. Therefore I'm going to close this issue.
