### ISSUE TITLE
NativeToForms.iOS - Title does not appear in Navigation Bar

### ISSUE THREAD

**Issue by munkii** [xamarin/xamarin-forms-samples#197]
In the iOS NativeToForms sample the Title for the ContentPage does not appear in the Navigation Bar.

**Comment by cmatskas** [comment]
Hi @munkii, this is because some things have changed. I had to change the App.xaml.cs with the following code:
```
public App()
{
    InitializeComponent();
    MainPage = new NavigationPage(new HomePage());
}
```
That worked for me

**Comment by munkii** [comment]
Thanks

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

The NativeToForms sample has been complete re-written since your initial query, and includes code to set the Title of the page on the NavigationBar.
