### ISSUE TITLE
Map don't move to region on Android Project?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/xamarin-forms-samples#198]
`customMap.MoveToRegion (MapSpan.FromCenterAndRadius (new Position (xx.xxxxx, -xxx.xxxxx), Distance.FromMiles (1.0)));`
I have a Xamarin.Forms Project, I use this code to make Map move to my favorite position. But it's only work on UWP project, it's not working on Android Project?
Pleas help!

**Comment by AlexTeixeira** [comment]
Same here. It's work perfectly on IOS but not on Android...

**Comment by Emixam23** [comment]
Sameeeeeeee, what is happening?

    using Xamarin.Forms.Map;
    // using ...

    public class CustomMap : Map
    {
        // ....

        /// <summary>
        /// Update the camera focus based on the CameraFocus property.
        /// </summary>
        public async void UpdateCamera()
        {
            if (this.isMapLoaded)
            {
                switch (this.CameraFocusParameter)
                {
                    case CameraFocusReference.OnPolyline:
                        // ....
                        break;

                    case CameraFocusReference.OnPins:
                        // ....
                        break;

                    case CameraFocusReference.OnUser:
                        UserLocation = await CustomMap.GetPosition();
                        this.MoveToRegion(MapSpan.FromCenterAndRadius(UserLocation, Distance.FromKilometers(10)));
                        break;
                }
            }
        }

        // ...

        #region User Location

        /// <summary>
        /// The current location of the user.
        /// </summary>
        public static readonly BindableProperty UserLocationProperty =
            BindableProperty.Create(nameof(UserLocation), typeof(Position), typeof(CustomMap), new Position());

        /// <summary>
        /// Assessor for UserLocation property.
        /// </summary>
        public Position UserLocation
        {
            get { return (Position)GetValue(UserLocationProperty); }
            private set { SetValue(UserLocationProperty, value); }
        }

        /// <summary>
        /// Get the current position of the user.
        /// </summary>
        /// <returns>The current location of the user.</returns>
        public async static Task<Position> GetPosition()
        {
            Plugin.Geolocator.Abstractions.Position position;

            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;

                position = await locator.GetPositionAsync(TimeSpan.FromSeconds(3));
                if (position != null)
                    return new Position(position.Latitude, position.Longitude);
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Unable to get location, may need to increase timeout: " + ex);
            }

            position = await CrossGeolocator.Current.GetLastKnownLocationAsync();
            if (position == null)
                return new Position();
            
            return (new Position());
        }

        #endregion User Location
    }

**this.isMapLoaded**: This variable is set by the `public void OnMapReady(GoogleMap googleMap)` of the Android map renderer. It wors perfectly, i tested it multiple time and it works also for UWP. 

Before it was working perfectly for Pins, Polylines, User location, etc

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. 

This issue did exist due to changes that were introduced in Xamarin.Forms (in 2.4 if I remember correctly). However, since then the maps samples have been updated and I can confirm that they are working correctly.

**Comment by yusufmsalh** [comment]
not solved, .issue still exist in xf 4.6
