### ISSUE TITLE
Camera does not fit full screen on iOS iPhone 4s (Solution included)

### ISSUE THREAD

**Issue by daspuru** [xamarin/xamarin-forms-samples#200]
In the CameraPageRenderer, two white stripes appear at the sides of the liveCameraStream layer in iPhone 4s. This solution works in iPhone 4s, but is not tested in other iPhone models, and was found here: [this StackOverflow Answer](https://stackoverflow.com/a/19802099). 

Here is the fix, in CameraPateRenderer.cs, line 160, and looks great in 4s, I hope this helps:

`var videoPreviewLayer = new AVCaptureVideoPreviewLayer (captureSession) {
    Frame = liveCameraStream.Bounds,
    VideoGravity = AVLayerVideoGravity.ResizeAspectFill
};`

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. The sample was hard coded to use a screen width of 320 pixels, which was the cause of the problem. It's since been updated to correctly use the screen width of the particular phone.
