### ISSUE TITLE
UWP sample?

### ISSUE THREAD

**Issue by munkii** [xamarin/xamarin-forms-samples#202]
I am trying to put together a UWP sample that shows going from Native to XF in UWP. Do you have anything you can share?

I have hit an issue with AccessViolationException when trying to Navigate to the first XF with this code

`_rootFrame.Navigate(mainPage.GetType(), this._rootFrame);`

**Comment by davidbritch** [comment]
Apologies for the delayed response. The following sample should demo what you require:

https://github.com/xamarin/xamarin-forms-samples/tree/master/Native2Forms
