### ISSUE TITLE
SkiaSharpForms SKRect.Offset has no effect?

### ISSUE THREAD

**Issue by Yumeryu** [xamarin/xamarin-forms-samples#206]
When using SKPath, Offset(x, y) can offset Paths correctly. 
But when I have a SKRect object, Offset(x, y) doesn't have any effect. 

Is this a bug? or just not implemented yet?

Thanks.

**Comment by charlespetzold** [comment]
Sorry for the delay in addressing this issue. Using SkiaSharp 1.60.0, I tried the following:

```
SKRect rect = new SKRect(10, 20, 30, 40);
rect.Offset(5, 5);
System.Diagnostics.Debug.WriteLine(rect);
```

and got the following:

```
{Left=15,Top=25,Width=20,Height=20}
```

The `SKRect.Offset` method seems to be working.
