### ISSUE TITLE
Add issues menu to Xamarin-forms github page

### ISSUE THREAD

**Issue by idarous** [xamarin/xamarin-forms-samples#210]
Hello I don't understand why there are no issue pages for xamarin-forms, xamarin-android, xamarin-ios.

I've heard that Xamarin's team want more feedback and code contributors from the community but how do they want all of that if there are no issue pages (see the video bellow https://blog.xamarin.com/glimpse-future-xamarin-forms-3-0/).

Can someone explain me that ?

**Comment by davidbritch** [comment]
Apologies for the delayed response. There are now issues pages for Xamarin.Forms, Xamarin.Android, and Xamarin.iOS.
