### ISSUE TITLE
Support Webassembly to target web browser

### ISSUE THREAD

**Issue by idarous** [xamarin/xamarin-forms-samples#211]
Hello,

It would be great if we can use Xamarin.forms inside browser on supporting Webassembly.
Unity3d has already plan to support Webassembly (It supports already HTML5/JS with WebGL).

I've read that Xamarin.forms 3 will target MacOSX and GNU/Linux in addition to Android, MacOSX and Windows. If Xamarin can support Webassembly, we can use C#+.net standard everywhere on client with Xamarin and C#+.net standard everywhere on server with Asp.net core to create web api.

It will be very good for the C# community and developers in general because we will be able to have great open source and cross platform tools (Xamarin, Asp.net core, .net core, C#, Visual Studio Code) to build a large set of applications (mobile, web, desktop and server).

**Comment by weitzhandler** [comment]
While this suggestion sounds great, I'm not sure you posted this issue in the right place. You should have posted it in the [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms) repo.

Anyway, looks like this is something that's being worked on, check out the [WebSharp](https://github.com/xamarin/WebSharp) repo.

**Comment by davidbritch** [comment]
Closing this issue as the above response is correct.

**Comment by weitzhandler** [comment]
And BTW, [Blazor](https://github.com/aspnet/Blazor) is also definitely something you'd want to look at.
