### ISSUE TITLE
"Vizualization Error" - Xamarin.Forms.Themes example not building

### ISSUE THREAD

**Issue by BrutalCoding** [xamarin/xamarin-forms-samples#212]
I tried building this:
https://github.com/xamarin/xamarin-forms-samples/tree/master/Themes/ThemesDemo

But what I'm getting is this error: **MergedWith should inherit from ResourceDictionary (ArgumentException)**. 

I haven't changed a line from the example, thought it would work out of the box. I am currently running Xamarin.Forms 2.3.5.256-pre6 with Xamarin.Forms.Theme.Base (1.0.0.43-pre1) and the Dark & Light packages (same version numbers as Base). 

What am I doing wrong? Can't find related issues from others, I also can't get it to work by compiling without Xamarin Live, so I assume that Xamarin Live is not causing problems here.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that with the latest stable release of Xamarin.Forms, this sample builds correctly on both iOS and Android.

**Comment by BrutalCoding** [comment]
I'm a bit faster with replying as you can see :)! But nonetheless, thank you for confirming the status now.

**Comment by nildarar** [comment]
Hi @BrutalCoding 
Can you solve this problem?

**Comment by BrutalCoding** [comment]
Hi @nildarar,

Sorry I haven't tried it out yet. Have been playing with Flutter nowadays. But the issue should be fixed with the latest builds according to @davidbritch.
