### ISSUE TITLE
VS 2017 + Xamarin on windows 10 Surface Pro: Andriod emulator cannot use HAXM

### ISSUE THREAD

**Issue by guangw** [xamarin/xamarin-forms-samples#214]
emulator params with hard coded API 23 which seems do not support Intel HAXM any more. I was able to open emulator w/o hardware accelerator but it's so slow to continue any work. There is no hyper-v though it always suggest to turn it off(virtualization is enabled). Does it really mean the IDE is doomed for andriod app development?  Not sure if this is the case for VS for mac that I will give a try.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

It's common to use the official Google Emulators for Android development with the Xamarin platform. These emulators all require HAXM to be enabled, which in turn requires disabling Hyper-V.
