### ISSUE TITLE
SelectedIndex of Picker is not working when binding itemssource

### ISSUE THREAD

**Issue by venkatkonda** [xamarin/xamarin-forms-samples#216]
When we bind ItemsSource to Picker  Selectedindex is not working in Xaml.

**Comment by vhugogarcia** [comment]
I'm having the same issue. Is there a Workaround?

**Comment by LuAngel1990** [comment]
It won't work, since the InitializeComponent() of the XAML starts first then the ViewModel. So it wont have an index to show. The solution is to make bindeable the SelectedIndex.

**Comment by profexorgeek** [comment]
This appears to be answered so I'm closing the issue. Please open a new issue if you still have problems.
