### ISSUE TITLE
How to use exists database file in Xamarin.Forms

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/xamarin-forms-samples#217]
I have a database sqlite.db file. How to use this file in Xamarin.Forms (include UWP project).

**Comment by Micnick** [comment]
@nguyenthanhliemfc this article on Xamarin official web page is the best reference to him https://developer.xamarin.com/recipes/android/data/databases/sqlite/

**Comment by nguyenthanhliemfc** [comment]
Thank you Micnick
