### ISSUE TITLE
[MasterDetalPage] HumbergerMenu disappear after navigation in Windows 10 PC?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/xamarin-forms-samples#219]
[MasterDetalPage] HumbergerMenu disappear after navigation in Windows 10 PC?

**Comment by ElAngeluz** [comment]
i don't know why but if you run in the emulator the bug is resolved

**Comment by nguyenthanhliemfc** [comment]
Yeah It working fine on Lumia phone, how to fix on PC

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that in the latest stable release of Xamarin.Forms that the hamburger menu is behaving as expected in UWP on Windows 10 desktop.
