### ISSUE TITLE
Call JS from C# in HybridWebView

### ISSUE THREAD

**Issue by danilotecoliveira** [xamarin/xamarin-forms-samples#221]
Call C# from JS in HybridWebView works perfectly, but I have no idea how can I call JS function from C#.
Example, I call C# function, run my process and I need to send the result come back to HTML. 

Is it possible do this with HybridWebView?

**Comment by denisaguilar** [comment]
Hey, did you solve it ?

**Comment by danilotecoliveira** [comment]
No Unfortunately. 
But I solved it differently. It's in my git [WebViewCommunication](https://github.com/danilotecoliveira/WebViewCommunication)

**Comment by denisaguilar** [comment]
Thank u, 
are u sure that it works in IOS, i tried without success.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

The following recipe documents how to call JS from C#: https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/controls/call-javascript/

**Comment by andreybutko** [comment]
@davidbritch This is not the answer, because in case of using HybridWebView you don't have whole api, only part.

**Comment by vijaypalve** [comment]
How to call JS function form C# in HybridWebView as like RegisterAction ?
