### ISSUE TITLE
Issue with Master-Detail Page

### ISSUE THREAD

**Issue by Inrego** [xamarin/xamarin-forms-samples#222]
There's an issue with Master-Detail Page which makes it unusable on Windows 10 Desktop computers.

Basically, when you click a menu item, the menu closes and it's impossible to get the menu to show again. I also reported it on xamarin forums [here](https://forums.xamarin.com/discussion/99898/problem-with-masterdetailpage#latest) and on StackOverflow [here](https://stackoverflow.com/questions/45640159/xamarin-masterdetailpage-menu-on-uwp)
But no responses. I don't know where else to report bugs in Xamarin Forms. Now I'm posting here, since it's easily reproducable in the sample provided here.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that the hamburger menu behaves as expected in the latest stable release of Xamarin.Forms on UWP desktop in Win10.
