### ISSUE TITLE
Keyboard hiding in Todo Sample

### ISSUE THREAD

**Issue by nor0x** [xamarin/xamarin-forms-samples#224]
I just cloned the project and build the Todo sample on iOS and Android. I noticed that once i tap somewhere outside of an entry the keyboard gets dismissed, even though I couldn't find any code like `.resignFirstResponder `or `.endEditing`. Can anybody help me on how this was done, I'm trying to add this functionality to an other app as well - where it's not working out of the box.

PS: I know, not really an issue, but really I'm really interested in how this works and thought this would be the place to ask.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
