### ISSUE TITLE
Add UrhoSharp project to xamarin-forms-samples

### ISSUE THREAD

**Issue by abrasat** [xamarin/xamarin-forms-samples#225]
Would be possible please to add a UrhoSharp project to the xamarin-forms-samples repository?
The urho-samples from the dedicated repository dont seem to be maintained anymore. For instance none of the urho samples works for UWP in release mode.
The SkiaSharp samples are also available here in the xamarin-forms-samples.

**Comment by conceptdev** [comment]
Thanks for the suggestion, however the goals of _this_ samples repo is to remain focused on key skills and techniques for the majority of Xamarin.Forms developers. UrhoSharp samples are likely to remain available in their own repo.
