### ISSUE TITLE
The application won't run without Google Play services, which are missing from your phone.

### ISSUE THREAD

**Issue by smaperkings** [xamarin/xamarin-forms-samples#228]
I tried the project and I get this message:
The application won't run without Google Play services, which are missing from your phone.  With a button that ask me to get Google Play service. When I click on that button, the application crashes. I downloaded the solution and deployed it on android 4.4. I also tried to deploy it on android 5.5 but on that platform, the application crashed directly without even displaying anything.
What could be the issue.

**Comment by davidbritch** [comment]
Apologies for the delayed response. The issue is that Google Play services are missing from your emulator or phone, and must be installed to run the sample.

For more information, see https://developer.xamarin.com/guides/android/troubleshooting/questions/install-gps/
