### ISSUE TITLE
Xamarin Samples Compilation

### ISSUE THREAD

**Issue by armenhacopian** [xamarin/xamarin-forms-samples#234]
Please help with the following issues.  I am unable to compile older Xamarin samples in 2017.

![image1](https://user-images.githubusercontent.com/32861272/31648227-8a26024a-b2da-11e7-999e-039da3bd6989.png)
![image2](https://user-images.githubusercontent.com/32861272/31648228-8a31201c-b2da-11e7-842b-9178fab0780a.png)
![image3](https://user-images.githubusercontent.com/32861272/31648229-8a3aa9ac-b2da-11e7-88fd-419f1c85a50c.png)

**Comment by jamesmontemagno** [comment]
Can you post from where you download the sample from? Which one specifically.

Looks like you need to restore NuGets and maybe just close and re-open the solution.

**Comment by davidbritch** [comment]
Closing this issue due to no response to above.
