### ISSUE TITLE
Xamarin Mobile App Azure AD B2C. Up to date sample

### ISSUE THREAD

**Issue by kmbogus** [xamarin/xamarin-forms-samples#239]
Is there a chance someone could provide an updated sample as to using a Xamarin PCL Mobile App and verifying access via Azure AD B2C. Every sample I have seen is either out of date with MSAL or incomplete.

**Comment by Jhanbury** [comment]
Totally agree

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This sample was updated last November.
