### ISSUE TITLE
Forms Gallery - MasterDetailPage - Windows Phone - selection of current item not stable

### ISSUE THREAD

**Issue by manisko** [xamarin/xamarin-forms-samples#24]
On WP8:
1. Select some item from master list e.g. Blue
2. Show menu list again - Blue is not selected, another item is selected
3. Click button back and show menu again - another item is selected

**Comment by tatlacas** [comment]
Experienced the same

**Comment by davidbritch** [comment]
Fixed in WinPhone8.1.
