### ISSUE TITLE
Could not add new pin in map? I am getting following error.Please tell me how to refresh the map in customrenderer

### ISSUE THREAD

**Issue by RagulChandra** [xamarin/xamarin-forms-samples#248]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
