### ISSUE TITLE
CustomRenderers Map sample have to update

### ISSUE THREAD

**Issue by dengere** [xamarin/xamarin-forms-samples#249]
CustomPin.cs inherited Pin, but Xamarin.Forms.Maps.Pin class has been modified by "**sealed**"

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. The sealed modifier was dropped from the `Pin` class a release or two ago.

I've just examined this sample and made a minor update to it. I can confirm that it functions correctly.
