### ISSUE TITLE
Customizable Custom Tabs in TodoAzureAuthADB2CClientFlow

### ISSUE THREAD

**Issue by HenKun** [xamarin/xamarin-forms-samples#250]
The images on https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoAzureAuthADB2CClientFlow/ suggest that we can customize the custom tabs for  client flow with Azure AD B2C, at least to hide the URL bar. Now actually the customer is confronted with a browser like window with URL bar and Microsoft url which is not really native. Are these images from an older version and should be updated or is it somehow possible to hide the URL bar and/or customize the colors and title of the custom tab?

**Comment by conceptdev** [comment]
The `Microsoft.Identity.Client` library itself is still in preview [NuGet link](https://www.nuget.org/packages/Microsoft.Identity.Client). Once it reaches a stable build we'll be revisiting the sample. Thanks for your feedback, I hope that the latest versions of the sample will address it.
