### ISSUE TITLE
Can't compile 'Weather' example

### ISSUE THREAD

**Issue by ALIENQuake** [xamarin/xamarin-forms-samples#251]
Hi,
'Weather' example: https://github.com/xamarin/xamarin-forms-samples/tree/forms-macos-preview/

I cannot make it work or even compile. There are errors about missing nuget packages. Can somebody please update this example?

**Comment by MuriloViviani** [comment]
Have you loaded/downloaded the nuget packages needed for this example?
Sometimes this problem happens because of some issue in the nuget dowload manager, try to Left Click in the solution and select the option "Download Nuget Packages" this might work for you!

**Comment by ALIENQuake** [comment]
@MuriloViviani Nope, the problem is that this project is using old framework packages/locations etc. Needs to be recreated manually. I'm leaving this open but it's not a big issue.

**Comment by MuriloViviani** [comment]
Got it! tnks for the reply

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

Once the macOS support in Xamarin.Forms moves to stable we'll add macOS support to all the samples. Until then, any branches with macOS support are experimental.
