### ISSUE TITLE
Question: Why Themes is still in prerelease ?

### ISSUE THREAD

**Issue by Jerome2606** [xamarin/xamarin-forms-samples#254]
Hello,

I was wondering why this nuget Theme is still in prerelease ? 
Seems to be from years and definitively good way to make theming in Xamarin.Forms.

What is the status and support about this nuget package ?

**Comment by conceptdev** [comment]
Hi @Jerome2606 this is more of a product question than a sample issue. The [forums](https://forums.xamarin.com/) are probably the best place to ask this question.
