### ISSUE TITLE
TODORest -is the API still available?

### ISSUE THREAD

**Issue by clcProjects** [xamarin/xamarin-forms-samples#257]
HI,

I am able to build and run the TODoRest app, but it does not bring back any data. is the URL still available to use?
http://developer.xamarin.com:8081/api/todoitems{0} 

Thanks!

**Comment by clcProjects** [comment]
A quick followup, I tried connecting using fiddler as well:
**User-Agent: Fiddler
Host: developer.xamarin.com:8081
Authorization: Basic WGFtYXJpbjpQYSQkdzByZA==
Content-Type: text/json ; charset=utf-8
Content-Length: 0**

Result:
[Fiddler] The connection to 'developer.xamarin.com' failed. <br />
Error: ConnectionRefused (0x274d). <br />
System.Net.Sockets.SocketException No connection could be made because the target machine actively refused it 40.118.170.31:8081

**Comment by davidbritch** [comment]
Apologies for the delayed response to your issue. I've just tried this sample on iOS and the REST service running on developer.xamarin.com does indeed return data. However, it may be that the service was down earlier in the year.

Therefore I'm closing this issue.

**Comment by improwise** [comment]
This had us confused as well, please see this ticket https://github.com/xamarin/xamarin-forms-samples/issues/299 #299
