### ISSUE TITLE
Navigation Sample not working - MasterDetailPage

### ISSUE THREAD

**Issue by erotavlas** [xamarin/xamarin-forms-samples#258]
I downloaded the sample for MasterDetailPage under Navigation, opened it up in latest Visual Studio 2017 (15.5.2) and tried to run both the Android and WIndows UWP projects, but am unable.

The following errors occur (same for Android and UWP project set as startup)

![capture](https://user-images.githubusercontent.com/10454265/34799184-e1b7e7f4-f62c-11e7-9aaa-79ac3c9ff1e9.PNG)

Upon opening the solution I immediately restored nugget packages and also updated the packages that were installed (the ones that had pending updates) Xamarin Forms and .NET Core

**Comment by JoelP121** [comment]
Just rebuild and restore Nuggets again. I have been trying to make this MasterDetailPage work for a couple hours+ now.

**Comment by erotavlas** [comment]
Ok thanks, surprisingly most of the errors went away after restarting Visual Studio.  However one error persists.

> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0006	Metadata file 'C:\Users\me\Downloads\MasterDetailPage\MasterDetailPageNavigation\bin\Debug\MasterDetailPageNavigation.dll' could not be found	MasterDetailPageNavigation.UWP	C:\Users\me\Downloads\MasterDetailPage\UWP\CSC	1	Active

Restoring nugget packages again had no effect, says all packages are present.

**Comment by erotavlas** [comment]
I finally got it working for UWP (by moving the solution folder to another drvei (d) maybe it was a permissions error accessing content of that folder.

However Android is now giving a single error

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize). Java ran out of memory while executing 'java.exe -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\\lib\dx.jar" --dex --no-strict --output obj\Debug\android\bin D:\MasterDetailPage\Droid\obj\Debug\android\bin\classes\classes.zip "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v8.0\mono.android.jar" obj\Debug\lp\0\jl\formsviewgroup.jar obj\Debug\lp\10\jl\bin\classes.jar obj\Debug\lp\11\jl\bin\classes.jar obj\Debug\lp\12\jl\bin\classes.jar obj\Debug\lp\13\jl\bin\classes.jar obj\Debug\lp\14\jl\bin\classes.jar obj\Debug\lp\15\jl\bin\classes.jar obj\Debug\lp\16\jl\bin\classes.jar obj\Debug\lp\17\jl\bin\classes.jar obj\Debug\lp\18\jl\bin\classes.jar obj\Debug\lp\19\jl\bin\classes.jar obj\Debug\lp\20\jl\bin\classes.jar obj\Debug\lp\21\jl\bin\classes.jar obj\Debug\lp\3\jl\arch-core-common.jar obj\Debug\lp\4\jl\arch-lifecycle-common.jar obj\Debug\lp\5\jl\bin\classes.jar obj\Debug\lp\6\jl\bin\classes.jar obj\Debug\lp\8\jl\bin\classes.jar obj\Debug\lp\9\jl\bin\classes.jar C:\Users\me\AppData\Local\Xamarin\Xamarin.GooglePlayServices.Basement\8.4.0\embedded\classes.jar'	MasterDetailPageNavigation.Droid			
>

**Comment by conceptdev** [comment]
https://stackoverflow.com/questions/36835790/getting-outofmemoryexception-in-xamarin
