### ISSUE TITLE
How to show mapoverlay when mapoverlay too close edge

### ISSUE THREAD

**Issue by soncnttqb** [xamarin/xamarin-forms-samples#262]
How to update region of maps to show mapoverlay when mapoverlay too close edge

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
