### ISSUE TITLE
[XI] MonkeyApp Project fails to build with an error:  Failed to resolve "Newtonsoft.Json.JsonSerializerSettings" reference from "Newtonsoft.Json

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-forms-samples#267]
### Steps to Reproduce

1. Open https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/AzureSearch/MonkeyApp
2. Build Sample

### Expected Behavior
App should build successfully

### Actual Behavior
http://xqa.blob.core.windows.net/gist/report-c98cb1f5fdc54ff4a61de17de864362f.txt with d15-6
This App isn't building with d15-5 as well but the error is different. http://xqa.blob.core.windows.net/gist/report-d6fe7b751c49487cbfb0c0ea2d11a5a7.txt

##Test Env:
d15-6: 4c56cbbf025378220b7fa46d66aad9b40d5eb90a
d15-5: de65bf22cbc3dc232b8d002a7b04124505f45987

**Comment by dalexsoto** [comment]
The iOS project is missing the [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json) by adding that package into the Xamarin.iOS project a I am able to build successfully for device.

```diff
diff --git a/WebServices/AzureSearch/iOS/MonkeyApp.iOS.csproj b/WebServices/AzureSearch/iOS/MonkeyApp.iOS.csproj
old mode 100755
new mode 100644
index c84f29054..4d56e0e6d
--- a/WebServices/AzureSearch/iOS/MonkeyApp.iOS.csproj
+++ b/WebServices/AzureSearch/iOS/MonkeyApp.iOS.csproj
@@ -132,6 +124,11 @@
     <Reference Include="System.Xml.ReaderWriter" />
     <Reference Include="System.Linq.Expressions" />
     <Reference Include="System.Xml.XmlSerializer" />
+    <Reference Include="Microsoft.CSharp" />
+    <Reference Include="System.IO.Compression" />
+    <Reference Include="Newtonsoft.Json">
+      <HintPath>..\packages\Newtonsoft.Json.10.0.3\lib\netstandard1.3\Newtonsoft.Json.dll</HintPath>
+    </Reference>
   </ItemGroup>
   <ItemGroup>
     <ProjectReference Include="..\MonkeyApp\MonkeyApp.csproj">
```
