### ISSUE TITLE
how to show/get the current image position in wrap-layout?

### ISSUE THREAD

**Issue by Nishita1121** [xamarin/xamarin-forms-samples#270]
I want to show the current tapped image.
`   CarouselImage.Position = tagg;` with I got the index of image. This is working in iOS but not in android.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
