### ISSUE TITLE
How to handle if two pins on same co-ordinate?

### ISSUE THREAD

**Issue by RagulChandra** [xamarin/xamarin-forms-samples#271]
CustomPin GetCustomPin(MKPointAnnotation annotation)
        {
            var position = new Position(annotation.Coordinate.Latitude, annotation.Coordinate.Longitude);
            foreach (var pin in customPins)
            {
                if (pin.Position == position)
                {
                    return pin;
                }
            }
            return null;
        }

**Comment by conceptdev** [comment]
That would be an application-specific concern - you may choose to ensure the pin collection contains only unique elements, or use other attributes of the pin or annotation to distinguish between them.
