### ISSUE TITLE
ViewRenderer Constructor not Xamarin.Forms 2.5 Compatible (Android) !! :) Help

### ISSUE THREAD

**Issue by dgerding** [xamarin/xamarin-forms-samples#272]
Hi All,
I'm pretty sure I'm running into the same problem as others, which seems to be the that recommended constructor in Android renderer is now obsolete and won't compile.  `This is at least true for the Android implementation of the Renderer.  I haven't gotten to iOS yet.  

`public class HybridWebViewRenderer : ViewRenderer<HybridWebView, Android.Webkit.WebView>`

is the problem line.  

I tried some potential solutions [from here ](https://forums.xamarin.com/discussion/106796/avoiding-obsolete-default-constructor-with-android-custom-renderers-in-2-5) but had no luck.  

I have to get this working on XF2.5.x (release).  I'll follow up here if I have any luck.  Please do same if you have any ideas.

**Comment by davidbritch** [comment]
Apologies for the delayed response. I updated the entire repo to Xamarin.Forms 2.5 this week, and also updated the custom renderers to be Xamarin.Forms 2.5 compliant.

**Comment by dgerding** [comment]
Thanks!! 👍
