### ISSUE TITLE
Send Location to WebView

### ISSUE THREAD

**Issue by RSadocchi** [xamarin/xamarin-forms-samples#273]
Hallo all, how i can send a gps Location point retrived to a page in WebView in Xamarin.Forms PCL?

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
