### ISSUE TITLE
content of zip is different?

### ISSUE THREAD

**Issue by geedsen** [xamarin/xamarin-forms-samples#277]
I downloaded the zip but the content of the zip is completely different from what I would expect from this page https://github.com/xamarin/xamarin-forms-samples. I wanted to look at the CustomeRenderers, but it is not in the download.

**Comment by conceptdev** [comment]
The ZIP generated by GitHub definitely contains all the code in this repo (however note that it is over 460Mb download).

Alternatively, you can download ZIPs of individual samples from the [documentation](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/).
