### ISSUE TITLE
VideoPlayer start in fullscreen?

### ISSUE THREAD

**Issue by RobDaPraia** [xamarin/xamarin-forms-samples#280]
Is it possible to start the  VideoPlayer in fullscreen?

When opening a page, like the PlayWebVideoPage in the demo, would it be possible to start the VideoPlayer in fullscreeen instead of windowed? 

I want to use it in an app, but only need the fullscreen option

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
