### ISSUE TITLE
customPins collection is empty or null when GetViewForAnnotation runs

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/xamarin-forms-samples#289]
I downloaded the example and it works fine with a single pin as the example is written.

When I add a collection (say 200) custom pins for some reason the customPins collection is empty or null when GetViewForAnnotation runs...

I have tried to add the custom pushpins to the collection one at a time and I have tried to set the list from a populated list as well.... neither way works 

The code below runs without error .. but when GetViewForAnnotation runs the customPins list is always empty 

            try
            {

           
                MainOverviewMap.Pins.Clear();
                MainOverviewMap.CustomPins = new List<CustomPin>();

                foreach (var well in WellsNearby)
                {
                
                    var customPP = new CustomPin();
                    customPP.Type = PinType.SearchResult;
                    customPP.Position = new Position(well.Latitude, well.Longitude);
                    customPP.Label = $"Type {well.WellTypeID} : {well.WellID}";
                    customPP.Address = well.Comments;
                    customPP.Id = well.WellID.ToString();

                    Debug.WriteLine($"Before add pin count: {MainOverviewMap.CustomPins.Count}");
                    MainOverviewMap.CustomPins.Add(customPP);
                    Debug.WriteLine($"Added a pin: {customPP.Id}");
                    Debug.WriteLine($"After add pin count: {MainOverviewMap.CustomPins.Count}");
                    MainOverviewMap.Pins.Add(customPP);
                }

            }
            catch (Exception ex)
            {
                Debug.WriteLine("Error refreshing map plot " + ex.Message);
            }

**Comment by stephenhauck** [comment]
I just changed my code to match exactly and it still has no elements when the custom renderer tries to lookup the element ...

  MainOverviewMap.Pins.Clear();
                MainOverviewMap.CustomPins = new List<CustomPin>();

                Debug.WriteLine(JsonConvert.SerializeObject(WellsNearby));
                foreach (var well in WellsNearby)
                {

                    var customPP = new CustomPin
                    {
                        Type = PinType.SearchResult,
                        Position = new Position(well.Latitude, well.Longitude),
                        Label = $"Type {well.WellTypeID} : {well.WellID}",
                        Address = well.Comments,
                        Id = well.WellID.ToString()
                    };

                    Debug.WriteLine($"Before add pin count: {MainOverviewMap.CustomPins.Count}");
                    MainOverviewMap.CustomPins.Add(customPP);
                    Debug.WriteLine($"Added a pin: {customPP.Id}");
                    Debug.WriteLine($"After add pin count: {MainOverviewMap.CustomPins.Count}");

                    MainOverviewMap.Pins.Add(customPP);
                }

**Comment by stephenhauck** [comment]
Someone .......anyone ..... Someone has to have encountered this issue at some point ??

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
