### ISSUE TITLE
SpinPaint and SpinPaintShared crash on Android

### ISSUE THREAD

**Issue by davidbritch** [xamarin/xamarin-forms-samples#291]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/SpinPaint

AND

https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/SpinPaintShared

### Description

Both SpinPaint and SpinPaintShared build and run on iOS, but while the solutions build on Android they crash on startup with a `NullReferenceException`.

### Steps to Reproduce

1. Load each solution.
2. Run in an Android emulator.
3. Samples crash with a `NullReferenceException`.

### Expected Behavior

Samples run and allow the user to spin paint.

### Actual Behavior

Samples crash with a `NullReferenceException` in the `OnPaintSurface` method in the `MainPage.xaml.cs` file. This is because `surface` is `null`.

### Information

- IDE and IDE version: Visual Studio for Mac 7.4 (build 1033)
- Platform with the issue: 
  - Android: 8.1
- Device or simulator/emulator: Google emulator (API 26).

**Comment by charlespetzold** [comment]
I have tested SpinPaint on VS 2017 for Windows (15.6.2) with Android 8.1 on 3 Android devices and 3 emulators, and could not reproduce the problem.

**Comment by charlespetzold** [comment]
I have also tested SpinPaint on VS 2017 for Mac (7.4) with an Android device, and still could not reproduce the problem. (In other words, it runs fine.) 

Unfortunately, I am not nearly smart enough to use Android emulators on VS 2017 for Mac.

**Comment by davidbritch** [comment]
Retried this with the latest everything and it's no longer an issue.
