### ISSUE TITLE
Xamarin.amdroid

### ISSUE THREAD

**Issue by sagarmp02** [xamarin/xamarin-forms-samples#297]
I need to implement auto capture image without user interaction after some seconds. help me
![lrfit](https://user-images.githubusercontent.com/37401688/37518855-f5524cb2-293c-11e8-80f4-a8e713276ed5.png)

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This is more of a support request rather than a sample issue. The [forums](https://forums.xamarin.com/categories/xamarin-forms) or [stackoverflow](https://stackoverflow.com) are probably the best place to ask this question.
