### ISSUE TITLE
REST WebAPI does not work

### ISSUE THREAD

**Issue by improwise** [xamarin/xamarin-forms-samples#299]
Am I the only one that can not browse the supped URL of the hosted REST service?

http://developer.xamarin.com:8081/api/todoitems/

Seems to try to redirect to some HTTPS which isnt working:

This site can’t provide a secure connection
developer.xamarin.com sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

The Sample Project wont even build with the latest VS2017 installed With Mobile Development for .NET.....

**Comment by improwise** [comment]
Seems to be working if you supply the credentials, strangely enough when browsed through a browser did not indicate this error properly but tried to redirect to HTTPS which did not work so probably a configuration error.

**Comment by improwise** [comment]
Also, the version hosted at Xamarin (https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoREST/) is obsolete and wont build in VS2017.

**Comment by davidbritch** [comment]
Both of the server side REST services (ASP.NET Core, and ASP.NET WebAPI 2) build fine in VS2017. In addition, the mobile app (TodoREST) also builds fine in VS2017, with the exception of the WinPhone81 project.

**Comment by improwise** [comment]
Please note that it was the old version at Xamarin.com that did not work in a freshly installed VS2017 (with necessary components). The latest version hosted here did build ok.
