### ISSUE TITLE
TodoREST not working on Android using Xamarin Live Player

### ISSUE THREAD

**Issue by improwise** [xamarin/xamarin-forms-samples#300]
This sample works fine when runing with UWP locally, but when setting startup project to Android and try running via Xamarin Live Player it fails. First, unless you comment out the Alert in TodoListPage.xaml.cs it does not seem to even make it to data loading. If you remove that alert, it will try to load data from REST but will crash as it seems. This have been reproduced on both a Google Nexus 6 and a Samsung Note 8. 

This is the actually the reason we even tried to use the TodoREST sample, as we experienced the exact same problems in our app, that REST did not work on Android but on UWP. We tried with direct HTTPClient calls, as well as using several frameworks like RestSharp etc, neither worked and had about the same problems. 

This is with a freshly installed VS2017 15.6.2 with Mobile Development for .NET installed.

**Comment by davidbritch** [comment]
The problem here is Live Player. It only has limited support for reflection, and JSON.NET uses reflection. See the [Live Player Limitations](https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations).

**Comment by improwise** [comment]
Thanks for the comment David. So you are basically saying that any samples that use JSON wont work with the Live Player then? We looked into the TODORest but cant find that JSON.NET is installed as a NuGet at least, are there other components using that?

**Comment by improwise** [comment]
Can confirm that after giving up on the Live Player (heavily promoted by Visual Studio) and throwing out the Android Emulator that gets installed by VS2017 by default and instead install the Visual Studio Emulator, we were finally  able to get this to work. Please note that the Visual Studio Emulator, "Visual Studio Emulator for Android", is NOT the one default installed by Visual Studio, it can be downloaded from https://www.visualstudio.com/vs/msft-android-emulator/.

**Comment by Tam66662** [comment]
@improwise @davidbritch 

> First, unless you comment out the Alert in TodoListPage.xaml.cs it does not seem to even make it to data loading

For me, this also was the case, but I found that the root-cause was because the display renderer wasn't ready yet on first pass, and therefore it could not show the alert.  The output window stated:

> 03-22 09:51:19.795 W/View    (30180): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{d62a326 V.E...... ........ 0,0-1080,1848 #1} during second layout pass: posting in next frame

To fix this problem, all I did was add "await Task.Delay(100);" before the Alert, and everything worked, including the population of the data from REST.  Just thought I'd shared this in case anyone else came across this problem with the data not loading on first launch of the Android app.
