### ISSUE TITLE
TodoAWSAuth authentication hangs

### ISSUE THREAD

**Issue by mipnw** [xamarin/xamarin-forms-samples#303]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAWSAuth

### Description

Clicking the Login button in the app brings opens a browser to perform google authentication, and when that's done, the browser is authenticated, but not the TodoAWS.Droid app.

### Steps to Reproduce
I followed the instructions provided at https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoAWSAuth/ and created a Cognito Identity Pool with unauthenticated users enabled and permission to AWS SimpleDB. Not that this matters actually since the problem described here fails before the handshake with AWS.

I also created a Google Developer Project, and within that project created OAUTH credentials and obtained a Client ID for an Android App, with package name set to "com.companyname.todoaws_simpledb" so as to match this sample app.

As instructed, I pasted the Cognito Identity Pool ID in Constants.CognitoIdentityPoolId and the Google Client App ID in Constants.AndroidClientId. I also reversed that Google Client App ID and appended it with ":/oauth2redirect" and pasted that in Constants.AndroidRedirectUrl. I left the iOS constants un-edited, that's OK I won't be building the iOS client.

I set the TodoAWS.Droid project as my Visual Studio Startup Project, updated the Solution Configuration to not only build but also Deploy that project, and then built the solution.

My device is an emulated Nexus 5X API 26 (that doesn't matter here).

Repro:
- I set breakpoints in LoginPage.OnAuthCompleted and LoginPage.OnAuthError and start debugging.
- The app launches on my device, I click the Login button. The app loads a google page, I authenticate with my google account, then the page loads www.google.com, and it's clearly authenticated (I see my google account name on the page). 
- That's weird, that's the landing page for google's search engine, I was expecting to land back in TodoAWS.Droid once authenticated. Also neither of my breakpoints hit, so authentication within LoginPage is basically hanging, it didn't succeeded and it didn't fail.

### Side notes:
 
If instead of OAUTH credentials for an Android App, I create OAUTH credentials for a Web App, clicking the Login button launches a browser and authentication will fail in the browser with a message that says "custom scheme URIs are not allowed for 'WEB' client type", thereby confirming this sample expects the OAUTH credentials to be of type 'Android App'

### Expected Behavior
After google's authentication I was expecting to land back inside the TodoAWS app, and the UI giving me the option to create Todo notes, as well as somehow visually inform me that I am authenticated.

### Actual Behavior

Instead I land on google search engine's website. On the device if I switch apps from the browser back to TodoAWS.Droid, I see the initial activity with a Login button, like nothing happened.

### Information

- IDE and IDE version:Visual Studio 2017 v15.6.3
- Platform with the issue:
  - Android:    VS build targetFramework is set to "Use Latest Platform (Android 8.1)"
- Device or simulator/emulator: emulated Nexus 5X API 26

**Comment by davidbritch** [comment]
Thanks for opening the issue, and apologies for the delayed response to it.

Following an internal discussion, and now that Amazon has content on using the [AWS Mobile SDK for .NET and Xamarin](https://docs.aws.amazon.com/mobile/sdkforxamarin/developerguide/Welcome.html), we've decided to retire our AWS content. Therefore, I'm closing this issue.
