### ISSUE TITLE
TodoAWSAuth should use authenticated Cognito Identity Pool

### ISSUE THREAD

**Issue by mipnw** [xamarin/xamarin-forms-samples#304]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAWSAuth

### Description

TodoAWSAuth is described (https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoAWSAuth/) as a sample which demonstrates how to authenticate with Google, use AWS Cognito Identity Pool, and reads/writes to AWS SimpleDB in Xamarin-Forms.

The audience for that sample app is therefore expecting to learn how to use an AWS Cognito Identity Pool with Google as authentication provider.

It turns out, this sample uses Google authentication on the client app, but then connects unauthenticated to AWS Cognito, which is very misleading. It took me a while to learn download this sample, read its source code, deploy and debug it, only to find out it does not do what I thought it did from its description page.

### Expected Behavior

A sample Xamarin-Forms app which connects to AWS Cognito with a google authentication provider.

### Actual Behavior

A sample Xamarin-Forms app which connects to AWS Cognito unauthenticated.

**Comment by davidbritch** [comment]
Thanks for opening the issue, and apologies for the delayed response to it.

Following an internal discussion, and now that Amazon has content on using the [AWS Mobile SDK for .NET and Xamarin](https://docs.aws.amazon.com/mobile/sdkforxamarin/developerguide/Welcome.html), we've decided to retire our AWS content. Therefore, I'm closing this issue.
