### ISSUE TITLE
How to customize TabbedPage to BottomTabBar in Android and UWP, just like the iOS style

### ISSUE THREAD

**Issue by hupo376787** [xamarin/xamarin-forms-samples#307]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/TabbedPageWithNavigationPage

### Description

Many android and uwp apps are more and more have the same style like iOS, the same thing to TabbedPage.

How to customize TabbedPage to BottomTabBar in Android and UWP, just like the iOS style?

### Expected Behavior
All TabbedPage behave like this.

![01ios](https://user-images.githubusercontent.com/14960168/37876048-ea5c24b0-3079-11e8-9d0e-13bd086ae78a.jpg)

### Actual Behavior
![01all](https://user-images.githubusercontent.com/14960168/37876062-18ec0ad4-307a-11e8-9a81-92bded58c0c0.jpg)

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. This functionality will be forthcoming in a future release of Xamarin.Forms - https://github.com/xamarin/Xamarin.Forms/pull/1748
