### ISSUE TITLE
Can the Xamarin.Forms be combined with Xamarin.IOS or Xamarin.Android in the same project? Is there an example?

### ISSUE THREAD

**Issue by ghd258** [xamarin/xamarin-forms-samples#311]
Can the Xamarin.Forms be combined with Xamarin.IOS or Xamarin.Android in the same project? Is there an example?

**Comment by ghd258** [comment]
Can cross platform development Xamarin.Forms be combined with Xamarin.IOS or Xamarin.Android in the same project or mixed use?

**Comment by davidbritch** [comment]
You can embed Xamarin.Forms ContentPages in Xamarin.iOS/Xamarin.Android projects using the Native Forms feature - https://docs.microsoft.com/xamarin/xamarin-forms/platform/native-forms

In addition, you can reference native iOS/Android controls in Xamarin.Forms projects - https://docs.microsoft.com/xamarin/xamarin-forms/platform/native-views/
