### ISSUE TITLE
Samples link for AzureADB2CAuth goes to missing page

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-forms-samples#314]
https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/AzureADB2CAuth

This link isn't right

https://github.com/xamarin/xamarin-forms-samples/blame/master/WebServices/AzureADB2CAuth/README.md#L6

**Comment by davidbritch** [comment]
Fixed the readme.
