### ISSUE TITLE
Custom map renderer on Android - Adding / removing pins and custom icon

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/xamarin-forms-samples#318]
My usage scenario is as follows:
      Get data from the database
      Clear the map if there are points - Seems easier than trying to manage data points / pins ??
      Plot the new points with custom marker images

The iOS custom renderer seems to function properly....
So I am adding about 200 pins to a map and that works ...

The user needs to be able to filter the "pins" 

When I want to remove a pin from the map it seems there is no way to clear the pins from the map in the PCL / .NET Standard library code base ???

So I tried to remove the pins like so ....
`MainOverviewMap.Pins.Clear();`
and 
```
 foreach (var pin in MainOverviewMap.Pins.ToList())
 {
       MainOverviewMap.Pins.Remove(pin);
 }
```

The problem is that when you add a pin in the PCL / .NET Standard library code the "CreateMarker" fires in the custom renderer  and I can set the custom icon.

When you remove a pin in the PCL / .NET Standard library code nothing fires in the custom renderer code as far as I can tell to remove the pin / marker from the google map.

I am using Xamarin.Forms.Maps - 2.5.1.444934
VS 2017 - 4.7.02556
Android - Api 23 (HAXM simulator)

Any advice you can offer on what I may be doing wrong or how to accomplish this would be greatly appreciated

**Comment by davidbritch** [comment]
Hi @stephenhauck this is more of a support question than a sample issue. The forums are probably the best place to ask this question.
