### ISSUE TITLE
ActivityIndicator does not work in Android

### ISSUE THREAD

**Issue by SamuelLioult** [xamarin/xamarin-forms-samples#320]
Hi,

I have an issue with the ActivityIndicator control. It works well on iOS and Windows devices but not with my Android device (API 23).

My basic code is just the following:
`<ActivityIndicator IsRunning="True"
                           VerticalOptions="CenterAndExpand"
                               Color="Red"
                               BackgroundColor="Yellow"/>`

When I execute this code, I can see the yellow background but not the ActivityIndicator.

Thanks.

### Information

- IDE and IDE version: Visual Studio 2017 Community edition v15.5.4
- Platform with the issue: 
  - Android: 6.0.1 (API 23)

**Comment by sayob** [comment]
@SamuelLioult You may want to try setting the indicator's visibility to true in the C# behind. that should do it

**Comment by SamuelLioult** [comment]
@sayob Thanks for your help but it has no effect. So I reported this issue on the [Xamarin Forms repository](https://github.com/xamarin/Xamarin.Forms/issues/2541)

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. As it's an issue with Xamarin.Forms itself, rather than a sample, and as you've logged the issue in the Xamarin.Forms repository, I'm closing the issue here.
