### ISSUE TITLE
Map Rendering with UWP fails

### ISSUE THREAD

**Issue by ctacke** [xamarin/xamarin-forms-samples#330]
I recently upgraded a working Xamarin Forms application that uses Maps to XF 3.0.  The UWP app fails to run now.  In an attempt to determine what is wrong with my app, I decided to go back to the XF Samples.  Well it seems that the Samples app also has the same failure.  So yay, it's not my app, but come on - I'd expect the samples to have been tested with new releases (or new releases to have been tested with the samples).

I loaded the sample, put in my Bing Maps key and run in the debugger (Studio 2017 Community, 15.7.3).  I get an UnhandledException in App.g.i.cs.  It contains an  SEHException with a message of "External component has thrown an exception."

The stack trace is:

>    at Windows.UI.Xaml.Controls.Maps.MapControl.put_MapServiceToken(String value)
   at Xamarin.Forms.Maps.UWP.MapRenderer.<OnElementChanged>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

In my own app I was able to debug it to, I believe, a NullReferenceException - but it's got  the exact same stack trace.

**Comment by ctacke** [comment]
I did a bit more debugging on this.  I pulled in the Xamarin.Forms.Maps source code projects to the sample app to step through the failure.

The exception is getting thrown in MapRenderer.cs of the Xamarin.Forms.Maps.UWP project, specifically at line 37, which looks like this:

`Control.MapServiceToken = FormsMaps.AuthenticationToken;`

At this point `Control` is a valid instance and `FormsMaps.AuthenticationToken` is returning a valid string.  It seems that the call to set the MapServiceToken property on the Control instance is what's exploding.  Unfortunately that call is in Windows.Foundation.UniversalApiContract, which I don't have source for, so I can't really chase this any further.  It's most certainly a show-stopper bug.

**Comment by davidbritch** [comment]
Thanks for logging this issue. I just popped my Bing map key into [this](https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin) sample and it worked fine on UWP. This is using VS 15.7.1. I'm currently updating to 15.7.3 and will re-test then.

**Comment by ctacke** [comment]
Two full development days wasted just because a change was made somewhere that made keys that used to work fail and then a meaningful error about the failure couldn't be passed upstream.  This sort of thing is what adds friction to platform adoption.

**Comment by davidbritch** [comment]
Thanks for bringing this to our attention. I'll close the issue here, as I've logged an issue in the Xamarin.Forms repo for the engineering team to investigate.

**Comment by PorkiePie** [comment]
#ctacke did you find a workaround for this?

I have tried changing the key type but still get the same error.

**Comment by ctacke** [comment]
I did.  The error is still some serious BS because somewhere in the call stack any meaningful information about the failure is getting stripped.  The key is that you *cannot* use a development maps key.  You used to be able to and I don't know at what version things went sideways.  I'm pretty sure it's a change down in the universal platform code, though.  Create an entirely new key, with Key Type of "Basic" and "App Type" of either "public" or "private Windows Windows App"

**Comment by PorkiePie** [comment]
#ctacke thanks for prompt reply. Things have moved on! I had previously tried to change the application type by editing updating the key and changing. I only created this key 2 -3 days ago. I just followed your advice and created a new key and now there are 2 new options relating to public and private UWP apps.

I created the key with a public UWP key and it now works as advertised. So MS have fixed something in Bing I guess. FYI the new key is twice as long as the old one which is interesting in itself.

**Comment by VWilcox2000** [comment]
Really appreciate you guys posting this!  I wasted a few hours throwing try / catches all over the place and adding unhandled exception errors that never caught anything -- they still haven't added a reasonable message to let us know a missing key is the issue.
