### ISSUE TITLE
SQLiteAsyncConnection issue VS2017

### ISSUE THREAD

**Issue by colton9182** [xamarin/xamarin-forms-samples#332]
using System.Collections.Generic;
using System.Threading.Tasks;
using SQLite.Net.Async;

namespace Todo
{
    public class TodoItemDatabase
    {
        readonly SQLiteAsyncConnection database;

        public TodoItemDatabase(string dbPath)
        {
            database = new SQLiteAsyncConnection(dbPath); 
            database.CreateTableAsync<TodoItem>().Wait();
        }
---------------------------------------------------------
Produces error: CS1503 Argument 1: cannot convert from 'string' to 'System.Func<SQLite.Net.SQLiteConnectionWithLock>'

---------------------------------------------------------
error occurs on line: database = new SQLiteAsyncConnection(dbPath);

**Comment by davidbritch** [comment]
Can you confirm the sample you're receiving this error on? Is it [Todo](https://github.com/xamarin/xamarin-forms-samples/tree/master/Todo)?

What platform are you getting the error on? The sample is compiling fine for me.

**Comment by colton9182** [comment]
This is for the ToDo sample. The error is occurring on Win10, VS 2017 across Android, iOS, and UWP. The only way I can get around on failure to build is to manually build out the connection like:

```
            string databasePath = "dbPath";
            var database = new Func<SQLiteConnectionWithLock>(() => new SQLiteConnectionWithLock(sqlitePlatform, new SQLiteConnectionString(databasePath, storeDateTimeAsTicks: false)));
            var sQLiteAsyncConnection = new SQLiteAsyncConnection(database);
```

but this requires additional work in the views and a separate return, I feel as it shouldn't be this complicated.

**Comment by renzimu** [comment]
Hi, all

Thank you for your attention.

So far, I have not use SQLite in my project in hand.

**Comment by davidbritch** [comment]
The Todo sample uses multiple SQLite NuGet packages - they are what provide the `SQLiteAsyncConnection` type.

Looking at your code it looks like you're using the wrong SQLite NuGet packages. I suggest you read [Local Databases](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/databases) and look at at the [Todo](https://github.com/xamarin/xamarin-forms-samples/tree/master/Todo) sample as this sample works and uses the correct SQLite NuGet packages.
