### ISSUE TITLE
Some UWP sample projects are missing png files

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#333]
### Sample
The following UWP sample projects are missing png files:
UserInterface\ListView\SwitchEntryTwoBinding\twoWayBinding  : need to add bulb.png
UserInterface\ListView\BuiltInCells : need to add lettuce.png, tomato.png, zucchini.png
UserInterface\TableView\TableViewSamples : need to add XamarinLogo.png

Are you guys going to fix the inability to display icons on tabbed pages without a hack in a UWP project?

### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Thanks for letting me know. I've updated the UWP projects with the specified files.

As for display icons on a `TabbedPage` on UWP, this is coming in Xamarin.Forms 3.1. See [this](https://github.com/xamarin/Xamarin.Forms/pull/1952) for the PR.
