### ISSUE TITLE
No resource found

### ISSUE THREAD

**Issue by RogerSchmidlin** [xamarin/xamarin-forms-samples#335]
I downloaded your sample and ran it on my visual studio on my mac. I got a runtime error. Xcode version 9.4, latest visual studio, and latest simulator. I have not touched the code at all.
<img width="503" alt="screen shot 2018-06-11 at 4 57 30 pm" src="https://user-images.githubusercontent.com/6247289/41222298-18dc56d2-6d99-11e8-9d4f-8af66ee68646.png">

Any ideas?

**Comment by 40345839668** [comment]
My dear friend, the most recent updates and downloaded software depending on the changes and updates made

**Comment by 40345839668** [comment]
CSS and HTML5

**Comment by davidbritch** [comment]
@RogerSchmidlin Thanks for letting me know. It's working fine in Xcode 9.3 for me. I'll upgrade to Xcode 9.4 and see what's going on.

**Comment by davidbritch** [comment]
@RogerSchmidlin I've updated to Xcode 9.4, and VS for Mac 7.5.2 (build 40) and still can't reproduce your issue. The MonkeyAppCSS sample builds and runs for me.

**Comment by RogerSchmidlin** [comment]
I upgraded to the beta release of visual studio on Mac and with no changes to the MonkeyAppCSS and it works now. I am good for now.
