### ISSUE TITLE
Tizen samples are missing

### ISSUE THREAD

**Issue by wiertel** [xamarin/xamarin-forms-samples#338]
### Sample
All sample apps 

### Description
Tizen sample apps are missing

### Information
Tizen is officially supported as a stable Xamarin.Forms platform (https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support) but all sample apps do not include relevant Tizen project.

First set of apps (70 apps) is available as PR #245 rebased today.

**Comment by Piotr12** [comment]
@davidbritch are you planning a mass update to [3.1](https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-3.1/3.1.0/) similar to [one from May 15th](https://github.com/xamarin/xamarin-forms-samples/commit/12ee338b4d5e4b3769b2ef3413add97161617741)? 

There are some sample apps which will benefit from fixes it brings to Tizen (e.g. gestures). It would great if you could merge #245 before the mass update though.

**Comment by davidbritch** [comment]
Closing following a discussion with Samsung over email.
