### ISSUE TITLE
Incorrect left padding in Android

### ISSUE THREAD

**Issue by LaloCo** [xamarin/xamarin-forms-samples#339]
If I set Layout Compression to a StackLayout that is defined inside a ScrollView, the result on Android has some extra left padding. On iOS it looks fine, the exact same way as without Layout Compression.

My code looks something like this:

    <ContentPage.Content CompressedLayout.IsHeadless="True">
        <ScrollView>
            <StackLayout VerticalOptions="Center"
                         CompressedLayout.IsHeadless="True"
                         Margin="20">
                <Image x:Name="iconImage"
                       Aspect="AspectFit"
                       HorizontalOptions="FillAndExpand"
                       Margin="0, 0, 0, 50"
                       HeightRequest="150"/>
                <Entry x:Name="EmailEntry" 
                       Placeholder="Email address"
                       Keyboard="Email"            />
                <Entry x:Name="PasswordEntry"
                       Placeholder="Password"
                       IsPassword="True"/>
                <Button x:Name="LoginButton" 
                        Margin="0,50,0,0"
                        Text="Log in"/>
                <Button x:Name="RegisterUserButton" 
                        Margin="0,50,0,0"
                        Text="Register"
                        HorizontalOptions="End"            />
            </StackLayout>
        </ScrollView>
    </ContentPage.Content>

**Comment by davidbritch** [comment]
Hi @LaloCo 

Thanks for bringing this to our attention. However, this repo is for logging issues with Xamarin.Forms samples, rather than with Xamarin.Forms features. Therefore I've opened an issue in the Xamarin.Forms repo for you: https://github.com/xamarin/Xamarin.Forms/issues/3287
