### ISSUE TITLE
MobileCRM build error

### ISSUE THREAD

**Issue by fabiencomte** [xamarin/xamarin-forms-samples#34]
Hello,
There is an error probably linked to a Android.Support.v7.MediaRouter change

C:\Users\fcomte\AppData\Local\Xamarin\Android.Support.v7.MediaRouter\19.1.0\content\support\v7\mediarouter\res\values\themes.xml(0,0): Error: No resource found that matches the given name (at 'mediaRouteButtonStyle' with value '@style/Widget.MediaRouter.MediaRouteButton'). (MobileCRM.Android)

**Comment by conceptdev** [comment]
This sample has been deprecated and is no longer supported.

Check out https://github.com/xamarin/app-crm instead.
