### ISSUE TITLE
Video is not playing in UWP

### ISSUE THREAD

**Issue by NvVijayakumara** [xamarin/xamarin-forms-samples#340]
### Description
Hi, for UWP, I tried 'Play Video Resource' option,  but its not playing video, it just showing just progress for some time. 

### Steps to Reproduce=
1. Run app by targeting UWP
2. Select 'Play Video Resource' option
3. Corresponding page will open.

### Expected Behavior
For UWP, I tried 'Play Video Resource' option,  but its playing video, it just showing progress. 

### Actual Behavior
I checked in Android, its working fine.

### Information
- IDE and IDE version: Visual Studio 2017 v15.7.4
- Platform with the issue: 
  - UWP: The version of the UWP SDK you are compiling against, e.g. 16299

**Comment by davidbritch** [comment]
Hi @NvVijayakumara 

I just tried to repo your issue and I can't. The video on the "Play Video Resource" page plays just fine for me on UWP. I suggest you make sure that you're VS2017 and Windows installs are completely up to date.
