### ISSUE TITLE
android:targetSdkVersion="26" causes JSBridge from HybridWebView control to no longer work

### ISSUE THREAD

**Issue by pabloalbanese** [xamarin/xamarin-forms-samples#343]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/HybridWebView

### Description

I wanted to report about an closed problem in this other repo: https://github.com/xamarin/Xamarin.Forms/issues/1376 for which this warning was added in the documentation here: https://docs.microsoft.com/es-es/xamarin/xamarin-forms/app-fundamentals/custom-renderer/ hybridwebview which says:

On Android Oreo ensure that the Android manifest sets the Target Android version to Automatic. Otherwise, running this code will result in the error message "invokeCSharpAction is not defined".

While it is true that if I remove the targetSdkVersion tag from the manifest.xml the problem is solved, that brings a new problem that Google Play Store does not recognize the target version of the SDK. This problem is described in this post: https://blog.xamarin.com/android-apps-google-play-target-api-level-requirements/

Which means that I can not publish the HybridWebView in production.

### Expected Behavior

To be able to specify the target android version 26 or higher and that the hybridwebview does not show the error invokeCSharpAction is not defined

### Actual Behavior

error invokeCSharpAction is not defined

### Information

- IDE and IDE version: Visual Studio 2017 v15.7.1
- Platform with the issue: 
  - Android: 8.0.0
- Device or simulator/emulator: devices for example with Android 8.0.0.

**Comment by Nguyentung79** [comment]
Fgghjnlm

**Comment by tung83** [comment]
following the thread of https://forums.xamarin.com/discussion/83115/webview-evaluatejavascript-or-loadurl-is-not-working
i found the solution to fix it from loading js; i think in new sdk they just allow js in OnPageFinished of webview
Here is my modification:

    public class HybridWebViewRenderer : ViewRenderer<HybridWebView, Android.Webkit.WebView>
    {
        const string JavaScriptFunction = "function invokeCSharpAction(data){jsBridge.invokeAction(data);} ; ";
        Context _context;

        public HybridWebViewRenderer(Context context) : base(context)
        {
            _context = context;
        }

        protected override void OnElementChanged(ElementChangedEventArgs<HybridWebView> e)
        {
            base.OnElementChanged(e);

            if (Control == null)
            {
                var webView = new Android.Webkit.WebView(_context);
                webView.Settings.JavaScriptEnabled = true;
                webView.Settings.DatabaseEnabled = true;
                webView.Settings.DomStorageEnabled = true;
                webView.SetWebViewClient(new JavaScriptWebViewClient(string.Format("javascript: {0}", JavaScriptFunction)));
                SetNativeControl(webView);
            }
            if (e.OldElement != null)
            {
                Control.RemoveJavascriptInterface("jsBridge");
                var hybridWebView = e.OldElement as HybridWebView;
                hybridWebView.Cleanup();
            }
            if (e.NewElement != null)
            {
                Control.AddJavascriptInterface(new JSBridge(this), "jsBridge");
                Control.LoadUrl(string.Format("file:///android_asset/Content/{0}", Element.Uri));
            }
        }
        public class JavaScriptWebViewClient : WebViewClient
        {
            string _javascript;
            public JavaScriptWebViewClient(string javascript)
            {
                _javascript = javascript;

            }
            public override void OnPageFinished(Android.Webkit.WebView view, string url)
            {
                base.OnPageFinished(view, url);
                view.EvaluateJavascript(_javascript, null);                
            }
        }
    }

**Comment by pabloalbanese** [comment]
thanks @tung83 , it's works!!!

Someone should change the example and official documentation because it doesn't work on Android without making those changes.

**Comment by tung83** [comment]
Great, Thanks @pabloabanese , did you run their example on ios, does it work as expectation? I need ios for my app too but have no mac to test now!

**Comment by kspearrin** [comment]
Thanks @tung83 

Android docs seem to explain the change here:

https://developer.android.com/reference/android/webkit/WebView.html#evaluateJavascript(java.lang.String,%20android.webkit.ValueCallback%3Cjava.lang.String%3E)

> Compatibility note. Applications targeting Build.VERSION_CODES.N or later, JavaScript state from an empty WebView is no longer persisted across navigations like loadUrl(String). For example, global variables and functions defined before calling loadUrl(String) will not exist in the loaded page. Applications should use addJavascriptInterface(Object, String) instead to persist JavaScript objects across navigations.

**Comment by davidbritch** [comment]
Hi @pabloalbanese 

Thanks for fixing this, and apologies for the delayed response.
