### ISSUE TITLE
Azure ADB2C UIOptions give me error

### ISSUE THREAD

**Issue by Malith1994124** [xamarin/xamarin-forms-samples#348]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/AzureADB2CAuth

### Description

When i try to implement same B2C login code in new app it say ui options not working in microsoft identity client library but if i used same code it works.

Visual Studio 2017
Xamarin Forms 2.3.4.231

**Comment by 40345839668** [comment]
You should go back and claim the code for re-entry, dear friend, try to renew the page.

**Comment by davidbritch** [comment]
This sample has since been refreshed, using a later release of MSAL.
