### ISSUE TITLE
Add an example for OnMeasureDelegate and OnLayoutDelegate

### ISSUE THREAD

**Issue by ddobrev** [xamarin/xamarin-forms-samples#353]
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/NativeEmbedding only uses GetSizeDelegate and it's not clear how to use OnMeasureDelegate and OnLayoutDelegate.

**Comment by conceptdev** [comment]
@ddobrev thanks for your suggestion. We try to cover key scenarios in our content, and we appreciate developers letting us know what is important to them. I've added your request to our backlog.
