### ISSUE TITLE
I get a weird error ( error: 'CustomMapRenderer.GetViewForAnnotation(MKMapView, IMKAnnotation)': no suitable method found to override) during run time with Live Player

### ISSUE THREAD

**Issue by jmah322** [xamarin/xamarin-forms-samples#357]
### Description

I am able to compile CustomMapRenderer for iOS.  However, during run time, I am error-ing out with the following error:

 error: 'CustomMapRenderer.GetViewForAnnotation(MKMapView, IMKAnnotation)': no suitable method found to override

When I look at MapRenderer it defines GetViewForAnnotation as a protected virtual method so it should let you override it.  Not sure what the heck is going on here....   

### Steps to Reproduce

1.  Follow the example for CustomMapRender
2.  Build w/o error
3.  Run an example that uses CustomMap and it errors out with the above message.

### Expected Behavior

I should be able to render a custom map with custom pins. 

### Actual Behavior

Map shows quickly and crashes iOS app.

### Information

- IDE and IDE version: Visual Studio 2017 v15.7.1
- Platform with the issue: 
  - iOS:  Default SDK -- no other options on the dropdown.
simulator/emulator --> Live Player

**Comment by davidbritch** [comment]
Hi @jmah322 

This sample works correctly on the iOS simulator so it'll be a problem with Live Player. I recommend switching to the iOS simulator if possible.

**Comment by jmah322** [comment]
Hi David,

Thank you for the quick response.  Live Player deploys code to an actual physical device to run and validate against it -- which is the end goal for app development.  That said, just because it works on the simulator, it doesn't guarantee it will work on a physical device -- does it?  I don't have a Mac environment setup.   I will see if I can find/create one and run it on the simulator to observe the behavior.  

BTW, do you know which version of iOS SDK works with CustomMapRenderer?  I am thinking that might be the root cause.  

Thanks

**Comment by davidbritch** [comment]
Hi @jmah322 

Live Player runs apps in a sandbox and has a lot of [limitations](https://docs.microsoft.com/xamarin/tools/live-player/limitations), including that it doesn't support custom renderers. Live Player is the source of your issue here.

The sample works fine once you run it in a simulator/on device (without live player).

**Comment by jmah322** [comment]
Thanks David for the response.  I have deployed the code to the app w/o Live Player and it’s crashing just like when it’s in Live Player.  I am running iOS 11.4.1.   What you recommend me trying?  Should I downgrade iOS to a previous version?  I am thinking it’s a version compatibility issue.  Thoughts?

Sent from Mail for Windows 10

**Comment by davidbritch** [comment]
Hi @jmah322 

While I think I know which sample you're referring to, can you provide a link to it so there are no misunderstandings. Thanks.

**Comment by jmah322** [comment]
Hi David,

Here is the link to the sample that I am using….

https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin

Thanks!

Sent from Mail for Windows 10

**Comment by davidbritch** [comment]
Hi @jmah322 

There's definitely nothing wrong with the sample. I've been able to run it on my iPhone (iOS 11.4.1). Have you tried deleting the bin/obj directories before deploying it? There may be some artefacts left over from when you were running it on LivePlayer.

**Comment by jmah322** [comment]
Thanks, David.  Let me clean the environment and try it.  Appreciate you looking at it.

**Comment by jmah322** [comment]
David,  

I am using AppCenter to build and deploy to my device.  So, I assume AppCenter is pulling my GitHub code and building and deploying from scratch every time.  Let me know see if there is something funny going on in that environment.  
  

Sent from Mail for Windows 10

**Comment by davidbritch** [comment]
Hi @jmah322 

Afraid I've got no insights into AppCenter. That's a different team.

**Comment by jmah322** [comment]
Hi David,

I have made the following change in GetViewForAnnotation:

#if false
            if (annotation is MKUserLocation)
                return null;
#endif
            var anno = annotation as MKPointAnnotation;
            if (anno == null)
                return null;

and is working for me now.  Thank you for your help.  Have a great day!

Sent from Mail for Windows 10
