### ISSUE TITLE
Broken master detail on iPad

### ISSUE THREAD

**Issue by ColeXm** [xamarin/xamarin-forms-samples#359]
[GIF here](https://us.v-cdn.net/5019960/uploads/editor/7y/9kn9ti7xizpc.gif)

When I am changing the orientation of a device, the master page is behaving very strange. 

You can see that the white space on the left is appearing.

Is it the known issue ?

**Comment by Mikilll94** [comment]
Here I am posting the gif which shows what author of this topic exactly means.

![master_detail_ipad_broken](https://user-images.githubusercontent.com/17653648/44402343-c1f82800-a551-11e8-8f6f-cee367ac5879.gif)

It does not looks well. Maybe someone knows the reason of this strange behavior?

**Comment by davidbritch** [comment]
Hi @ColeXm 

I was able to reproduce your issue. I was also able to fix it by setting `MasterBehavior = MasterBehavior.Popover;` in the `MainPage.xaml.cs` constructor. On a tablet simulator it made the sample behave as expected.

Take a look at https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page#controlling-the-detail-page-display-behavior for more details.

**Comment by eltonmrk** [comment]
Fixed on XF@latest
