### ISSUE TITLE
PinchGestureRecognizer example doesn't work on UWP device

### ISSUE THREAD

**Issue by helzgate** [xamarin/xamarin-forms-samples#363]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithGestures/PinchGesture

### Description

PinchGestureRecognizer example doesn't work on a Surface Go.  All it does when you try to pinch is move the image slightly to the upper left, but no amount of zooming occurs.  I verified pinch functionality does exist on the Surface Go device by loading up a normal picture in the Windows picture viewer and zooming on it using pinch.

### Steps to Reproduce

Launch the demo app on a  Surface Go device (maybe other UWP devices, I don't know as this is the only one I have).

### Expected Behavior
Image should zoom when pinched

### Actual Behavior
Image doesn't zoom when pinched, it only slightly moves to the upper left.

### Information

- IDE and IDE version: Visual Studio Enterprise 2017 v15.8.2 
- Platform with the issue: UWP (works fine in android, haven't tested iOS)
  - iOS:  n/a
  - Android: n/a
  - UWP:  16299
- Device : Surface Go running Microsoft Windows 10 Pro, version 10.0.17134 Build 17134

**Comment by conceptdev** [comment]
Hi @helzgate, thanks for your feedback. I was able to reproduce this (incorrect) behavior on another Windows laptop with a touchscreen, so it is not specific to the Surface Go.

It isn't clear whether this is a problem with the sample or the SDK. We will have to work with the engineers to investigate.

**Comment by davidbritch** [comment]
Hi @helzgate 

I just tried this sample with Xamarin.Forms 3.3 and it zoomed just fine for me with a pinch gesture. Do you still have this problem?

**Comment by profexorgeek** [comment]
Closing due to lack of response.

**Comment by Druffl3** [comment]
It doesn't work on a desktop as well? I believe one has to hold 'ctrl' and use the scroll button to zoom, as suggested here:
https://docs.microsoft.com/en-us/windows/uwp/design/input/guidelines-for-optical-zoom
