### ISSUE TITLE
Deeplinking project has issues for Android

### ISSUE THREAD

**Issue by pmahend1** [xamarin/xamarin-forms-samples#368]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/DeepLinking

### Description

There are few issues with this sample.

1. Requires Firebase integration: Goes into exception asking to initialize the Firebase app.
- Need to create proeject in firebase -> link your app -> download google services JSON and place in project with build action Google services Json - but this still doesnt work (Go to step 3)

2. AppLink intent filter values are incorrect , hence dont work.
~~DataHost = "DeepLinking",~~
~~DataPathPrefix = "/deeplinking/",~~

**Correct values :**
```
    [IntentFilter(new[] { Intent.ActionView },
        Categories = new[] {
            Intent.ActionView,
            Intent.CategoryDefault,
            Intent.CategoryBrowsable
        },
        DataScheme = "http",
        DataHost = "deeplinking", //base URL
        DataPathPrefix = "/",  //
        AutoVerify = true //false if you want android to ask permission before opening
        )
    ]
```

3. App throws exception with respect to Firebase

- So add below code in MainActivity.cs 

```

//values are to be referred from downloaded google-services.json file
var options = new FirebaseOptions.Builder()
                      .SetApplicationId("<client.client_info.mobilesdk_app_id>")
                      .SetApiKey("<api_key.current_key>")
                      .SetDatabaseUrl("<project_info.firebase_url>")
                      .SetGcmSenderId("<oauth_client.client_id>")
                      .SetStorageBucket("<project_info.storage_bucket>")
                      .Build();

var apps = FirebaseApp.GetApps(this);
            if(apps.Count == 0)
            {
                FirebaseApp.InitializeApp(this,options);
            }
```
4. SQLite database creation error
~~database.CreateTable<TodoItem>();~~

 `database.CreateTable<TodoItem>(CreateFlags.None); `

### Steps to Reproduce

1. Compile
2. Run project with emulator or device with API >=23

### Information

- IDE and IDE version: Visual Studio 2017 v15.8.3
- Platform with the issue: 
  - iOS:  NA
  - Android: Android 9.0 (P) - SDK 28
  - UWP:  NA
- Device or simulator/emulator: both

**Comment by conceptdev** [comment]
@pmahend1 thanks for your feedback (and the linked PR). As with all updates we need to test and verify the changes. We appreciate the time that you have taken, and hope to finalize it soon.

**Comment by davidbritch** [comment]
Sample updated.
