### ISSUE TITLE
What is x:FieldModifier="public"?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/xamarin-forms-samples#379]
Thank you for your sample about Xamarin Forms!
I saw x:FieldModifier="public" in MasterPage.XAML of MasterDetailPage sample.
Sorry for noob question. What is x:FieldModifier="public"?
Thank you!

**Comment by davidbritch** [comment]
Answered at https://github.com/MicrosoftDocs/xamarin-docs/issues/801
