### ISSUE TITLE
Adding sample to this repo

### ISSUE THREAD

**Issue by dev-aritra** [xamarin/xamarin-forms-samples#386]
I want to add one sample for Xamarin forms communication with IBM Watson Assitant services, to build a ChatBot.
Please let me know how I can do that.

**Comment by conceptdev** [comment]
@dev-aritra Thanks for asking. We do not accept samples showcasing external products - we cannot build or test them, nor do we have the ability to maintain them. Perhaps IBM has a samples repo for Watson-related technologies that would accept it?

**Comment by dev-aritra** [comment]
@conceptdev I have created another project where I showcase how to do Speech to text on android and iOS using platform apis and Messaging center, will that work?
