### ISSUE TITLE
The given key 'Xamarin.Forms.Xaml.ElementNode' was not present in the dictionary.   

### ISSUE THREAD

**Issue by sadhac** [xamarin/xamarin-forms-samples#388]
Hi

I have added Master Detail Navigation to my XF app. I am only getting this one error pointing to my MainPage.xaml file.
Please let me know what the issue could be:
`<?xml version="1.0" encoding="utf-8"?>
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:local="clr-namespace:App;assembly=App" 
             x:Class="App.MainPage">
<MasterDetailPage.Master>
 <local:MasterPage x:Name="masterPage" />
</MasterDetailPage.Master>
    <MasterDetailPage.Detail>
        <NavigationPage>
            <x:Arguments>
                <local:Views.ApplicationTags />
            </x:Arguments>
        </NavigationPage>
    </MasterDetailPage.Detail>
</MasterDetailPage>`

**Comment by conceptdev** [comment]
The MasterDetailPage documentation is here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page which includes link to a working sample.

These issues are for reporting problems with the sample code. For general programming questions try https://stackoverflow.com/tags/xamarin
