### ISSUE TITLE
Unevenrows listview not working properly with custom cells

### ISSUE THREAD

**Issue by englebertnicolas** [xamarin/xamarin-forms-samples#390]
### Sample
xamarin-forms-samples/CustomRenderers/ViewCell/

@davidbritch 
@conceptdev 

### Description

I tried to update the sample "ViewCell Custom Renderer" in order to work with uneven row height (iOS).
Result: I made it work with caching strategy RetainElement but not with RecycleElement (row height stays constant).
Am I missing something?

### Steps to Reproduce

1. I changed NativeiOSCell.cs to only display a wrappable headingLabel:

```
internal class NativeiOSCell : UITableViewCell, INativeElementView
{
    bool constraintsUpdated;

    public UILabel HeadingLabel { get; set; }

    public NativeCell NativeCell { get; private set; }
    public Element Element => NativeCell;

    public NativeiOSCell(string cellId, NativeCell cell) : base(UITableViewCellStyle.Default, cellId)
    {
        NativeCell = cell;

        SelectionStyle = UITableViewCellSelectionStyle.Gray;
        ContentView.BackgroundColor = UIColor.FromRGB(255, 255, 224);

        HeadingLabel = new UILabel()
        {
            Font = UIFont.FromName("Cochin-BoldItalic", 22f),
            TextColor = UIColor.FromRGB(127, 51, 0),
            BackgroundColor = UIColor.Clear,
            Lines = 0,
            LineBreakMode = UILineBreakMode.WordWrap
        };

        ContentView.Add(HeadingLabel);
    }

    public override void UpdateConstraints() 
    {
        base.UpdateConstraints();
        if (!constraintsUpdated) {
            HeadingLabel.TranslatesAutoresizingMaskIntoConstraints = false;
            HeadingLabel.SetContentCompressionResistancePriority(1000, UILayoutConstraintAxis.Vertical);
            HeadingLabel.LeftAnchor.ConstraintEqualTo(ContentView.LeftAnchor, 15).Active = true;
            HeadingLabel.RightAnchor.ConstraintEqualTo(ContentView.RightAnchor, -15).Active = true;
            HeadingLabel.TopAnchor.ConstraintEqualTo(ContentView.TopAnchor, 10).Active = true;
            HeadingLabel.BottomAnchor.ConstraintEqualTo(ContentView.BottomAnchor, -10).Active = true;
            constraintsUpdated = true;
        }
    }

    public void UpdateCell(NativeCell cell)
    {
        HeadingLabel.Text = cell.Name;
    }
}
```

2. I changed NativeiOSCellRenderer.cs to update constraints:

```
public override UITableViewCell GetCell(Cell item, UITableViewCell reusableCell, UITableView tv)
{
    var nativeCell = (NativeCell)item;
    cell = reusableCell as NativeiOSCell;

    if (cell == null)
    {
        cell = new NativeiOSCell(item.GetType().FullName, nativeCell);
    }
    else
    {
        cell.NativeCell.PropertyChanged -= OnNativeCellPropertyChanged;
    }

    nativeCell.PropertyChanged += OnNativeCellPropertyChanged;

    cell.UpdateCell(nativeCell);

    cell.NeedsUpdateConstraints(); //added line
    cell.UpdateConstraintsIfNeeded(); //added line
    
    return cell;
}
```

3. I changed DataSource.cs to have some long texts:

```
    ...
    l.Add (new DataSource ("Asparagus. Additional text that should wrap and increase cell height size.", "Vegetables", "Vegetables"));
    l.Add (new DataSource ("Avocados. Additional text that should wrap and increase cell height size.", "Vegetables", "Vegetables"));
    l.Add (new DataSource ("Beetroots. Additional text that should wrap and increase cell height size.", "Vegetables", "Vegetables"));
    l.Add (new DataSource ("Capsicum", "Vegetables", "Vegetables"));
    l.Add (new DataSource ("Broccoli", "Vegetables", "Vegetables"));
    ...
```

4. I changed NativeCellPage.xaml to set the ListView property HasUnevenRows:

```
    ...
    <ListView x:Name="listView" CachingStrategy="RecycleElement" ItemSelected="OnItemSelected" HasUnevenRows="true">
    ...
```

### Expected Behavior

The 3 first row of the list view should grow.

### Actual Behavior

The 3 first row does not grow if list view caching strategy is RecycleElement.
(Notice that it works if caching strategy is RetainElement).

![customrenderer](https://user-images.githubusercontent.com/33529977/46795015-5eb49600-cd49-11e8-935a-6938ed849aba.png)

### Information

- IDE and IDE version: Visual Studio 2017 v15.5.2
- Platform with the issue: iOS:  11.6.1.2
- Device or simulator/emulator: iPhone 6 iOS 11.2 simulator 
- Code: [CustomRendererWithUnevenRows.zip](https://github.com/xamarin/xamarin-forms-samples/files/2468285/CustomRendererWithUnevenRows.zip)

**Comment by englebertnicolas** [comment]
I found the following solution to fix the issue:

1. By overriding SizeThatFits in NativeiOSCell class:

```
    public override CGSize SizeThatFits(CGSize size) {
        return ContentView.SystemLayoutSizeFittingSize(UIView.UILayoutFittingCompressedSize);
    }
```

2. And by setting HeadingLabel.PreferredMaxLayoutWidth in NativeiOSCell.UpdateConstraints()

`    HeadingLabel.PreferredMaxLayoutWidth = ContentView.Bounds.Width - 30;
`

Here is now the full code of NativeiOSCell:

```
internal class NativeiOSCell : UITableViewCell, INativeElementView
{
    bool constraintsUpdated;

    public UILabel HeadingLabel { get; set; }

    public NativeCell NativeCell { get; private set; }
    public Element Element => NativeCell;

    public NativeiOSCell(string cellId, NativeCell cell) : base(UITableViewCellStyle.Default, cellId)
    {
        NativeCell = cell;

        SelectionStyle = UITableViewCellSelectionStyle.Gray;
        ContentView.BackgroundColor = UIColor.FromRGB(255, 255, 224);

         HeadingLabel = new UILabel()
         {
             Font = UIFont.FromName("Cochin-BoldItalic", 22f),
             TextColor = UIColor.FromRGB(127, 51, 0),
             BackgroundColor = UIColor.Clear,
             Lines = 0,
             LineBreakMode = UILineBreakMode.WordWrap
         };

         ContentView.Add(HeadingLabel);
    }

    public override void UpdateConstraints() 
    {
        base.UpdateConstraints();
        if (!constraintsUpdated) {
            HeadingLabel.TranslatesAutoresizingMaskIntoConstraints = false;
            HeadingLabel.PreferredMaxLayoutWidth = ContentView.Bounds.Width - 30;
            HeadingLabel.SetContentCompressionResistancePriority(1000, UILayoutConstraintAxis.Vertical);
            HeadingLabel.LeftAnchor.ConstraintEqualTo(ContentView.LeftAnchor, 15).Active = true;
            HeadingLabel.RightAnchor.ConstraintEqualTo(ContentView.RightAnchor, -15).Active = true;
            HeadingLabel.TopAnchor.ConstraintEqualTo(ContentView.TopAnchor, 10).Active = true;
            HeadingLabel.BottomAnchor.ConstraintEqualTo(ContentView.BottomAnchor, -10).Active = true;
            constraintsUpdated = true;
        }
    }

    public void UpdateCell(NativeCell cell)
    {
        HeadingLabel.Text = cell.Name;
    }

    public override CGSize SizeThatFits(CGSize size)
    {
        return ContentView.SystemLayoutSizeFittingSize(UIView.UILayoutFittingCompressedSize);
    }
}
```

SizeThatFits seems to be called only when list view caching strategy is RecycleElement. I guess we have to return the cell height here? 

As I don't find any docs on this subject, could you tell me if this fix is correct and efficient, or if another approach is recommended by Xamarin?

**Comment by conceptdev** [comment]
@englebertnicolas thanks for the detailed explanation and screenshots. You are correct that the documentation does not cover this. It seems like it could be a bug with `RecycleElement`, in which case you should raise it with the development team at the open-source repo https://github.com/xamarin/xamarin.forms 

Your workaround seems good to me, and might help other developers that are hitting the same problem.

**Comment by englebertnicolas** [comment]
Thank for your response.
For those who would read this: to be efficient, we should cache size in the SizeThatFits() overriden method.

**Comment by englebertnicolas** [comment]
@nathan1658 
Probably not the same issue, this thead was not related to dynamic update at runtime.

Are your cells native or forms?
How do you update/refresh your cell?

**Comment by nathan1658** [comment]
Woah I think I've solved it, what a day

At the beginning I use DataTrigger to represent different state of the cell:

`
Cell

     <Grid>
      <ContentView ControlTemplate = "NormalMessage">
                 <DataTrigger Binding={Binding IsMasked}>
                            <Setter Property="ControlTemplate" Value="MaskedMessage">
                 </DataTrigger>
       </ContentView>
      </Grid>
/Cell`
^Something like that

At the code behind of the cell, i did update the Property {IsMasked} and call ForceUpdateSize, and resulting in the above buggy view.

I followed the fourth method of this post, and made a little changes to my code:
[post](https://forums.xamarin.com/discussion/comment/205764/#Comment_205764)

Instead of using ContentView switching ControlTemplate, I paste both View(NormalMessage and MaskedMessage) in a StackLayout and switching their IsVisible property.

Also Instead of calling ForceUpdateSize, I decided to update the ObservableList ItemsSource like this:
`
var newMsg = JsonConvert.DeserializeObject<Message>(JsonConvert.SerializeObject(sourceMsg));
newMsg.IsMasked = false;

GroupedMessages = newMsg;
`
To trigger the update. 

And turn out the result is satisfying! Smooth animation and correct height of the cell! I am not so certain what's going on and am I doing unnecessary stuff, my guess is Switching ContentView ControlTemplate is a bit slower than the height of the cell being calculated, resulting in wrong height of the cell, and also according to the official document
`Developers can call this method to update the cell's size, even if the cell is currently visible. Developers should note that this operation can be expensive.`
Maybe that's why the animation is jitty and why we should avoid it? hmmm

**Comment by samhouts** [comment]
Related to https://github.com/xamarin/Xamarin.Forms/issues/2383

**Comment by saamerm** [comment]
As mentioned [here](https://github.com/xamarin/Xamarin.Forms/issues/2383), the solution is to use CollectionView instead of ListView to get around this issue

**Comment by davidbritch** [comment]
Closing this issue as it looks like solutions have since been found.
