### ISSUE TITLE
ViewModel First Navigation Service with Xamarin.Forms

### ISSUE THREAD

**Issue by tomislaveric** [xamarin/xamarin-forms-samples#396]
### Sample

I've created a sample App with a ViewModel First Navigation. I try to stick to the MVVM Pattern and without this Navigation Service it seems unpossible for me. So maybe someone of the community is interested in my solution. Here is the Pull Request of the sample: https://github.com/xamarin/xamarin-forms-samples/pull/395

**Comment by davidbritch** [comment]
Hi @tomislaveric 

Thanks for the PR. Unfortunately we don't require the sample in this PR as we've already got view model first navigation covered in our (eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) sample, which is documented [here](https://docs.microsoft.com/xamarin/xamarin-forms/enterprise-application-patterns/navigation). Thanks anyway!
