### ISSUE TITLE
Android.Net namespace not found

### ISSUE THREAD

**Issue by donmesserli** [xamarin/xamarin-forms-samples#399]
### Sample

https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/VideoPlayerDemos/VideoPlayerDemos/VideoPlayerDemos.Android/FormsVideoLibrary/VideoPlayerRenderer.cs

### Description

Getting namespace not found error on lines 144 and 167. Saying Android doesn't contain a .Net namespace.

### Steps to Reproduce

1. Build the Android sample app

### Expected Behavior
 Successful build

### Actual Behavior
Error message from above

**Comment by davidbritch** [comment]
Hi @donmesserli 

I've just tried this sample (on Android) in both VS2017 and VSMac and it builds fine. Therefore it's most likely a problem with your install.
