### ISSUE TITLE
MobileCRM menu didn't work well on Windows Phone

### ISSUE THREAD

**Issue by iamhnt** [xamarin/xamarin-forms-samples#40]
When run app on WP8:
 - Go to list page under Leads menu then click on row to go to DetailEditPage.
 - Then click on menu icon, select Contacts (OR Accoutns OR Opportunities), app didn't navigate to new page but the icons.

**Comment by conceptdev** [comment]
This sample has been deprecated and is no longer supported.

Check out https://github.com/xamarin/app-crm
