### ISSUE TITLE
Type SwipeGestureRecognizer not found in xmlns http://xamarin.com/schemas/2014/forms

### ISSUE THREAD

**Issue by alextorres50** [xamarin/xamarin-forms-samples#403]
### Sample

<StackLayout.GestureRecognizers>
                        
                   <SwipeGestureRecognizer Direction="Left" 
                                           Command="{Binding GotoForm}"
                                           CommandParameter="Left"/>
                 
</StackLayout.GestureRecognizers>

### Description
 Type SwipeGestureRecognizer not found in xmlns http://xamarin.com/schemas/2014/forms 

### Steps to Reproduce

1. I don't use this gesture, neither in xaml, nor by code
2. Say the directive doesn´t found

### Information

- IDE and IDE version:  Visual Studio Mac v7.6 
- Platform with the issue: 
  - iOS:  12.0
  - Android: 9.0

**Comment by davidbritch** [comment]
I just tried your code without any problems. Check out the swipe gesture recognizer [sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithGestures/SwipeGesture) for a working example.
