### ISSUE TITLE
UsingUITest seems to be obsolete

### ISSUE THREAD

**Issue by Tviljan** [xamarin/xamarin-forms-samples#405]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UsingUITest

### Description

Running the sample does not work anymore. All I get is failed test "System.Exception : ApkFile or InstalledApp has not been configured"

### Steps to Reproduce

1. Run tests

### Expected Behavior

Test succeeded

### Actual Behavior

Failed test "System.Exception : ApkFile or InstalledApp has not been configured"

### Information

- IDE and IDE version: Visual Studio 2017 v15.8.9 
- Platform with the issue: 
  - Android 9.0 API 28
 - Device: HMD Global Nokia 7 plus

If I change ConfigureApp.Android and add .ApkFile(<Path-to-apk>) it runs

**Comment by matei-tm** [comment]
Avoid adding the ApkFile that requires an explicit path (different for each build configuration).
The InstalledApp method is cleaner because of its unmodified parameter across build configurations:

```csharp
if(platform == Platform.Android)
  {
    return ConfigureApp
                    .Android
                    .InstalledApp("com.xamarin.usinguitest")
                    .StartApp();
  }
```

**Comment by profexorgeek** [comment]
Based on the committed fix, I'm closing this issue. @Tviljan, please let us know if the fix did not resolve your problem.
