### ISSUE TITLE
ImageResourceExtension gives an System.PlatformNotSupportedException in UWP release

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#406]
### Sample

https://github.com/xamarin/xamarin-forms-samples/XAML/MarkupExtensions
### Description
If you compile and run this sample for UWP release, select Image Resource Demo. You will immediately break with a System.PlatformNotSupportedException. This will happen with any sample using this extension. And this includes any of the Xamarin-Forms-Book-Samples using the ImageResourceExtension.cs.

### Steps to Reproduce
If you compile and run this sample for UWP release, select the Image Resource Demo. You will immediately break with a System.PlatformNotSupportedException. 
 The error occurs at the following line:
            return ImageSource.FromResource(assemblyName + "." + Source);
1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Hi @davefxy 

I'll get the sample/doc updated, but can confirm that the exception vanishes if you switch the line of code to:

`return ImageSource.FromResource(assemblyName + "." + Source, typeof(ImageResourceExtension).GetTypeInfo().Assembly);`
