### ISSUE TITLE
EmployeeDirectory ImageDownloader

### ISSUE THREAD

**Issue by neokeats** [xamarin/xamarin-forms-samples#41]
hi, 
is it possible to have the different implementation of  the function LoadImage for the different plateform ?
they seem missing on the portage.

thanx

**Comment by olegoid** [comment]
Hello @neokeats, if this issue is still actual please start discussion on Xamarin Forums: https://forums.xamarin.com/categories/xamarin-forms

PS: it would be nice to give more detailed explanation of your problem  + code snippet.
