### ISSUE TITLE
Problems with the xml file reading

### ISSUE THREAD

**Issue by amra12** [xamarin/xamarin-forms-samples#411]
I have already created my app with xlm files (from the file handling example) here. It is working perfectly the only problem that I am facing is , it does not show anything on the xml page the xml file is not loaded at all. I tried to debug it and everything but no success. Any suggestions. Ps even the project from this GitHub page has the same issue

**Comment by davidbritch** [comment]
Hi @amra12 

Which sample has the problem?

**Comment by amra12** [comment]
@davidbritch  Its is the WorkingwithFiles sample

**Comment by davidbritch** [comment]
Hi @amra12 

I can confirm there's an issue, as you described. I've updated the sample and it's now working again.
