### ISSUE TITLE
Handle a pan gesture recognizer Image on Mac

### ISSUE THREAD

**Issue by nhatvhm** [xamarin/xamarin-forms-samples#417]
### Sample

https://developer.xamarin.com/samples/xamarin-forms/WorkingWithGestures/PanGesture/

### Description

I saw a sample for all platform iOS, Android and UWP. How can I handle a pan gesture recognizer Image on Mac?

### Steps to Reproduce

N/A

### Expected Behavior
I need branch code for MAC

### Actual Behavior
I don't see sample on MAC

### Information

- IDE and IDE version: Visual Studio Mac v7.7.2 
- Platform with the issue: 
  - Mac:  
  
- Device or simulator/emulator: ANY

**Comment by davidbritch** [comment]
Hi @nhatvhm 

Apologies for the much delayed response to your issue.

I'm afraid you'll have to wait for MAUI for full macOS parity.
