### ISSUE TITLE
Camera Preview screen stretched ContentPage/CustomRenderer

### ISSUE THREAD

**Issue by prashant-bhandari** [xamarin/xamarin-forms-samples#418]
### Sample

https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/ContentPage/Droid/CameraPageRenderer.cs

### Description

The screen of the camera preview is stretched. The image that is clicked is skinny and stretched.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
