### ISSUE TITLE
Current FormsGallery still warning about Label.Font after API change

### ISSUE THREAD

**Issue by TonyGravagno** [xamarin/xamarin-forms-samples#42]
The Label.Font attribute was deprecated last month but the samples today still have over 50 instances of .Font being set on a new Label. I took a tacky approach to fixing all of these myself. The intent was to correct the code without paying any attention to properly breaking apart the details. It took about 1/2 hour to slog through all of them. It was fast to do because each change only required a quick sequence of single keys or clicks. It could probably be done with a RegExp but would have taken me longer to get that right. Anyway - it would be better if this were fixed properly in the package. Thanks!

Original
```csharp
Label header = new Label
{
    Text = "WebView",
    Font = Font.SystemFontOfSize(50, FontAttributes.Bold),
    HorizontalOptions = LayoutOptions.Center
};
```
My hack for anyone else who wants to do this quickly:
```csharp
Label header = new Label
{
    Text = "WebView",
    FontAttributes = Font.SystemFontOfSize(50, FontAttributes.Bold).FontAttributes,
    FontSize = Font.SystemFontOfSize(50, FontAttributes.Bold).FontSize,
    HorizontalOptions = LayoutOptions.Center
};
```

**Comment by davidbritch** [comment]
Label.Font was removed from remaining samples yesterday as part of a deprecated API sweep.
