### ISSUE TITLE
What do i need to make it work for youtube videos?

### ISSUE THREAD

**Issue by ant81584** [xamarin/xamarin-forms-samples#421]
how to make this work for youtube videos?
below i tried  on the PlayWebVideoPage.xaml and does not load. what do i need to make it work for youtube videos?
below is the code on PlayWebVideoPage.xaml
<video:VideoPlayer Source="http://www.youtube.com/embed/EngW7tLk6R8" />

**Comment by saamerm** [comment]
Hey @ant81584 what is the root of the PlayWebVideoPage.xaml file?

From the research I did for an assignment, I found that there's very few ways of making youtube videos work, one is to use what I did [here](https://github.com/saamerm/XF-YouTubeChannel-Streaming) by just putting in a web view, and the other one is to use the Youtube SDKs as shown in [this tutorial](https://www.thewissen.io/embedding-youtube-feed-xamarin-forms/) that you probably need to put in your Credit Card info in exchange for API credentials

**Comment by samhouts** [comment]
Hi @ant81584! This question is better suited for https://forums.xamarin.com/ or http://www.stackoverflow.com. If you are still having trouble, I recommend you ask there. Thanks!
