### ISSUE TITLE
Custom Renderer Map Pin Event

### ISSUE THREAD

**Issue by wml2017** [xamarin/xamarin-forms-samples#422]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin

### Description

In this sample, I try to use pin's original event like this way

        public MapPage()
        {
            InitializeComponent();

            var pin = new CustomPin
            {
                Type = PinType.Place,
                Position = new Position(37.79752, -122.40183),
                Label = "Xamarin San Francisco Office",
                Address = "394 Pacific Ave, San Francisco CA",
                Id = "Xamarin",
                Url = "http://xamarin.com/about/"
            };
            pin.Clicked += Pin_Clicked;
            customMap.CustomPins = new List<CustomPin> { pin };
            customMap.Pins.Add(pin);
            customMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(37.79752, -122.40183), Distance.FromMiles(1.0)));
        }

        private async void Pin_Clicked(object sender, System.EventArgs e)
        {
            await DisplayAlert("Alert", ((CustomPin)sender).Label, "OK");
        }

For Android, I commit the following line in OnElementChanged
                NativeMap.InfoWindowClick -= OnInfoWindowClick;
and
            NativeMap.InfoWindowClick += OnInfoWindowClick;
in OnMapReady

        protected override void OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs<Map> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null)
            {
                //NativeMap.InfoWindowClick -= OnInfoWindowClick;
            }

            if (e.NewElement != null)
            {
                var formsMap = (CustomMap)e.NewElement;
                customPins = formsMap.CustomPins;
                Control.GetMapAsync(this);
            }
        }

        protected override void OnMapReady(GoogleMap map)
        {
            base.OnMapReady(map);

            //NativeMap.InfoWindowClick += OnInfoWindowClick;
            NativeMap.SetInfoWindowAdapter(this);
        }

the pin event can be fired correctly after tap the pin's info window

### Expected Behavior
But on iOS devices, after I commented out nativeMap.CalloutAccessoryControlTapped  in OnElementChanged. The event can't be triggered:

        protected override void OnElementChanged(ElementChangedEventArgs<View> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null)
            {
                var nativeMap = Control as MKMapView;
                nativeMap.GetViewForAnnotation = null;
                //nativeMap.CalloutAccessoryControlTapped -= OnCalloutAccessoryControlTapped;
                nativeMap.DidSelectAnnotationView -= OnDidSelectAnnotationView;
                nativeMap.DidDeselectAnnotationView -= OnDidDeselectAnnotationView;
            }

            if (e.NewElement != null)
            {
                var formsMap = (CustomMap)e.NewElement;
                var nativeMap = Control as MKMapView;
                customPins = formsMap.CustomPins;

                nativeMap.GetViewForAnnotation = GetViewForAnnotation;
                //nativeMap.CalloutAccessoryControlTapped += OnCalloutAccessoryControlTapped;
                nativeMap.DidSelectAnnotationView += OnDidSelectAnnotationView;
                nativeMap.DidDeselectAnnotationView += OnDidDeselectAnnotationView;
            }
        }
Please help me to solve the issue on iPhone

### Actual Behavior
Can't trigger pin event on iPhone

**Comment by profexorgeek** [comment]
Hi @wml2017,
Sorry for the delayed response. Forms 4.3 included several new additions to the Xamarin.Forms map. Pin events are now separated into `MarkerClicked` and `InfoWindowClicked` events. You can create maps, databind pins, and create polygons and polylines without custom renderers. We have also published updated docs that cover these improvements. The pins doc is here:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/pins

You should be able to use this updated functionality to have more reliable events.
