### ISSUE TITLE
Redirect to  Login page

### ISSUE THREAD

**Issue by ndondapati** [xamarin/xamarin-forms-samples#423]
how to redirect to new landing page instead of displaying alert?

               await DisplayAlert("Email address", user.Email, "OK");

**Comment by susairajs** [comment]
@ndondapati you can use this

await Navigation.PushAsync (new Page2Xaml ());
more details visit here [](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical)

**Comment by davidbritch** [comment]
Closing as this issue has been dealt with.
