### ISSUE TITLE
In ToDoAzure - TodoItemManager.DefaultManager throws exception

### ISSUE THREAD

**Issue by WillAutioItrax** [xamarin/xamarin-forms-samples#428]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAzure/TodoAzure

### Description

in ToDoList.xaml.cs the following line:
`manager = TodoItemManager.DefaultManager;
`
throws an exception:
```
Unhandled Exception:

System.TypeInitializationException: The type initializer for 'TodoAzure.TodoItemManager' threw an exception.
```

### Steps to Reproduce

1.Download Xamarin-forms-sample-master
2.build ToDoAzure for Android
3.run for a device: TCL 90240 (Android 7.1 - API25)

### Expected Behavior
That I see something on the device.

### Actual Behavior
See an exception in code in VS 2017

### Information

- IDE and IDE version: VS 2017 15.9.7
- Platform with the issue: 
  - iOS:  12.2.1.15 did not try
  - Android: 8.1  TCL 90240 (Android 7.1 - API25)
  - UWP:  16299  Local machine
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Hi @WillAutioItrax 

You need to update the `ApplicationURL` property in the `Constants` class to the URL of your Azure App.
