### ISSUE TITLE
For Andriod didn't work (open)

### ISSUE THREAD

**Issue by NetworkStudioRu** [xamarin/xamarin-forms-samples#429]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/GetStarted/Notes/Database

### Description

This is not work only in WINDOWS 10 (I try VS Community 2017 and 2019 preview)
Android Emulator !!! HYPER-V !!! is opened and then noting to do. 

Only for Database sample. With File sample all works fine.
If I use Apple with VS - all works fine with Android Emulator.

### Steps to Reproduce

1. Open Sample with VS Community on Windows 10.
2. Buid
3. Run

### Expected Behavior
Run App 

### Actual Behavior
App didn't run.

### Information

- IDE and IDE version: 
Visual Studio 2017 v15.6 - app didn't run.
Visual Studio 2019 v.3 PREVIEW - app didn't run.
Visual Studio Mac v7.4 - all works fine.
- Platform with the issue: 
  - Android: 
V8.1, V6.0...

- Device or simulator/emulator: 
Errors and problems didn't detected.

**Comment by davidbritch** [comment]
Hi @NetworkStudioRu 

I was able to run the sample in an Android emulator on Windows 10.

![01](https://user-images.githubusercontent.com/8092460/55342305-6bb47580-54a0-11e9-9958-4800f092c133.PNG)
