### ISSUE TITLE
ToDoAzureAuth with MS Live Account consent screen goes blank and does not navigate to ToDo functionality.

### ISSUE THREAD

**Issue by aszalacinski** [xamarin/xamarin-forms-samples#434]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAzureAuth

### Description

iOS project, AppDelegate, line 32... await LoginAsync never returns. 

The sample loads, I enter my MS Live account credentials, I consent and then the screen just goes blank. The iOS consent UI doesn't go away. 

It doesn't look like the callback is being called, maybe? Or the sample is missing some new functionality around navigation? Or my auth provider isn't properly set up. (Documentation is spotty)

### Steps to Reproduce

1. Load Sample
2. Log in using MS Account credentials
3. Callback screen doesn't load

### Expected Behavior
Able to interact with the ToDo functionality

### Actual Behavior
Post Consent screen, nothing happens. Just a white screen.

### Information

- IDE and IDE version: Visual Studio 2017 v15.6 paired with a Mac
- Platform with the issue: 
  - iOS:  12.1
- Device or simulator/emulator: iPhone simulator

I got the Azure App Service running to back the ToDo item sample (the Forms sample worked as expected).

I setup my authentication using MS App Registration portal.

I configured the Authentication of the app service as I am supposed to.

I set my redirect url with my custom url scheme: (i also tried https... no go)
hastodo://has-todo.azurewebsites.net/.auth/login/microsoftaccount/callback

I updated the sample as directed in the constants.cs file
- URL
- URL Scheme set to hastodo

I updated line 32 of the appdelegate to use MobileServiceAuthenticationProvider.MicrosoftAccount

I would be grateful for any direction on what I am doing wrong. Or if the sample is wrong.

**Comment by aszalacinski** [comment]
Actually, on App Registration, I didn't have a web client specified; I specified one of those but NOW the iOS browser loads the web client response and not the public (mobile/desktop) callback. So what is wrong?

**Comment by JHHMobile** [comment]
Were you able to figure it out? 
I'm having the issue with the oauth, please share

https://github.com/xamarin/xamarin-forms-samples/issues/435

**Comment by aszalacinski** [comment]
@JHHMobile not yet... have a support ticket open with Azure Tech support right now. It appears its an authentication setup issue with my Azure App Service; I get back the access token but the app service refuses to authorize my requests using it. Once I sort it out I will update here. May need to post a PR to show how to configure for MS account access. Fingers crossed.

**Comment by davidbritch** [comment]
Hi @aszalacinski 

I'm afraid that we've since deleted our Azure Mobile Apps samples and docs. I suggest you take a look at the Azure Mobile Apps documentation, which has good Xamarin.Forms coverage: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users
