### ISSUE TITLE
How to generate References.cs in ToDoWCF

### ISSUE THREAD

**Issue by tunbeo** [xamarin/xamarin-forms-samples#436]
Hi, can you tell me how to generate References.cs in ToDoWCF? Did you use svcutil.exe ? I tried but the output not exactly the same

Many thanks

**Comment by davidbritch** [comment]
Hi @tunbeo 

The web service reference can be generated from Visual Studio (on Windows), provided that the solution you are adding the web service reference to is a PCL. You can't add a WCF web service reference to a .NET Standard Library.
