### ISSUE TITLE
xamarin forms picker control text truncate issue

### ISSUE THREAD

**Issue by vyasaraj999** [xamarin/xamarin-forms-samples#437]
Need to implement LineBreakmode property for the picker control to use the tail truncation as the text ellipsize to indicate the text is not completes yet. 

this issue exists in android only, ios works fine.

tried implementing prooerty in the PickerRenderer but nothing happens.

Also implemented this changes in the link below it didn't work.
link-  https://stackoverflow.com/questions/38476609/tailtruncation-ellipsize-the-text-of-a-picker-control-in-xamarin-forms

**Comment by davidbritch** [comment]
Hi @vyasaraj999 

If you believe there's a problem with the `Picker` control, you should report it in the [engineering repo](https://github.com/xamarin/Xamarin.Forms).
