### ISSUE TITLE
XamFormsImageResize - Directives Causing Build Issues

### ISSUE THREAD

**Issue by Xerosigma** [xamarin/xamarin-forms-samples#44]
I can't seem to get my project to compile when I add the ImageResizer class to my project due to a "Not all code paths return..." error thrown because of the directive-hidden returns in ResizeImage().

Example itself builds fine. Not sure what the difference is here.

Thank you.

**Comment by conceptdev** [comment]
This is so old you have probably solved it. If not, please provide some more info about your project to help us understand what might be going wrong.
