### ISSUE TITLE
Sample Proposal-App Center Push Notifications

### ISSUE THREAD

**Issue by saamerm** [xamarin/xamarin-forms-samples#443]
### Sample Proposal

I would like to propose bringing in a new Xamarin Form Sample that makes it super easy for users to create a new page that displays a list of Push Notifications from the MS App Center. Some of the work done for it is in this repo:
https://github.com/saamerm/Microsoft-App-Center-Push-Notifications-API

### Description

(I wish there was a better template I could fill out instead of the standard one linked in the README of this repo)

It is currently a daunting task for users to figure out how to implement push notifications in their apps, even though the MS App Center makes it very easy. Once implemented, "Notification List" and "Notification Detail" pages are easy for users to add to their app. So it would be nice to provide a sample for users to view and implement.

### Information

- Upon reading the README of the "xamarin-forms-samples" repo, I am trying to follow the steps to request adding my sample into the list of samples that users can view and implement into their own apps.
- The sample will use Xamarin Forms and will work for iOS and Android.

**Comment by nick5454** [comment]
I would prefer Firebase as an example or include both

**Comment by saamerm** [comment]
Hey @nick5454, Apart from providing simple steps to setup Push Notifications, MS AppCenter provides a client to send those notifications so you don't need a server for your Apps. Users could use this for their companies as a quick start to sending & showing push notifications on their apps.

Hey @samhouts, Do i have to get it approved or should I just submit a Pull Request?

**Comment by profexorgeek** [comment]
The App Center doc site (which is a different repo) now has a section focused on Push Notifications here. This section includes a Xamarin.Forms doc:
https://docs.microsoft.com/en-us/appcenter/push/

I am closing this issue as an App Center notifications sample would probably be a better fit for the App Center repository.
