### ISSUE TITLE
ToDoRESTService.sln won't compile because it is missing the package.config file

### ISSUE THREAD

**Issue by Tam66662** [xamarin/xamarin-forms-samples#446]
### Sample

https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoREST/TodoRESTService/ASP.NET%20WebAPI%202/TodoRESTService.sln

### Description

When you open this solution, the single project inside is missing packages.config file, and as a result there are numerous missing references related to System.Net.* and System.Web.*

### Steps to Reproduce

1. Download the solution and folder contents
2. Open in VS2017
3. You'll see it is missing the packages.config file

### Expected Behavior
All the files should be there and compilation is successful

### Actual Behavior
Not all the files are there and compilation fails

### Information

- IDE and IDE version: Visual Studio 2017 v15.6
- Platform with the issue: N/A

**Comment by davidbritch** [comment]
Hi @Tam66662 

I've just pushed out an updated version of this sample, so it should be working for you now.

**Comment by Tam66662** [comment]
@davidbritch I'm not sure I understand how this was resolved.  You pushed a new sample that simply removed this TodoRESTService.sln and its projects.  I was looking at this code to try and understand how to write such a local service.  
By pushing your updated sample, it no longer exists.  Also, the TodoREST md file still points to the old Xamarin download sample that contains the TodoRESTService.sln, which also has the missing packages.config file.  Can you either explain the new sample you pushed (what changed?), or bring back the missing solution and project?

Thanks,
Tam

**Comment by davidbritch** [comment]
Hi @Tam66662 

While I've removed TodoRESTService, I've replaced it with a folder named TodoAPI, that rewrites the service in using ASP.NET Core 2.

Afraid that the zip files haven't regenerated for various reasons.

**Comment by Tam66662** [comment]
Ahh, got it.  Thanks for the pointer, I didn't know it was rewritten there.
