### ISSUE TITLE
XamFormsImageResize -rotated to the left on portrait

### ISSUE THREAD

**Issue by jesusgarza** [xamarin/xamarin-forms-samples#46]
In iOS, if the image is in portrait (height>width) the resized image is rotated to the left, but keeps the correct dimensions .

**Comment by FredyWenger** [comment]
If have the same issue.
Additionally, I have have a crash in WP in the line:
WriteableBitmap bitmap = PictureDecoder.DecodeJpeg (streamIn, (int)width, (int)height);
System.Runtime.InteropServices.COMException 
  _message=The component cannot be found. (Exception from HRESULT: 0x88982F50)
and it seems as the aspect-ratio is not held.

Did you have the same problems?
Did you ever become any feedback?
Do you still use this code?
Thanks for an answer.
Fredy

**Comment by jesusgarza** [comment]
I used this one, I forgot to record its origin, sorry:

		public byte[] ResizeImage (byte[] imageData, float scaleFactor)
		{

			// Load the bitmap
			UIImage originalImage = ImageFromByteArray (imageData);
			float oldWidth = (float)originalImage.Size.Width;
			float oldHeight = (float)originalImage.Size.Height;

			float width = (float) (oldWidth * scaleFactor);
			float height = (float) (oldHeight * scaleFactor);

			UIGraphics.BeginImageContext (new SizeF (width, height));
			originalImage.Draw (new RectangleF (0, 0, width, height));
			var resizedImage = UIGraphics.GetImageFromCurrentImageContext();
			UIGraphics.EndImageContext ();

			var bytesImagen = resizedImage.AsJPEG ().ToArray ();
			resizedImage.Dispose ();
			return bytesImagen;
}

**Comment by FredyWenger** [comment]
Hi Jesus
Thanks for the fast reply :)
But... this code (UIImage) only works on iOS...?

**Comment by jesusgarza** [comment]
Oh yes, its for iOS. So far I haven't had any problems with the android version and haven't tested the WP version.

**Comment by FredyWenger** [comment]
Hi Jesus

Your code works like a charm - thank you very much !!
As I wrote in my posting, I had further problems (crashes depending on the loaded image).
With your code, it seems all problems are gone now :dancers: 
As I need a target-resolution (for all platforms), I have added a dynamic scaling and then just replaced the iOS-Implementation with the new code.

       public static byte[] ResizeImageIOS(byte[] imageData, float width, float height)
        {
            // Load the bitmap
            UIImage originalImage = ImageFromByteArray(imageData);
            //
            var Hoehe = originalImage.Size.Height;
            var Breite = originalImage.Size.Width;
            //
            nfloat ZielHoehe = 0;
            nfloat ZielBreite = 0;
            //

            if (Hoehe > Breite) // Höhe (71 für Avatar) ist Master
            {
                ZielHoehe = height;
                nfloat teiler = Hoehe / height;
                ZielBreite = Breite / teiler;
            }
            else // Breite (61 for Avatar) ist Master
            {
                ZielBreite = width;
                nfloat teiler = Breite / width;
                ZielHoehe = Hoehe / teiler;
            }
            //
            width = (float)ZielBreite;
            height = (float)ZielHoehe;

            UIGraphics.BeginImageContext(new SizeF(width, height));
            originalImage.Draw(new RectangleF(0, 0, width, height));
            var resizedImage = UIGraphics.GetImageFromCurrentImageContext();
            UIGraphics.EndImageContext();

            var bytesImagen = resizedImage.AsJPEG().ToArray();
            resizedImage.Dispose();
            return bytesImagen;
        }

<strong>Once again - thanks a lot! </strong>

**Comment by jesusgarza** [comment]
Glad it worked!!

**Comment by davidbritch** [comment]
Solution currently doesn't load in XS or VS.

**Comment by davidbritch** [comment]
Solution updated to load in both XS/VS.

On iOS, resized image now respects original orientation (currently 2.0.0 branch only).

**Comment by alexrainman** [comment]
@davidbritch i am trying to use the imageresizer but in iOS original orientation is not respected. Can u help?

**Comment by davidbritch** [comment]
@alexrainman The change I made to respect image orientation on iOS seems to have been wiped out in a branch merge. I've re-applied the fix.

**Comment by alexrainman** [comment]
@davidbritch i am having same issue with orientation but in Android

**Comment by Arpit360** [comment]
@alexrainman  could you please provide a sample project  or steps to reproduce. So that we can reproduce this issue at our end.

Also provide Environment Info with xamarin.Forms version.

**Comment by Parmendrak** [comment]
@davidbritch,  I have filed a bug for On changing the device orientation portrait to landscape iOS app doesn't rotate. Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=43666
I am facing this issue with latest master branch.

**Comment by davidbritch** [comment]
@Parmendrak I've closed the bug in bugzilla. I tried the sample in a number of different iOS 10 simulators (including 6s Plus) and the app rotates when the device orientation is changed.
