### ISSUE TITLE
Shell Sample (Xaminals) doesn't work

### ISSUE THREAD

**Issue by henryyue2010** [xamarin/xamarin-forms-samples#462]
### Sample

Try to run the sample at https://github.com/xamarin/xamarin-forms-samples/tree/forms40/UserInterface/Xaminals/

It doesn't work. Got error: 
Java.Lang.ClassNotFoundException: <Timeout exceeded getting exception details>

### Steps to Reproduce

1.
2.
3.

### Expected Behavior
The app should work

### Actual Behavior
The app terminated after starting

### Information

- IDE and IDE version: Visual Studio 2017 v15.6
- Platform with the issue: 
  - iOS:  
  - Android: Android 5.1 API 22
  - UWP:  
- Device or simulator/emulator:

**Comment by sticker592** [comment]
I get a similar but different error:
System.MissingMethodException: Default constructor not found for type Xaminals.Views.CatsPage
(I checked and there is a constructor that takes no arguments)

**Comment by davidbritch** [comment]
This will most likely be an issue with API 22. Investigating further.

**Comment by davidbritch** [comment]
I've just managed to build the sample for API 22. Therefore, I'll close this issue.
