### ISSUE TITLE
Basic Shell, IoC/ DI and basic MVVM Sample

### ISSUE THREAD

**Issue by kieronlanning** [xamarin/xamarin-forms-samples#469]
As a beginner to Xamarin, I was hoping for a best practice sample involving the same patterns I’ve been using in previous WPF applications and more recently ASP.NET Core applications. 

Basic (non-framework) MVVM, IoC/ DI baked into navigation, so a views automatically resolve its ViewModel using constructor injection for complex view mode types.

Does this example exist anywhere?

I’ve not done Xamarin before, and haven’t done any WPF for 5 years, but lots of RESTful API work in ASP.NET Core. So a sample to bridge that gap - testable ViewModels, automatic ViewModel into View injection etc, seemed like a good place to start.

**Comment by davidbritch** [comment]
Hi @kieronlanning 

Yes, such a sample exists, but it's not in this repo. You want the eShop app - https://github.com/dotnet-architecture/eShopOnContainers

There's also a companion guide (which needs updating) at https://docs.microsoft.com/xamarin/xamarin-forms/enterprise-application-patterns/index

**Comment by kieronlanning** [comment]
Thanks @davidbritch, I'll take a look! Cheers.

**Comment by kieronlanning** [comment]
@davidbritch Sorry, I'm a little confused.

The eShopOnContainers isn't a Shell application...

I was after a `Basic Shell, IoC/ DI and basic MVVM Sample`...

**Comment by davidbritch** [comment]
@kieronlanning 

Sorry! I skimmed over the issue title. Afraid we don't have any samples for Shell with IoC and MVVM.

However, we do have a sample for Shell with MVVM, just no IoC. That's not unusual though, as IoC can significantly slow down a Xamarin.Android application, depending upon the choice of container. You can find it at: https://github.com/Microsoft/TailwindTraders-Mobile

**Comment by kieronlanning** [comment]
@davidbritch Thanks! I'll take a look.

You mentioned that it can significantly slow the solutions down - is there a recommended IoC/ DI framework to use?

**Comment by davidbritch** [comment]
@kieronlanning 

Yes, it's a Shell app (https://github.com/microsoft/TailwindTraders-Mobile/tree/master/Source/TailwindTraders.Mobile/TailwindTraders.Mobile/Features/Shell).

As for DI frameworks, take a look at https://xamarinhelp.com/ioc-container-performance/ for a comparison. Basically, dynamic code is bad on Android, so you want to reduce the use of reflection to a minimum.

TinyIoC seems to be as good as it gets. I knocked 2s off the startup time of an Android app by moving from Autofac to TinyIoC.

**Comment by kieronlanning** [comment]
@davidbritch Thanks for the advice! Sorry, missed the shell bit - was looking in the root.

**Comment by Bohirjon** [comment]
Hi @kieronlanning did you find out any solution for this?

**Comment by kieronlanning** [comment]
@Bohirjon Sorry, no. I did move to React Native though, and found it's so much easier. Especially with `expo`.
