### ISSUE TITLE
WorkingWithStyles App.xaml.cs code clobbers styles generated in App.xaml

### ISSUE THREAD

**Issue by MobileDan** [xamarin/xamarin-forms-samples#47]
I referenced the WorkingWithStyles sample app as a basis to convert my App.cs class into a XAML-based App.xaml/App.xaml.cs class. The following code tripped me up by clearing out any styles created in the App class's XAML.

The style created in the App XAML was not a focal point of this sample app and I can see it was easy to overlook that it was not created.

xamarin-forms-samples\WorkingWithStyles\WorkingWithStyles\App.xaml.cs

    public App()
    {
        InitializeComponent();

        // if Current.Resources was created in App.xaml (when InitializeComponent is called) it will be replaced here
        Current.Resources = new ResourceDictionary(); 

I changed it to this to fix the problem

    public App()
    {
        InitializeComponent();

        // Create Current.Resources if not created in XAML
        if (Current.Resources == null)
        {
            Current.Resources = new ResourceDictionary();
        }

I started a forum post here thinking it might be a problem in Xamarin Forms itself http://forums.xamarin.com/discussion/33700/styles-defined-in-app-xaml-resource-dictionary-are-not-created-at-runtime#latest

This cost me some time and frustration but I learned something and won't forget it (for a while anyway). Hopefully correcting the code above will prevent this from happening to someone else.

**Comment by conceptdev** [comment]
I've taken your suggestion on-board and made this change (currently in branch 1.4.3). Thanks for the feedback.
