### ISSUE TITLE
Xaminals example flickering 

### ISSUE THREAD

**Issue by angelru** [xamarin/xamarin-forms-samples#470]
### Sample
[https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals)

### Description

When I selected one element in the collectionview in the tabs (domestic, monkeys...) when navigate to element there is a flickering very annoying.

### Steps to Reproduce

1. Select one tab
2. Domestic, Monkeys...
3. Navigate to element

### Information

- IDE and IDE version: Visual Studio 2019 last version
 - Android: 9

**Comment by davidbritch** [comment]
Hi @angelru 

Thanks for reporting this issue. It's being tracked in the Xamarin.Forms engineering repo (https://github.com/xamarin/Xamarin.Forms/issues/6294), so I'll close it here.
