### ISSUE TITLE
Native2Forms iOS Memory Leak

### ISSUE THREAD

**Issue by kbosselman** [xamarin/xamarin-forms-samples#471]
### Sample

https://developer.xamarin.com/samples/xamarin-forms/Native2Forms/

### Description

On iOS the CallHistoryPage and underlying UIViewController appear be leaking when using Page.CreateViewController.

### Steps to Reproduce

I tried downloading and playing with github.com/xamarin/xamarin-forms-samples/tree/master/Native2Forms (sha 263d168) and the sample project appears to be leaking Page objects.

I added a GC button to the PhonewordPage and a finalizer to CallHistoryPage. 

I would expect that after repeatedly pushing and popping CallHistoryPages and then clicking the GC button I would see the finalizer getting called as after the Page's UIViewController is popped from the UINavigationController it should no longer be referenced. However, the finalizer is never called.

When profiling using the Xcode Instruments I can see UIViewControllers getting allocated and never being released when pushing and popping the CallHistoryPage.
 
If I do the same thing on the Droid application everything works as expected. I push and pop the CallHistoryPage several times and then click the GC button and I see that the finalizers for the popped pages are called.

### Expected Behavior

Popped CallHistoryPage instances and their underlying UIViewContollers are GC'ed on iOS

### Actual Behavior

Popped CallHistoryPage instances and their underlying UIViewContollers are leaked on iOS

### Information

- IDE and IDE version: Visual Studio Mac v8.0.5 
- Platform with the issue: 
- iOS:  12.2
- Device or simulator/emulator: iPhone 6

**Comment by davidbritch** [comment]
Hi @kbosselman 

The popping of a `UIViewController` from the iOS Native Navigation stack does not automatically dispose of `UIViewController`s. It is the responsibility of the developer to ensure that any `UIViewController` that is no longer needed has its `Dispose` method called, else the `UIViewController` and attached `Page` will be orphaned and will not be collected by the garbage collector, resulting in a memory leak.

Admittedly, the sample doesn't do this, and so it requires an update.

**Comment by davidbritch** [comment]
Fixed by https://github.com/xamarin/xamarin-forms-samples/commit/61043c162998e6b3e4bcc296942a5a2e6b31d522
