### ISSUE TITLE
Unable to resolve 'Autofac (>= 4.8.1)' for '.NETStandard,Version=v2.0'.

### ISSUE THREAD

**Issue by AlvaroTorrez** [xamarin/xamarin-forms-samples#473]
### Sample
https://github.com/xamarin/xamarin-forms-samples/tree/master/Advanced/DependencyResolution/DIContainerDemo

### Description

It is not possible to build the example. I was reviewing that into a visual studio 2019 for macOS Mojave 10.14.4

Getting restore information for project /Users/a/D/DIContainerDemo/DIContainerDemo.iOS/DIContainerDemo.iOS.csproj
Getting restore information for project /Users/a/D/DIContainerDemo/DIContainerDemo.Android/DIContainerDemo.Android.csproj
Running non-parallel restore.
Reading project file /Users/a/D/DIContainerDemo/DIContainerDemo/DIContainerDemo.csproj.
Restoring packages for /Users/a/D/DIContainerDemo/DIContainerDemo/DIContainerDemo.csproj...
Restoring packages for .NETStandard,Version=v2.0...
Resolving conflicts for .NETStandard,Version=v2.0...
DIContainerDemo depends on Xamarin.Forms (>= 4.0.0.425677) but Xamarin.Forms 4.0.0.425677 was not found. An approximate best match of Xamarin.Forms 4.0.0.482894 was resolved.
Unable to resolve 'Autofac (>= 4.8.1)' for '.NETStandard,Version=v2.0'.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: /Users/a/D/DIContainerDemo/DIContainerDemo/obj/project.assets.json
Writing cache file to disk. Path: /Users/a/D/DIContainerDemo/DIContainerDemo/obj/DIContainerDemo.csproj.nuget.cache
Restore failed in 15.57 ms for /Users/a/D/DIContainerDemo/DIContainerDemo/DIContainerDemo.csproj.

NuGet Config files used:
    /U/a/.config/NuGet/NuGet.Config

Restore failed for 'Autofac (>= 4.8.1)'.
Unable to resolve 'Autofac (>= 4.8.1)' for '.NETStandard,Version=v2.0'.
Restore failed.

### Steps to Reproduce

1. Just download the project example
2. Open in visual studio
3. At the moment to restore the packages NuGet the error happened

### Expected Behavior
A sussesfull build

### Actual Behavior
Error:
Restore failed for 'Autofac (>= 4.8.1)'.
Unable to resolve 'Autofac (>= 4.8.1)' for '.NETStandard,Version=v2.0'.
Restore failed.

### Information

- IDE and IDE version: Visual Studio Mac Version 8.0.5 (build 9) -->
- Platform with the issue:

**Comment by davidbritch** [comment]
Interesting, I've just loaded it into VS for Mac 8.0.9 (build 5) without any problems.

---

Getting restore information for project /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/DIContainerDemo.iOS.csproj
Getting restore information for project /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/DIContainerDemo.Android.csproj
Running non-parallel restore.
Reading project file /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/DIContainerDemo.Android.csproj.
Restoring packages for /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/DIContainerDemo.Android.csproj...
Restoring packages for MonoAndroid,Version=v9.0...
Resolving conflicts for MonoAndroid,Version=v9.0...
Checking compatibility of packages on MonoAndroid,Version=v9.0.
Checking compatibility for DIContainerDemo.Android 1.0.0 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Forms 4.0.0.425677 with MonoAndroid,Version=v9.0.
Checking compatibility for DIContainerDemo 1.0.0 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.v4 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Design 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.v7.AppCompat 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.v7.CardView 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.v7.MediaRouter 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.CustomTabs 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Autofac 4.8.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Compat 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Core.UI 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Core.Utils 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Fragment 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Media.Compat 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.v7.RecyclerView 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Annotations 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Transition 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Animated.Vector.Drawable 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Collections 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.CursorAdapter 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Vector.Drawable 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.v7.Palette 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Interpolator 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for System.ComponentModel 4.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.Runtime 1.1.1.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.VersionedParcelable 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.AsyncLayoutInflater 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.CoordinaterLayout 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.CustomView 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.DrawerLayout 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.SlidingPaneLayout 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.SwipeRefreshLayout 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.ViewPager 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.DocumentFile 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Loader 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.LocalBroadcastManager 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Support.Print 28.0.0.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.ViewModel 1.1.1.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Core.Common 1.1.1.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.Common 1.1.1.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.LiveData 1.1.1.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Core.Runtime 1.1.1.1 with MonoAndroid,Version=v9.0.
Checking compatibility for Xamarin.Android.Arch.Lifecycle.LiveData.Core 1.1.1.1 with MonoAndroid,Version=v9.0.
All packages and projects are compatible with MonoAndroid,Version=v9.0.
Committing restore...
Generating MSBuild file /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/obj/DIContainerDemo.Android.csproj.nuget.g.props.
Generating MSBuild file /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/obj/DIContainerDemo.Android.csproj.nuget.g.targets.
Writing lock file to disk. Path: /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/obj/project.assets.json
Writing cache file to disk. Path: /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/obj/DIContainerDemo.Android.csproj.nuget.cache
Restore completed in 2.59 sec for /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.Android/DIContainerDemo.Android.csproj.
Reading project file /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/DIContainerDemo.iOS.csproj.
The restore inputs for 'DIContainerDemo.iOS' have changed. Continuing restore.
Restoring packages for /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/DIContainerDemo.iOS.csproj...
Restoring packages for Xamarin.iOS,Version=v1.0...
Resolving conflicts for Xamarin.iOS,Version=v1.0...
Scanning packages for runtime.json files...
Restoring packages for Xamarin.iOS,Version=v1.0/win...
Resolving conflicts for Xamarin.iOS,Version=v1.0/win...
Restoring packages for Xamarin.iOS,Version=v1.0/win-x64...
Resolving conflicts for Xamarin.iOS,Version=v1.0/win-x64...
Restoring packages for Xamarin.iOS,Version=v1.0/win-x86...
Resolving conflicts for Xamarin.iOS,Version=v1.0/win-x86...
Checking compatibility of packages on Xamarin.iOS,Version=v1.0.
Checking compatibility for DIContainerDemo.iOS 1.0.0 with Xamarin.iOS,Version=v1.0.
Checking compatibility for Xamarin.Forms 4.0.0.425677 with Xamarin.iOS,Version=v1.0.
Checking compatibility for DIContainerDemo 1.0.0 with Xamarin.iOS,Version=v1.0.
Checking compatibility for Autofac 4.8.1 with Xamarin.iOS,Version=v1.0.
Checking compatibility for System.ComponentModel 4.0.1 with Xamarin.iOS,Version=v1.0.
All packages and projects are compatible with Xamarin.iOS,Version=v1.0.
Checking compatibility of packages on Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for DIContainerDemo.iOS 1.0.0 with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for Xamarin.Forms 4.0.0.425677 with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for DIContainerDemo 1.0.0 with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for Autofac 4.8.1 with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for System.ComponentModel 4.0.1 with Xamarin.iOS,Version=v1.0 (win).
All packages and projects are compatible with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility of packages on Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for DIContainerDemo.iOS 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for Xamarin.Forms 4.0.0.425677 with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for DIContainerDemo 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for Autofac 4.8.1 with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for System.ComponentModel 4.0.1 with Xamarin.iOS,Version=v1.0 (win-x64).
All packages and projects are compatible with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility of packages on Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for DIContainerDemo.iOS 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for Xamarin.Forms 4.0.0.425677 with Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for DIContainerDemo 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for Autofac 4.8.1 with Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for System.ComponentModel 4.0.1 with Xamarin.iOS,Version=v1.0 (win-x86).
All packages and projects are compatible with Xamarin.iOS,Version=v1.0 (win-x86).
Committing restore...
Generating MSBuild file /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/obj/DIContainerDemo.iOS.csproj.nuget.g.props.
Writing lock file to disk. Path: /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/obj/project.assets.json
Writing cache file to disk. Path: /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/obj/DIContainerDemo.iOS.csproj.nuget.cache
Restore completed in 231.71 ms for /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo.iOS/DIContainerDemo.iOS.csproj.
Reading project file /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo/DIContainerDemo.csproj.
The restore inputs for 'DIContainerDemo' have not changed. No further actions are required to complete the restore.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo/obj/project.assets.json
No-Op restore. The cache will not be updated. Path: /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo/obj/DIContainerDemo.csproj.nuget.cache
Restore completed in 40.54 ms for /Users/davidbritch/Repos/xamarin-forms-samples/Advanced/DependencyResolution/DIContainerDemo/DIContainerDemo/DIContainerDemo.csproj.

NuGet Config files used:
    /Users/davidbritch/.config/NuGet/NuGet.Config

Feeds used:
    https://www.nuget.org/api/v2/

Packages successfully restored.

**Comment by davidbritch** [comment]
I've also just successfully loaded this into VS for Mac 8.2.3 so I'm going to close this issue.
