### ISSUE TITLE
ThemesDemo raise null error

### ISSUE THREAD

**Issue by xp0379** [xamarin/xamarin-forms-samples#477]
### Description
When running the ThemesDemo project on the android emulator, the "LoadApplication (new App ());" line raise error: 
System.NullReferenceException: Object reference not set to an instance of an object

### Information

- IDE and IDE version:   Visual Studio 2019 v16.1.3
- Platform with the issue: 
  - Android: 9.0
- Device or simulator/emulator: Android emulator

![theme-error](https://user-images.githubusercontent.com/3965048/59328943-4190f680-8d20-11e9-9624-88fda6eeafea.png)

**Comment by davidbritch** [comment]
Hi @xp0379 

I just tried this on Android 9.0, using the latest release of VS2019 and it ran fine for me.
