### ISSUE TITLE
Cannot set text which has character '&' for button

### ISSUE THREAD

**Issue by nakulashok** [xamarin/xamarin-forms-samples#478]
### Description

There is an error when Text property of Entry is set as ' Save & Close'.

### Steps to Reproduce

1. Set Text as 'Save & Close' for Entry

### Expected Behavior

Show show the button name as 'Save & Close'

### Actual Behavior

There is build error

**Comment by anirugu** [comment]
@nakulashok 

Did you try something like this ?

**Comment by nakulashok** [comment]
@anirugu 
Thanks for your help.
Happy to see support from other developers.
Anyway I used **&amp;**
