### ISSUE TITLE
Google maps issue in visual studio 2013

### ISSUE THREAD

**Issue by partialdata** [xamarin/xamarin-forms-samples#48]
Works fine in Xamarin studio,
 but  if you open the exact project up in visual studio 2013 google maps will not  show up just stays a tan color. I have tried this on a live device with the same results. 

![img_2026](https://cloud.githubusercontent.com/assets/6014478/6360732/594b9f10-bc4a-11e4-8cbb-e869d5b25b5c.JPG)
![img_2027](https://cloud.githubusercontent.com/assets/6014478/6360733/59549a8e-bc4a-11e4-974f-9a38282ba337.JPG)

**Comment by conceptdev** [comment]
Follow the instructions to [obtain and install a Google Maps API Key](http://developer.xamarin.com/guides/android/platform_features/maps_and_location/maps/obtaining_a_google_maps_api_key/) in the Android project. 

This is also explained in the [Xamarin.Forms Map doc](http://developer.xamarin.com/guides/cross-platform/xamarin-forms/working-with/maps/).

Note that each computer can have its own keystore, and therefor needs the key to be created and configured for both debugging and production use.
