### ISSUE TITLE
Renderer Exception for UWP : System.ArgumentException

### ISSUE THREAD

**Issue by vijaypalve** [xamarin/xamarin-forms-samples#480]
### Sample

```
public class HybridWebViewRenderer : ViewRenderer<HybridWebView, Windows.UI.Xaml.Controls.WebView>
    {
        const string JavaScriptFunction = "function invokeCSharpAction(data){window.external.notify(data);}";
        public HybridWebViewRenderer()
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<HybridWebView> e)
        {
            base.OnElementChanged(e);
            
            if (e.OldElement != null)
            {
                Control.NavigationCompleted -= OnWebViewNavigationCompleted;
                Control.ScriptNotify -= OnWebViewScriptNotify;
            }
            if (e.NewElement != null)
            {
                if (Control == null && e.OldElement == null)
                {
                    SetNativeControl(new Windows.UI.Xaml.Controls.WebView());
                }

                Control.NavigationCompleted += OnWebViewNavigationCompleted;
                Control.ScriptNotify += OnWebViewScriptNotify;

               Control.NavigateToString(Element.HtmlData);
               
            }
        }
        async void OnWebViewNavigationCompleted(Windows.UI.Xaml.Controls.WebView sender, WebViewNavigationCompletedEventArgs args)
        {
            if (args.IsSuccess)
            {
                // Inject JS script
                await Control.InvokeScriptAsync("eval", new[] { JavaScriptFunction });
            }
        }

        void OnWebViewScriptNotify(object sender, NotifyEventArgs e)
        {
            Element.InvokeAction(e.Value);
        }
    }
```

### Description

I have implemented HybridWebViewRenderer in iOS, Android and UWP.
Android and iOS working fine but in UWP throws exception "System.ArgumentException: Delegate to an instance method cannot have null 'this'"

### Information
Microsoft Visual Studio Professional 2017 
Version 15.9.12
VisualStudio.15.Release/15.9.12+28307.665
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Professional

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- UWP:  The version of the UWP SDK you are compiling against, e.g. 17763
- Occurs on a simulator/emulator: simulator/emulator

<img width="529" alt="HybridWebView1" src="https://user-images.githubusercontent.com/14092016/59897238-60227c00-9409-11e9-8cff-ebe078280ed0.png">

**Comment by profexorgeek** [comment]
Hi @vijaypalve, sorry for the delayed response. It's not clear whether your sample is code you've written or from one of our samples. If it is from a sample, please indicate which sample!

I don't have enough contextual information to be sure about your problem but the issue seems to be that you are trying to remove a method handler from a delegate that hasn't been initialized. Probably because Control is not the same object or is not in the same state that it was when the handler was added.

**Comment by davidbritch** [comment]
The `HybridWebViewRenderer` has since been re-written to derive from `WebViewRenderer` instead of `ViewRenderer`. As part of that, I checked it worked on UWP and all was good. 

Therefore I'll close this issue.
