### ISSUE TITLE
Cannot able to set shell page as navigation page in android

### ISSUE THREAD

**Issue by sarthak199526** [xamarin/xamarin-forms-samples#483]
### Description

Cannot able to set AppShell as navigation when I tried to do that it become blank

Just replace MainPage = new AppShell();  to . MainPage = new NavigationPage( new AppShell()); in you app.cs the weird thing is this in iOS it works perfectly . I am using the latest version of xamarin forms . I want to use my custom navigation not Gotoasync on some clicks 

### Expected Behavior
App shell should load normally

### Actual Behavior
Nothing loads in android 

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android:

**Comment by rhellestrae** [comment]
any resolution? my Xamarin Forms Shell application has same issue - no problem on iOS;

However, after entering Email Address, Password on Sign In screen with Android - and pressing Sign in button, Main Activity screen does not load; processing does occur; after checking Azure Active Directory in Azure Portal for Users - Sign-ins - a successful sign in is registered;

Thanks in advance for insight, guidance;

**Comment by sarthak199526** [comment]
@rhellestrae  I have opened this issue on xamarin.forms below is the link
https://github.com/xamarin/Xamarin.Forms/issues/6743
You can comment there but we are not getting any reply from Xam Team don't know why

**Comment by davidbritch** [comment]
Hi @sarthak199526 

Wrapping an AppShell in a NavigationPage is unsupported. It's just luck that it works on iOS. In future, the engineers might add code to throw an exception when developers try and do that.
