### ISSUE TITLE
MobileCRM Show Stopper 

### ISSUE THREAD

**Issue by MuhammadRashid** [xamarin/xamarin-forms-samples#49]
I am facing an issue when try to run MobileCRM Sample on Android. Xamarin Studio shows following errors;

1. C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2,2): Error XA5207: Please install package: 'Google Play Services' available in SDK installer. Java library file D:\Development\Samples\Xamarin\Xamarin Forms\xamarin-forms-samples-master\xamarin-forms-samples-master\MobileCRM\packages\Xamarin.GooglePlayServices.22.0.0.2\lib\MonoAndroid41\22.0.0\embedded\classes.jar doesn't exist. (XA5207) (MobileCRM.Android)

2. C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2,2): Error XA5206: Please install package: 'Google Play Services' available in SDK installer. Android resource directory D:\Development\Samples\Xamarin\Xamarin Forms\xamarin-forms-samples-master\xamarin-forms-samples-master\MobileCRM\packages\Xamarin.GooglePlayServices.22.0.0.2\lib\MonoAndroid41\22.0.0\embedded\./ doesn't exist. (XA5206) (MobileCRM.Android)

Any solution will great appreciated.

**Comment by conceptdev** [comment]
In Xamarin Studio, go to **Tools > Open Android SDK Manager** and install **Google Play Services** (it might also be called **Google APIs**) for the API level you are targeting. Also install the related **System Images** for the default emulator (or alternatively test on a physical device with Google Play Services installed; or investigate how to add Google Play Services to the Xamarin Android Player).
