### ISSUE TITLE
Cannot download single sample project

### ISSUE THREAD

**Issue by gceaser** [xamarin/xamarin-forms-samples#493]
### Sample

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout

### Description

On the page at the URL above there is a link that says "Download the sample" but when you click on the link there is no way to download just that sample.

### Steps to Reproduce

1.  Past the URL above in your browser
2.  Click on the link at the top of the page that says "Download the sample"
3.  On the next page there is no place to download JUST the Xanimals sample.

### Expected Behavior
On the GitHub page for the Xanimals sample, I except to be able to download JUST that sample.  

### Actual Behavior
After clicking the link, I have to navigate up two levels to the Xamarin-forms-samples page to have the 'Clone or Download' button available.  Downloading from here downloads hundreds of extra project I do not need or want.

### Information

Browser: Edge
OS: Windows 10

**Comment by conceptdev** [comment]
We are working on a new download experience, and while that work is in progress, some samples do not have their own ZIP file. You can find _most_ of our samples with working download links [here](https://developer.xamarin.com/samples); but unfortunately Shell samples are not available by themselves.

When the new portal is available this link will be updated. Sorry for the inconvenience.
