### ISSUE TITLE
Collection View Mutilple Select Item Event Cannot Raise!

### ISSUE THREAD

**Issue by logeshpalani98** [xamarin/xamarin-forms-samples#495]
### Sample

Multiple Select Event Cannot Raise!
### Description

 When i click Item it goes Exception (Java.Lang.NoMathod) but i created method does.

### Steps to Reproduce

1.
2.
3.

### Expected Behavior
Multiple Select Does not Work

### Actual Behavior

Need Multiple Select
### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 

- Device or simulator/emulator: 5.1 API x86

Code 
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RestarantAppDemo.Models;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace RestarantAppDemo.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class CourasalPage1 : ContentPage
    {
        public CourasalPage1()
        {
            InitializeComponent();
        }
        protected override void OnAppearing()
        {
            base.OnAppearing();

            List<CollectionModel> listItems = new List<CollectionModel>();
            CollectionModel listItem = new CollectionModel() {  ImageSource = "MoonriseHome.png", TickSource = "itemcheckedicon.png" };
            CollectionModel listItem1 = new CollectionModel() { ImageSource = "Drawhotelpng.png", TickSource = "itemcheckedicon.png" };
            CollectionModel listItem2 = new CollectionModel() { ImageSource = "MoonriseHome.png", TickSource = "itemcheckedicon.png" };
            CollectionModel listItem3 = new CollectionModel() { ImageSource = "Drawhotelpng.png", TickSource = "itemcheckedicon.png" };
            listItems.Add(listItem);
            listItems.Add(listItem1);
            listItems.Add(listItem2);
            listItems.Add(listItem3);
            listItems.Add(new CollectionModel() { ImageSource = "MoonriseHome.png", TickSource = "itemcheckedicon.png" });
            listItems.Add(new CollectionModel() { ImageSource = "Drawhotelpng.png", TickSource = "itemcheckedicon.png" });
            listItems.Add(new CollectionModel() { ImageSource = "MoonriseHome.png", TickSource = "itemcheckedicon.png" });
            listItems.Add(new CollectionModel() { ImageSource = "Drawhotelpng.png", TickSource = "itemcheckedicon.png"});
            listItems.Add(new CollectionModel() { ImageSource = "MoonriseHome.png", TickSource = "itemcheckedicon.png" });
            listItems.Add(new CollectionModel() { ImageSource = "Drawhotelpng.png", TickSource = "itemcheckedicon.png"});
            collectionList.ItemsSource = listItems;
        }

        private void CollectionList_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var list = sender as CollectionModel;
            var currentSelection = e.CurrentSelection;
            var position = (e.CurrentSelection.FirstOrDefault() as CollectionModel)?.TickSource;
        }
    }
}`

**Comment by davidbritch** [comment]
Hi @logeshpalani98 

Try the [sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/CollectionViewDemos/). Multiple selection works fine there.
