### ISSUE TITLE
Native2Forms Sample calls Dispose of page in OnDisappearing()

### ISSUE THREAD

**Issue by v-haroha** [xamarin/xamarin-forms-samples#499]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/Native2Forms

### Description

The NoteEntryPage's OnDisappearing method calls Dispose of the created NoteEntrypage that is being stored on the AppDelegate class. This works for this here as you can only go back from the NoteEntryPage but would fail if the app allowed the user to Navigate from the NoteEntryPage to another page. As a demonstration to people I believe that we could show a more robust example of how to dispose of pages.
I think a more robust example would be to show the use of an overridden Navigation Controller that would dispose of a page on the PopViewController class and then explain in Comments that it is up to the Developer to decide when and if a page is disposed of. This would show them a viable method of doing this while also expressing that they can retain ViewControllers if they wish.

### Expected Behavior
OnDisappering should not dispose of pages as they could still be expected to be on the nav stack.

### Actual Behavior
Disposing of the page should be decided by the Developer, but controlled though Navigation stack Pop methods

I have also created a local branch that is ready to be pushed if required.

**Comment by davidbritch** [comment]
Hi @v-haroha 

Good suggestion and one I'm happy to take care of. However, if you've already done the work you can make a PR from your local branch I'll take a look at it.

**Comment by v-haroha** [comment]
Ya I can do that. I just found out how ( need to fork branch) so I can dig up that code and submit a PR.


Sincerely,



Harold (Joe) Harvey

Support Engineer v-haroha@microsoft.com<mailto:v-haroha@microsoft.com>
Developer - Demand On Prem
1 (980) 776-2817

M-F 8:00a – 4:00p EST


[Microsoft]
If you have any feedback about my work, please let either me or my manager Nam Su Kang know at nkang@microsoft.com<mailto:nkang@microsoft.com>

________________________________

**Comment by davidbritch** [comment]
Closing as this change is now in the repo.
