### ISSUE TITLE
Employee Directory IOS

### ISSUE THREAD

**Issue by ckoncur** [xamarin/xamarin-forms-samples#50]
Lated build throws this error

var b = base.FinishedLaunching (app,options);
=>
Method not found: 'UIKit.UINavigationBar.SetTitleTextAttributes'.

**Comment by kladis** [comment]
Method 'UINavigationBar.SetTitleTextAttributes' not found :(

**Comment by Parmendrak** [comment]
I have checked this issue with latest sample and latest sample and observed that Its working fine.

Thanks.
