### ISSUE TITLE
Full screen on video player ? 

### ISSUE THREAD

**Issue by Kelve17** [xamarin/xamarin-forms-samples#502]
Is it possible to make the video reproduce in full screen ?

**Comment by profexorgeek** [comment]
Hi @Kelve17, sorry for the slow reply. This issue doesn't specify which sample project you are referring to. Can you please specify which project you are referencing?

**Comment by Tmaturano** [comment]
@profexorgeek I believe he's talking for the Android component that does not display it.
For iOS, it has an option

**Comment by nikhilsingh58** [comment]
[VideoRenderer.cs.zip](https://github.com/xamarin/xamarin-forms-samples/files/3949075/VideoRenderer.cs.zip)
@Kelve17 I have done some tweaks to make it full screen.It works fine.Please have a look

**Comment by Tmaturano** [comment]
> [VideoRenderer.cs.zip](https://github.com/xamarin/xamarin-forms-samples/files/3949075/VideoRenderer.cs.zip)
> @Kelve17 I have done some tweaks to make it full screen. It works fine. Please have a look. Attaching my android video renderer.

Do you have the portrait_mode and landscape_mode png files?

**Comment by nikhilsingh58** [comment]
yes I do have.Please find the attachment
![landscape_mode](https://user-images.githubusercontent.com/6691757/72161181-a3fcc300-33e5-11ea-9796-c12b7b79123c.png)
![portrait_mode](https://user-images.githubusercontent.com/6691757/72161183-a3fcc300-33e5-11ea-96cf-584ee54a38f9.png)

**Comment by Tmaturano** [comment]
@nikhilsingh58 thanks for the assets, where should I call the  VideoPlayerRenderer.Init method?
I tried on the MainActivity, but when I tap over the "FullScreen" image, I get redirected in landscape mode to the MainPage

**Comment by davidbritch** [comment]
The video player sample was always intended as a demonstration of how to play video, rather than a fully fledged video control that incorporates all the required functionality.

However, the next pre-release of Xamarin.Forms should be gaining a `MediaElement` control that can play video. This will be the recommended way to play videos in future.
