### ISSUE TITLE
Xanimals Sample missing UWP project

### ISSUE THREAD

**Issue by robv8r** [xamarin/xamarin-forms-samples#505]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals/

### Description

No UWP example provided for Xanimals using Xamarin.Forms

### Steps to Reproduce

1.  Open the above link.
2.  Verify that UWP is missing.

### Expected Behavior

A UWP Example should be provided

### Actual Behavior

No UWP Example is provided

### Information

- IDE and IDE version: GitHub
- Platform with the issue: UWP
  - UWP:  18362 (1903)

**Comment by davidbritch** [comment]
Hi @robv8r 

If you look at the Shell docs (https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/introduction) you'll see that Shell is only available for iOS and Android. Hence it's not possible to provide a UWP project for this sample.

**Comment by robv8r** [comment]
Can you help understand why the Shell isn't available for UWP?  (IMHO) Xamarin+UWP is pretty painful.  I was really looking forward to the Shell.  It would significantly simplify the UWP development process.
