### ISSUE TITLE
Malformed XML?

### ISSUE THREAD

**Issue by spottedmahn** [xamarin/xamarin-forms-samples#512]
### Sample
In this file: https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/AzureADB2CAuth/Droid/Properties/AndroidManifest.xml there appears to be extra quotes. 

### Description

![image](https://user-images.githubusercontent.com/14079228/63205933-eeb62100-c079-11e9-9946-dc47802cbc31.png)

### Expected Behavior
No extra quotes

---

Is that correct?  I can submit a PR to clean it up 😊

It's also in the doc page: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#android

**Comment by profexorgeek** [comment]
Nice catch, thank you!

I fixed this here:
https://github.com/xamarin/xamarin-forms-samples/pull/514

**Comment by spottedmahn** [comment]
cool 😎, thanks for fixing!
