### ISSUE TITLE
UsingResxLocalization.UWP Exception

### ISSUE THREAD

**Issue by mmazzieri** [xamarin/xamarin-forms-samples#516]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UsingResxLocalization

### Description

`Object reference not set to an instance of an object. 
  in UsingResxLocalization.TranslateExtension.ProvideValue(IServiceProvider serviceProvider) in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UsingResxLocalization\PagesXaml\TranslateExtension.cs: riga 38
   in UsingResxLocalization.FirstPageXaml.InitializeComponent() in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UsingResxLocalization\obj\Debug\netstandard2.0\PagesXaml\FirstPageXaml.xaml.g.cs: riga 22
   in UsingResxLocalization.FirstPageXaml..ctor() in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UsingResxLocalization\PagesXaml\FirstPageXaml.xaml.cs: riga 11
   in UsingResxLocalization.App..ctor() in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UsingResxLocalization\App.cs: riga 29
   in UsingResxLocalization.UWP.MainPage..ctor() in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UWP\MainPage.xaml.cs: riga 12
   in UsingResxLocalization.UWP.UsingResxLocalization_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage() in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UWP\obj\x86\Debug\XamlTypeInfo.g.cs: riga 255
   in UsingResxLocalization.UWP.UsingResxLocalization_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\Users\MauroMazzieri\source\repos\xamarin-forms-samples\UsingResxLocalization\UWP\obj\x86\Debug\XamlTypeInfo.g.cs: riga 476`

### Steps to Reproduce

1. Open UsingResxLocalization/UsingResxLocalization.sln
2. Set UsingResxLocalization.UWP as startup project
3. Start debug 

### Expected Behavior

Run the sample

### Actual Behavior

Exception

### Information

- IDE and IDE version:  Visual Studio Professional 2019 v.16.2.3
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:   16299
- Device or simulator/emulator:  local PC

**Comment by profexorgeek** [comment]
Sorry for the slow response. This is happening because the shared project defines an interface called `ILocalize` that must be implemented on each platform. The Android and iOS projects each have an implementation. But the UWP project does not have an implementation so when the `DependencyService` tries to resolve the `ILocalize` dependency on UWP it is returning null, which results in a null reference exception.

I will discuss this with the team and see if it makes sense to create a UWP implementation.

**Comment by profexorgeek** [comment]
We have looked into the docs and sample for Localization and have created a work item to refresh this content. We'll be publishing a new doc and sample.
