### ISSUE TITLE
expandable label in xamarin forms

### ISSUE THREAD

**Issue by shahramomidvar** [xamarin/xamarin-forms-samples#517]
Hello
How can I have an expandable label like the opposite file
https://github.com/apploft/ExpandableLabel
![ExpandableLabel](https://user-images.githubusercontent.com/39812683/63974267-c4288700-cac1-11e9-9800-4b4c1c65cdf9.gif)

**Comment by davidbritch** [comment]
Hi @shahramomidvar 

You'd have to write your own custom renderer to do this, or find an existing third-party control.
