### ISSUE TITLE
ICommand sample fails based on xamarin icommand doc it is linked from.

### ISSUE THREAD

**Issue by wtfink** [xamarin/xamarin-forms-samples#521]
### Sample
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/databindingdemos/

### Description

How come the ICommand sample is not based on mvvm as the DOC seems to imply it should be.  There are models but no viewmodels in this sample..  The doc describes ICommands to be viewmodels based.

**Comment by davidbritch** [comment]
Hi @wtfink 

The doc specifically refers to the Person Entry page in the sample (https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding#basic-commanding)

If you look at the sample, the `PersonEntryPage` class sets it's `BindingContext` to the `PersonCollectionViewModel`, and binds to commands and properties in the view model. 

Similarly, the `SampleSettingsPage` binds to the `SampleSettingsViewModel` class.

There are also other view models in the sample.
