### ISSUE TITLE
Support for drag and drop way to rearange items in Xamarin.forms ListView

### ISSUE THREAD

**Issue by dinobu** [xamarin/xamarin-forms-samples#522]
Is there a Xamarin.Forms support for drag and drop on ListView items to rearrange the items in a list view for all 3 platforms?

**Comment by davidbritch** [comment]
Hi @dinobu 

Afraid not. You'd have to build that support yourself, using custom renderers.

`ListView` is being superseded by `CollectionView`. If you believe this is something that `CollectionView` should support, you should open an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms).

**Comment by dinobu** [comment]
Thanks @davidbritch , I created a ticket there https://github.com/xamarin/Xamarin.Forms/issues/7508
