### ISSUE TITLE
Custom control examples needed

### ISSUE THREAD

**Issue by timskillman** [xamarin/xamarin-forms-samples#525]
Hi, I'm quite new to Xamarin and I've found creating custom controls a little daunting to say the least!

There appear to be very few examples of custom controls; could this repo provide several examples such as Label/Button, List/Button/Switch, menu's and some other common examples?

I'm sure it would save the Xamarin community a lot of hassle and help with understanding how these things work.

Also, are there any plans to make custom controls XAML only? For example;

LabelButton.xaml

```html
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             x:Class="MyApp.Controls.LabelButton">
  <ContentView.Content>
        <Grid Margin="10,0"  BackgroundColor="LightGray" Padding="0">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="Auto" />
            </Grid.ColumnDefinitions>
            <Label x:Name="LB_Label"
                Style="{StaticResource RCText}"
                HorizontalTextAlignment="Start"
                VerticalTextAlignment="Center"
                Grid.Column="0" />
            <Button x:Name="LB_Button"
                TextColor="#1DC1DD"
                BackgroundColor="Transparent"
                Grid.Column="1"
                VerticalOptions="End"
                />
        </Grid>
    </ContentView.Content>
</ContentView>
```

Implemented with ...

```html
<controls:LabelButton
           LB_Label.Text="My Current setting" 
           LB_Button.Text="Change..."
           LB_Button.Pressed="ChangeCurrentSetting_Pressed"/>
```

Kind Regards.

**Comment by davidbritch** [comment]
Hi @timskillman 

We recently added a doc/sample on creating custom controls: https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/layouts/contentview

There are also plenty of other samples that use custom controls, but don't specifically call them out (e.g. https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/xaml-customnamespaceschemas/).

You can write custom controls in XAML or C#, and there are no plans to make them XAML only.
