### ISSUE TITLE
Request: The official example of how to use Microsoft.Extensions.DependencyInjection in Xamarin.Forms apps

### ISSUE THREAD

**Issue by pstricks-fans** [xamarin/xamarin-forms-samples#526]
I have read James Montemagno's article about [Add ASP.NET Core's Dependency Injection into Xamarin Apps with HostBuilder](https://montemagno.com/add-asp-net-cores-dependency-injection-into-xamarin-apps-with-hostbuilder/). He used Microsoft.Extensions.Hosting just for taking advantage of DI without running a host.

Most applications explained in other articles or books use `autofac` so here I need an official example how to use Microsoft.Extensions.DependencyInjection in Xamarin.Forms applications.

**Comment by davidbritch** [comment]
Hi @pstricks-fans 

I've added an item to our backlog to do this.
