### ISSUE TITLE
WorkingWithListviewNative - Page C crashes the app

### ISSUE THREAD

**Issue by Primalpat-** [xamarin/xamarin-forms-samples#53]
When trying to view page C of the WorkingWithListviewNative sample, it will crash the app with an error:

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at Xamarin.Forms.Platform.Android.Platform.GetRenderer (Xamarin.Forms.BindableObject) <IL 0x00006, 0x00058>
[MonoDroid] at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (int,Android.Views.View,Android.Views.ViewGroup) <IL 0x00249, 0x0133b>
[MonoDroid] at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (intptr,intptr,int,intptr,intptr) [0x0001a] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/9e05e39f/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Android.Widget.BaseAdapter.cs:460
[MonoDroid] at (wrapper dynamic-method) object.c43e51ca-4153-431a-ba32-85c16f57e74a (intptr,intptr,int,intptr,intptr) <IL 0x00023, 0x00067>
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid]   at Xamarin.Forms.Platform.Android.Platform.GetRenderer (Xamarin.Forms.BindableObject bindable) [0x00000] in <filename unknown>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00000] in <filename unknown>:0 
[MonoDroid]   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (IntPtr jnienv, IntPtr native__this, Int32 position, IntPtr native_convertView, IntPtr native_parent) [0x0001a] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/9e05e39f/source/monodroid/src/Mono.Android/platforms/android-19/src/generated/Android.Widget.BaseAdapter.cs:460 
[MonoDroid]   at (wrapper dynamic-method) object:c43e51ca-4153-431a-ba32-85c16f57e74a (intptr,intptr,int,intptr,intptr)
[libc] Fatal signal 6 (SIGABRT) at 0x00002876 (code=-6), thread 10358 (hlistviewnative)

**Comment by Andection** [comment]
I have same problem with inflatoring in xamarin.Forms 1.4.1.6349

**Comment by deepesh002** [comment]
I am having the same issue.Does anyone know if this works with the previous version of XF?

**Comment by Andection** [comment]
Yes, it's works. I downgraded XF to 1.2...
07.04.2015 11:08 пользователь "deepesh002" <notifications@github.com>
написал:

**Comment by dedene** [comment]
This seems fixed in 1-4-3-pre1

https://forums.xamarin.com/discussion/38729/xamarin-forms-1-4-3-pre1-released#latest

**Comment by conceptdev** [comment]
Yes, there were some know issues for a while with this sample, they should be resolved now.

**Comment by poppie** [comment]
Craig? Have you been fired? Do you have a manager that is curious why so
many posts remain unanswered?  Are you a born again, and believe this is
your way to salvation?

**Comment by conceptdev** [comment]
@poppie no, it was never our intention for these issues to remain unanswered so long; but as often happens in busy places, sometimes things get missed. this is just the first step in having these issues checked and resolved more frequently in future.
