### ISSUE TITLE
Sample "WorkingWithImages" don´t display "Download" Tab image (Uri image).

### ISSUE THREAD

**Issue by Fender92** [xamarin/xamarin-forms-samples#530]
### Sample

xamarin-forms-samples/WorkingWithImages/

### Description

When I click "DOWNLOAD" tab, image won´t appear. (URI)

All the other tabs show the image.

### Steps to Reproduce

1. Compile Android project version (Debug or Release);
2. Click "DOWNLOAD" Tab;
3. Wait.... wait... nothing no image exemple...

### Expected Behavior

See image from URI source downloading on the tutorial.

### Actual Behavior

Nothing at all. Tutorial won´t show image from URI source.

### Information

- IDE and IDE version: Visual Studio 2019 v16.3.1 
- Platform with the issue: - Android: 8.0 
- Device: Android Emulator (API 23)

**Comment by davidbritch** [comment]
Hi @Fender92 

This is a problem with the `Image` control in Xamarin.Forms 4.2. For more info see https://github.com/xamarin/Xamarin.Forms/issues/7751#issuecomment-536694500

As it's a problem with Xamarin.Forms, rather than a problem with the sample, I'm going to close this issue.
