### ISSUE TITLE
Navigation - TitleView - Android - Path too long build error

### ISSUE THREAD

**Issue by BrayanKhosravian** [xamarin/xamarin-forms-samples#531]
### Sample
Clone this repo and try to build it for android: https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/TitleView

### Steps to Reproduce

1. clone the repo
2. build for android

### Expected Behavior
no warnings

### Actual Behavior
path too long warning

### Information

-IDE Visual Studio 2017

### Image
![image](https://user-images.githubusercontent.com/35541212/66276606-216be100-e895-11e9-8dfe-8c4616c37106.png)

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

I recommend you take a read of https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception

**Comment by BrayanKhosravian** [comment]
Oh ok thank you very much
