### ISSUE TITLE
CustomMapRenderer samples : the line "Control.GetMapAsync(this);" in Android CustomMapRenderer.cs is causing OnMapReady() to be called twice.

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#534]
### Sample
CustomMapRenderer samples : the line "Control.GetMapAsync(this);" in Android CustomMapRenderer.cs needs to be removed.
It is causing OnMapReady() to be called twice because if you are using it like a View it will be called automatically.
(Ref: https://stackoverflow.com/questions/38802531/onmapready-gets-called-twice-on-first-run/58307164#58307164)

Samples:
https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map

- IDE and IDE version: 
Visual Studio 2019 v16.3.4
- Platform with the issue: 
Android SDK 9.0
- Device or simulator/emulator: 
Samsung SM-T810 (Android 7.0 - API 24)

**Comment by davidbritch** [comment]
Hi @davefxy 

Thanks for pointing this out. I'll get the samples/docs updated today.

**Comment by davidbritch** [comment]
I've removed the `GetMapAsync` calls from the Pin and Circle samples. There's no need to remove them from the Polygon and Polyline samples, as they are being deleted this week.
