### ISSUE TITLE
alert message does not pop-up

### ISSUE THREAD

**Issue by amarkatti** [xamarin/xamarin-forms-samples#540]
### Description

Alert pop-up message does not display for ios app.

### Steps to Reproduce

1.
2.
3.

### Information

I am using visual studio 2019 and pairing to mac machine.
when I click on button "Invoke C# Code" iOS app does not display any pop-up message.
this works fine for uwp and android app but not for iOS app.

Please fix this issue.

**Comment by profexorgeek** [comment]
Hi @amarkatti, can you specify which sample project you encountered this problem with?

**Comment by amarkatti** [comment]
Its in hybridview example:
xamarin-forms-samples/CustomRenderers/HybridWebView/

**Comment by amarkatti** [comment]
i got the fix for the above issue.

To enable javascript function calls in iOS apps, please check 'enable device specific builds' option under 
project -> properties ->iOS Build.
![github](https://user-images.githubusercontent.com/1284554/67289143-bdcfed80-f4fb-11e9-9271-d227314c846f.PNG)

**Comment by amarkatti** [comment]
There is also another way(better way) to enable scripts i.e. to create delegate. 
Please see attached pics.
![Delegate](https://user-images.githubusercontent.com/1284554/69028379-d26aad00-09f7-11ea-9ee4-6fb7c8e73f35.PNG)d
![assignDelegate](https://user-images.githubusercontent.com/1284554/69028408-e9a99a80-09f7-11ea-8928-39f1f01cc552.PNG)

**Comment by profexorgeek** [comment]
Thanks for taking the time to update this for future searchers!
