### ISSUE TITLE
Map doesnt appear on UWP release configuration

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#544]
### Sample

https://github.com/xamarin/xamarin-forms-samples/WorkingWithMaps/UWP
### Description
The UWP sample works fine in Debug configuration. However when using the release configuration, the map doesn't appear on any of the samples pages except the pages using the native map app.

### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Hi @davefxy 

This is now fixed. Thanks for bringing it to our attention. I'll get the docs updated re: this fix later today.
