### ISSUE TITLE
WorkingWithMaps sample cleanup actions

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#545]
### Sample

https://github.com/xamarin/xamarin-forms-samples/WorkingWithMaps
### Description
PolygonsPage.xaml => the Title="Polygon/Polyline XAML Demo" could be changed to Title="Polygon/Polyline Demo"

### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Hi @davefxy 

This is now fixed.
