### ISSUE TITLE
Map Pins sample should not use MarkerId to store a string because the Android code uses MarkerId this for its own internal info.

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#547]
### Sample

https://github.com/xamarin/xamarin-forms-samples/CustomRenderers/Map/Pin

### Description
The sample uses the Pin.MarkerId to store "Xamarin" that is then checked in the Android CustomRenderer.cs. Android uses the MarkerId field to store its own info. So the "Xamarin" string is overwritten and the comparison for "Xamarin" is never true.

### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Hi @davefxy 

Thanks for pointing this out. I've fixed the sample, and will update the docs later today.
