### ISSUE TITLE
Using this for multiple images

### ISSUE THREAD

**Issue by andywerber** [xamarin/xamarin-forms-samples#552]
I'm trying to adapt this code for use where a new container is created for several images and each container is added to a StackLayout. The critical code looks like this:

     foreach (string fileName in picFiles)
            {
                string picFileWebAddress = calls.Domain + "Rodney/" + actualDirectoryName + "/" + fileName;
                Image imgControl = new Image();
                imgControl.Source = picFileWebAddress;

                PinchToZoomContainer cont = new PinchToZoomContainer();
                
                cont.Content = imgControl;
                sl.Children.Add(cont);
            }
sl is a StackLayout declared in the XAML for the page.

I can see all the pictures, but I cannot zoom in, like I can when I run the example code that is related to this project.

I'm using the PinchToZoomContainer.cs file from the sample project. 

Any help with this would be appreciated.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
