### ISSUE TITLE
Change Placeholder Color

### ISSUE THREAD

**Issue by BalsamIbrahim** [xamarin/xamarin-forms-samples#553]
i want to change placeholder color from gray to black 
i use PlaceholderColor="Black" but not work 
i don't know why not work it code
can you help me please 
this all entry disabled 
![Screenshot_2019-11-18-15-57](https://user-images.githubusercontent.com/34779906/69058610-a7df1b00-0a1c-11ea-8146-1939cf5d8c2b.png)

**Comment by conceptdev** [comment]
Please raise issues with Xamarin.Forms on the [engineering GitHub repo](https://github.com/xamarin/xamarin.forms/issues), thanks.
