### ISSUE TITLE
UWP implementation of PhotoLibrary will never create a target folder

### ISSUE THREAD

**Issue by Dijji** [xamarin/xamarin-forms-samples#556]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos.UWP

### Description

There is a bug in the UWP implementation of PhotoLibrary. In SavePhotoAsync, if the target folder does not exist, then GetFolderAsync throws an exception, and so the test at line 59, if (folderDirectory == null), will always fail because folderDirectory is initialised to point at the pictures directory. Thus, the specified folder will never be created if it does not already exist.

### Steps to Reproduce

1. Run the FingerPaint demo and save a picture when there is no FingerPaint folder within Pictures

### Expected Behavior
The FingerPaint folder is created and the picture is saved to it

### Actual Behavior
The FingerPaint folder is not created and the picture is saved to the root pictures folder

### Information
Visual Studio 2017 running UWP build of demo on Windows 10

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
