### ISSUE TITLE
Local (JPG) Image files

### ISSUE THREAD

**Issue by DRAirey1** [xamarin/xamarin-forms-samples#559]
Why can't I find a single example where a XAMARIN application is reading images from a local resource?  WPF and UWP both have the ability to read the ms-appx protocol like this:

`                    <Image Source="ms-appx:///MyDLL/Assets/Portfolio.png"/>
`
From the assembly MyDLL.  How do you do the same thing in XAMARIN?

**Comment by davidbritch** [comment]
Apple provide their own approach for iOS, and Google provide their own approach for Android. For more info, see https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/images?tabs=windows#local-images and https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/images?tabs=windows#embedded-images
