### ISSUE TITLE
WorkingWithMaps UWP implementation requires additional line in UWP MainPage to work.

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#569]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps/WorkingWithMaps/WorkingWithMaps.UWP

### Description

On the UWP implmentation of the geocoder demo page, the "Geocode:" button doesnt return any locations for the sample address.
Always returns 0 geolocations for the sample address:"Pacific Ave, San Francisco, California"
Unless you add the follwing line to the MainPage.xaml.cs in the UWP folder:
            Xamarin.FormsMaps.Init("INSERT_AUTH_TOKEN_HERE");
===>  Windows.Services.Maps.MapService.ServiceToken = "INSERT_AUTH_TOKEN_HERE";

### Steps to Reproduce

1. Run the WorkingWithMaps demo, select the "Geocode and reverse geocode an address.", select the "Geocode" button.

### Expected Behavior
Display the geoposition of "Pacific Ave, San Francisco, California"

### Actual Behavior
Displays 0, 0

### Information
Visual Studio 2019 running UWP build of demo on Windows 10
Using Xamarin Forms & Maps v 4.4.0.991265 & visual studio 16.4.2

**Comment by davidbritch** [comment]
Thanks for pointing this out. Fixed by https://github.com/xamarin/xamarin-forms-samples/commit/2cb9a3fa1a1145709f4f65254a3aef8a43347887
