### ISSUE TITLE
Deep Linking is not working

### ISSUE THREAD

**Issue by rodrigojuarez** [xamarin/xamarin-forms-samples#570]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/DeepLinking

### Description

Deep linking is not showing elements in the emulator search, after an app link entry is created and registered

### Steps to Reproduce

1. Used my google-services.json
2. Set the build action to GoogleServiceJson
3. Change the package name to the one registered in firebase console
4. Start the app and create and save an item
5. Search in the emulator for the text used for the item

### Expected Behavior
The item should be visible in the search list

### Actual Behavior
The items is not visible in the result list

### Information

- IDE and IDE version: Visual Studio 2019 Community Edition 16.4.2
- Platform with the issue:
  - Android: 9.0
- Device or simulator/emulator: emulator

**Comment by rodrigojuarez** [comment]
Also, I can confirm that this is working on ios

**Comment by saamerm** [comment]
Were you ever able to figure this out @rodrigojuarez ?

**Comment by rodrigojuarez** [comment]
Not at all, not working for me yet @saamerm

**Comment by leelandclay** [comment]
There's quite a few requirements for this to work properly listed in the companion website. Did you check to make sure all of them are done? If you go to https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking#setup it has a section for Android and iOS

**Comment by rodrigojuarez** [comment]
I did at the time, I should run all the checks again to make sure it's still an issue

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
