### ISSUE TITLE
Error compiling ResourceTokenBroker

### ISSUE THREAD

**Issue by ekalyvio** [xamarin/xamarin-forms-samples#571]
### Error
Trying to compile the project located at:
/xamarin-forms-samples\WebServices\TodoDocumentDBAuth\ResourceTokenBroker\ResourceTokenBroker\
it gives the error "The target "Rebuild" does not exist in the project.".
No other targets also work (eg. Clean, Build, etc).

### Steps to Reproduce
This behavior occurs on a Visual Studio 2019 (16.3.9). No other VS have been tested.

**Comment by tefkin** [comment]
Similar issue. Tried with VS 2015 and 2019. messed around with csproj file as this usually seems to be the problem with aligning msbuild but to no avail. Can anyone build this broker? What VS version did they use?

**Comment by amgarnier** [comment]
I have the same issue as well

**Comment by kimho1021** [comment]
@davidbritch 
When i open this solution, the single project inside is missing packages.config file, and as a result there are numerous missing references related to System.Web.* ett
