### ISSUE TITLE
Could you please create a better example?

### ISSUE THREAD

**Issue by BillyMartin1964** [xamarin/xamarin-forms-samples#576]
Could you please create a better example of the Todo list local database with MVVM and multiple classes.

I like that we no longer have to use interfaces for the platform database, but I'm confused how generics would fit into this.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
