### ISSUE TITLE
iOS Resource video not playing in latest iOS

### ISSUE THREAD

**Issue by oscarjaergren** [xamarin/xamarin-forms-samples#577]
### Description

Download project and run on iOS emulator Iphone 11 iOS 13.3 or Tablet Ipad 7th generation iOS 13.3. It seems the same problem is with all the players and this player is no longer valid for iOS 13.

Android player works fine however

### Steps to Reproduce

1. Download this project
2. Run on latest iOS emulators
3. Pick any video to play

### Expected Behavior
Video plays

### Actual Behavior

Video is stuck after loading video image and then won't play anymore. 

### Information

Visual Studio 2019 - latest version 
iOS 13.3

**Comment by davidbritch** [comment]
I've just tried the sample in VSMac, on the iPhone 11 iOS 13.3 emulator, and I can play web videos and resource videos without any problems:

![Screenshot 2020-02-07 at 16 36 17](https://user-images.githubusercontent.com/8092460/74047395-2f0eb000-49c8-11ea-9131-cbc17a7d9027.png)

![Screenshot 2020-02-07 at 16 36 34](https://user-images.githubusercontent.com/8092460/74047397-303fdd00-49c8-11ea-8981-e3b3868f58bd.png)

![Screenshot 2020-02-07 at 16 36 51](https://user-images.githubusercontent.com/8092460/74047404-31710a00-49c8-11ea-88e5-ed0f6b0edc4c.png)
