### ISSUE TITLE
Invoke in Reveal mode works in simulator. Not on physical phone.

### ISSUE THREAD

**Issue by larspehrsson** [xamarin/xamarin-forms-samples#578]
### Sample

https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/SwipeViewDemos/SwipeViewDemos/Views/SwipeViewModeBehaviorPage.xaml

### Description

SwipeMode = Execute works fine. SwipeMode = Reveal works in Android Simulator but not on my Android Phone (Huawei P20 pro)

### Steps to Reproduce

1. Run SwipeView mode and behaviour sample
2. Toggle between "Reveal" and "Execute"

### Expected Behavior
When clicking buttons in Reveal mode I expect to get the same result as when swiping in Execute mode. But nothing happens.

### Actual Behavior
Nothing happens.

### Information

- IDE and IDE version: VS 2019 16.4.4
- Platform with the issue:
  - Android: Huawei P20 Pro. Android 9.0 1. december 2019. Does not work.
  - Device or simulator/emulator: Android 9. API 28. Work.

**Comment by davidbritch** [comment]
Some of the SwipeView code relied on having API 23 as a minimum. This has since been updated in Xamarin.Forms 4.5-pre3, so hopefully it'll fine for you in the next release.
