### ISSUE TITLE
Ios info window touch area issue

### ISSUE THREAD

**Issue by nithinlogiticks** [xamarin/xamarin-forms-samples#583]
map pin info window has full view touch property for android. But in the case of ios output is not as expected, it allow only touch inside info icon . can you please update the sample with touch area  to the full view

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
