### ISSUE TITLE
[Bug] [Crash] Interactive Linear Gradient Demo crashes on Android, UWP, ....

### ISSUE THREAD

**Issue by maexsp** [xamarin/xamarin-forms-samples#588]
Start the demo on UWP or Android and choose "SkiaSharp Effects" and "Interactive Linear Gradient" and it will crash immediatly. 

- IDE and IDE version: VS2019 latest

Just use the Demo source code as it is.

**Comment by davidbritch** [comment]
Hi @maexsp 

I've just fixed this. Thanks for bringing it to my attention.

**Comment by maexsp** [comment]
@davidbritch Thx for the fix.
