### ISSUE TITLE
Entry values are changing when switch tabs if I use visual material in  Xamarin forms shell app

### ISSUE THREAD

**Issue by tal-athena** [xamarin/xamarin-forms-samples#589]
I am now developing Xamarin forms shell app
and used visual material

but whenever I switch tabs, entry values are not kept, it's changing 
If I don't use visual material all values are kept.

**Comment by davidbritch** [comment]
Hi @tal-athena 

That's one for the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
