### ISSUE TITLE
WorkingWithTriggers

### ISSUE THREAD

**Issue by stoverje** [xamarin/xamarin-forms-samples#59]
On Android and iOS, the requirements to have a length > 0 for button to become active isn't working, button is active all the time (on Data Trigger and MultiTrigger tabs).
On Android and iOS, on MultiTrigger tab, requiring BOTH username and password never activates the Login button.

Building app for iOS (iPhone 5S, iOS 8.3, Forms 1.4.2.6359) throws an exception this.LoadFromXaml(typeof(DataTriggerXaml)); (on _LabelRenderer).
(NOTE: Found that with this update of Xamarin Forms, have to make sure text on labels is in Text attribute tags and that fixes this issue).

**Comment by conceptdev** [comment]
The `<Label>Some Text</Label>` problem has been reported as a bug.

**Comment by conceptdev** [comment]
apologies @stoverje - the sample was accidentally updated to remove the `x:Name` attributes that are required for the `{x:Reference}` to work. this has been fixed in branch **1.4.3** and will be pushed to master soon.
