### ISSUE TITLE
[BUG][ANDROID] Customizing a Map Pin Exemple

### ISSUE THREAD

**Issue by Hydeo** [xamarin/xamarin-forms-samples#590]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin

### Description

Android version of this doesn't work , map view is showing but blank (no map tiles) and the custom pin doesn't show.
Works fine on IOS.

![Capture](https://user-images.githubusercontent.com/9498498/76006661-bc302080-5f04-11ea-820b-604c10a2ce8e.JPG)

### Steps to Reproduce

Start android app of this exemple/

### Expected Behavior
Show the map with the custom pin

### Actual Behavior

Empty map

### Information

- IDE and IDE version: Microsoft Visual Studio Community 2019 Version 16.4.4
- Tried on Android simulator (Android 9.0 - Api 28) and my phone (Android 8.0 - Api 26)

**Comment by davidbritch** [comment]
Hi @Hydeo 

That's because on Android you need to supply a Google Maps API key, in your AndroidManifest.xml file. See https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/map/setup#get-a-google-maps-api-key
