### ISSUE TITLE
Where is the enum Color defined? Can't use it without it.

### ISSUE THREAD

**Issue by lynnkuh** [xamarin/xamarin-forms-samples#591]
### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
It's a struct: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Color.cs
