### ISSUE TITLE
[request] Add UWP project to Shell Xaminals sample

### ISSUE THREAD

**Issue by MappingSteve** [xamarin/xamarin-forms-samples#595]
[XF issue 5593](https://github.com/xamarin/Xamarin.Forms/issues/5593) is **Done**, and [a comment there by PureWeen](https://github.com/xamarin/Xamarin.Forms/issues/5593#issuecomment-532352456) shows a screenshot of Xaminals running on UWP.

Yet I see that the sample source code here does not include such a UWP project.

Would be great to have a Xaminals UWP project added to this repo.

**Comment by rhy-ama** [comment]
+1

Additional question - starting from an empty UWP project what are the dependencies/nuggets we would need to include to get it?

**Comment by davidbritch** [comment]
This is now done.
