### ISSUE TITLE
Xamarin.Forms.Shell for UWP navigate to detail page is not working

### ISSUE THREAD

**Issue by cairoutm** [xamarin/xamarin-forms-samples#598]
Hi;

I have just downloaded Xamarin.Forms.Shell and try to run on UWP platform. I have found out that nanavigate to detail page and search function is not working. The link of code is here

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

**Comment by davidbritch** [comment]
Hi @cairoutm 

Shell support on UWP is still experimental, and isn't fully implemented yet. It's very much a work in progress feature.
