### ISSUE TITLE
SwipeViewDemo - Crashes on Android as currently configured

### ISSUE THREAD

**Issue by ToddVan** [xamarin/xamarin-forms-samples#599]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/SwipeViewDemos

### Description

Simply trying to explore the SwipeViewDemo, downloaded ZIP. Opened in VS2019 compile and run on Pixel 2 Emulator. Select a view and it will crash when trying to load any of the views referencing the SwipeView.

I have confirmed it has to due with the version of Xamarin.Forms NUGET the solution pulls down. **When I change it to Xamarin.Forms 4.4 things work fine.**

Perhaps just a warning on the MSDN page as we do call out this is experimental:
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-swipeviewdemos/

### Steps to Reproduce

1. Download zip https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-swipeviewdemos/
2. Extract
3. Load into VS2019
4. Compile
5. Run in Pixel 2 Emulator
6. Select a SwipeView Sample

### Expected Behavior
Should just load the correct view then render

### Actual Behavior
Crashes when attempting to load the sample view

### Information

- IDE and IDE version: VS 2019
- Platform with the issue: 
   - Android: Pixel 2 - 28.
- Device or simulator/emulator: Emulator (Haven't tested on phone)

**Comment by Wolvenart** [comment]
I have the same issue as well.
System.InvalidCastException is thrown on line 38 of SwipeViewDemoPage.cs file;

                swipeView.LeftItems = new SwipeItems { swipeItem };

**Comment by davefxy** [comment]
The problem occurs on my tablet also. The statement flagged (specified cast is invalid) is line 38 in SwipeViewDemoPage.xaml.cs :
swipeView.LeftItems = new SwipeItems() { swipeItem };
I replaced this with:
swipeView.LeftItems.Add(swipeItem);

**Comment by davidbritch** [comment]
Thanks for logging this issue @ToddVan 

Luckily, it's all good again in Xamarin.Forms 4.6.
