### ISSUE TITLE
XAML version of MasterDetailPage Sample has no way to access the MasterPage

### ISSUE THREAD

**Issue by Wolvenart** [xamarin/xamarin-forms-samples#601]
### Sample

FormsGallery/FormsGallery/FormsGallery/XamlExamples/MasterDetailPageDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/MasterDetailPageDemoPage.xaml.cs

### Description

Upon selecting the MasterDetailPageDemo from under the XAML tab the page automatically moves to the detail page with the "Aqua" color selected. And from there there's no way to access the MasterPage menu to select colors. At first I thought the issue might be with the NuGet packages, as earlier in the Styling section of the documentation the color changes didn't apply to the app and by updating the NuGet packages it began working as intended, so I tried updating them. However, it still didn't work.

As the CS version of the page works as intended, I decided to compare the codes and it seems the TapGestureRecognizer part is missing from the XAML version. And as there is no other changes to the IsPresented property anywhere in the code only the Detail page is shown.

### Information
  -Visual Studio 2019 v.16.5.2
  -Xamarin.Forms v.4.5.0.530
  -Tested on Emulated Google Pixel Device - Android 9.0 API 28

**Comment by davidbritch** [comment]
I'll also close the issue here, as the PR contains my response.
