### ISSUE TITLE
Resharper: Can not resolve symbol RelativeSource RelativeSourceExtension

### ISSUE THREAD

**Issue by vardansargsyan92** [xamarin/xamarin-forms-samples#602]
### Sample

[sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/DataBindingDemos)

### Description

Hi all. 

 I have a problem and suppose many of the others have this issue too. I just downloaded the sample and tried to debug it. Everything works fine except recognizing extension properties like "RelativeSource" or "AncestorType" by Resharper.

My Resharper does not recognize 'RelativeSource' telling me that "Can not resolve symbol RelativeSource RelativeSourceExtension". I have tried to update the Resharper but it did not help me. The Resharper works fine when I create custom markup extension (does not matter the content inside the extension. The properties which I define inside extension class are recognizable by Resharper). So any ideas how can I solve this? 

### Steps to Reproduce

1. Open app 
2. Go to RelativeSourceSelfPage.xaml
3. Check BoxView Control

### Expected Behavior

"{Binding Source={RelativeSource Self}, Path=WidthRequest}" should be recognizable by Resharper

### Actual Behavior

![image](https://user-images.githubusercontent.com/19687305/78883581-bdf08500-7a6a-11ea-9854-ab20ee03ad37.png)

### Information

- IDE and IDE version: Microsoft Visual Studio Community 2019 Version 16.5.1 
- Resharper version: 2019.3.4

**Comment by davidbritch** [comment]
Hi @vardansargsyan92 

Afraid this is an issue with the product, rather than a specific sample. Therefore, the issue should be opened at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) where it'll get triaged and assigned to the correct product team.

**Comment by vardansargsyan92** [comment]
ok thanks
