### ISSUE TITLE
Is it possible to have multiple circle ?

### ISSUE THREAD

**Issue by stann84** [xamarin/xamarin-forms-samples#603]
### Description

I try to have a circle for a lot of pin do you thinks is possible 

### Expected Behavior
one circle for each user

### Actual Behavior
pin and circle

### Information

- IDE and IDE version: 
- Platform with the issue: 
 
  - Android: 
9

Thank you

**Comment by PaoloLeva** [comment]
I added this code in OnMapReady to draw a circle around each Pin. I guess it is a similar code to draw a circle around each user:

```
            foreach (Pin p in customMap.Pins)
            {
                var circleOptions = new CircleOptions();
                circleOptions.InvokeCenter(new LatLng(p.Position.Latitude, p.Position.Longitude));
                circleOptions.InvokeRadius(500);
                circleOptions.InvokeFillColor(0X66CCCC00);
                circleOptions.InvokeStrokeColor(0X66FFFF00);
                circleOptions.InvokeStrokeWidth(4);

                NativeMap.AddCircle(circleOptions);
            }
```

**Comment by davidbritch** [comment]
Hi @stann84 and @PaoloLeva 

Xamarin.Forms 4.6, which will be released next week, includes cross-platform support for drawing circles on maps (without using custom renderers). I'd recommend waiting for that release, then it'll be easy to add multiple circles to a map.
