### ISSUE TITLE
AppleSignIn didn't close Browser on Finish activity

### ISSUE THREAD

**Issue by juanredondo** [xamarin/xamarin-forms-samples#604]
### Description

The Apple SignIn example, open a Browser in Android, in order to login on apple Id external page. When the process finish, return to an Activity open by a callback Uri, on Finish(), the browser opened is not closed.

### Steps to Reproduce

1. Update to Xamarin.Essentials 1.5.3
2. Run Android on a VS Emulator (or a device)
3. Login with Apple ID

### Expected Behavior

Closed Internal Browser on Finish() Activity

### Actual Behavior
Not Closed Browser on Finish() Activity
If changed Essentials.Browser.OpenAsync to Launcher.OpenAsync() or open with BrowserLaunchMode.External, works as expected

### Information

- IDE and IDE version: Visual Studio 2019 16.4.5
- Platform with the issue: 
  - Android: Android 
- Device or simulator/emulator: Pixel VS Emulator

**Comment by saamerm** [comment]
@juanredondo so is the solution just to use Launcher.OpenAsync instead?

**Comment by juanredondo** [comment]
Finally we have  
```

await Xamarin.Essentials.Browser.OpenAsync($"{InitialAuthUrl}?&state={currentState}&nonce={currentNonce}",
                Xamarin.Essentials.BrowserLaunchMode.External);
```

in order to work with essentials

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
