### ISSUE TITLE
Can I base a commercial app off of these samples?

### ISSUE THREAD

**Issue by testmaster217** [xamarin/xamarin-forms-samples#606]
### Description

I want to make an app and sell it and I want to base several features of that app off of these samples. If I do that, can I sell the app for any price other than "free"? I'm not sure if this is a good place to ask this question, but I don't know where else to ask.

**Comment by davidbritch** [comment]
Hi @testmaster217 

I recommend you read the [license](https://github.com/xamarin/xamarin-forms-samples/blob/master/LICENSE) for this repo, and the Apache license it links to.

**Comment by testmaster217** [comment]
I read them before I asked this.
