### ISSUE TITLE
Hyperlink on hyperlink sample 404

### ISSUE THREAD

**Issue by ymebrugts** [xamarin/xamarin-forms-samples#608]
[https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Hyperlinks
](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Hyperlinks
)
It's a bit ironic but the hyperlink in the hyperlink sample readme goes to 404.

**Comment by davidbritch** [comment]
Hi @ymebrugts 

Thanks for pointing this out. I've just fixed the link in the repo. It'll take an hour or two for the CI to update the samples gallery.
