### ISSUE TITLE
CollectionViewDemos doesn't work with "Link All" link option

### ISSUE THREAD

**Issue by xplatform** [xamarin/xamarin-forms-samples#614]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/CollectionViewDemos

### Description

If I set the link option to "Link All" in the iOS project, the example doesn't work at all. The main page shows up, but when you click on the items, it doesn't go into the expected page. If you set one of the test pages to be the main page, the image and the description will not be shown inside the page.

### Steps to Reproduce

1. Open CollectionViewDemos.sln in VS
2. Right click on CollectionViewDemos.iOS project, and change the Link Behavior to "Link All".
3. Build CollectionViewDemos.iOS project and run it on an iOS device.

### Expected Behavior
The main page shows up when running on the device. When you click on the items, it should go inside the next page, with name, image, and description if they exists.

### Actual Behavior
The main page shows up, but when you click on the items, it doesn't go into the expected page.

### Information

- IDE and IDE version: Visual Studio Mac v7.4
- Platform with the issue: 
  - iOS:  11.4
- Device or simulator/emulator: Tested on an iPhone

**Comment by davidbritch** [comment]
Hi @xplatform 

Apologies for the delayed response to your issue.

LinkAll is a really aggressive choice, that isn't XAML aware. Therefore, the linker is removing anything that isn't referenced through code. There are number of approaches to dealing with this. The simplest is to tell the linker not to remove any of the types in the .NET Standard project (CollectionViewDemos). This can be accomplished by setting `--linkskip=CollectionViewDemos` as an mtouch argument:

![Screenshot 2020-08-18 at 12 49 21](https://user-images.githubusercontent.com/8092460/90509588-77661200-e151-11ea-97fd-9beb69b97ff1.png)

This stops the linker removing all the types in the CollectionViewDemos assembly, and the sample then runs correctly with the LinkAll option chosen.

I recommend you read https://montemagno.com/optimizing-xamarin-apps-libraries-with-the-linker/ to gain a better understanding of controlling the linker.
