### ISSUE TITLE
Issues in data editing for two way ListView binding

### ISSUE THREAD

**Issue by msajjadh8411** [xamarin/xamarin-forms-samples#616]
### Sample

https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-listview-switchentrytwobinding/

### Description

When we enter data each keypress is required twice. I resolved this issue by removing extra OnPropertyChanged() from setter functions in light.cs BUT it hides the ON/OFF state on home page.

	public class light : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		private string _name;
		private string _comment;
		private Color _color;
		private bool _isOn;
		public string name
        {
            get{ return _name;}
            set
            {
                //OnPropertyChanged ();
                _name = value;
            }
        }
		public string comment
        {
            get{return _comment;}
            set
            {
                //OnPropertyChanged ();
                _comment = value;
            }
        }
		public Color color
        {
            get{ return _color;}
            set
            {
                //OnPropertyChanged ();
                _color = value;
            }
        }
		public bool isOn
        {
            get{ return _isOn;}
            set
            {
                //OnPropertyChanged ();
                OnPropertyChanged ("isNotOn"); _isOn = value;
            }
        }
		public bool isNotOn{ get { return !_isOn; } }

		public light ()
		{
			this.isOn = false;
			this.name = "My first light!";
			this.color = Color.Blue;
			this.comment = "Bedroom";
		}
		public light(bool isOn, string name, Color color, string comment)
		{
			this.isOn = isOn;
			this.name = name;
			this.color = color;
			this.comment = comment;
		}
		void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			var handler = PropertyChanged;
			if (handler != null)
			{
				handler(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

### Steps to Reproduce

1. Run the application
2. Click on the Name menu
3. Try to edit the data

### Expected Behavior
Each character entry should work on single keypress but it requires to press each key twice

### Actual Behavior
I need to press each character twice

### Information

- IDE and IDE version: Visual Studio Mac 
- Platform with the issue: 
  - iOS:
  - Android:
- Device or simulator/emulator: Tested on simulator/emulator

**Comment by davidbritch** [comment]
Hi @msajjadh8411 

The sample code was incorrect. `OnPropertyChanged` should only be called after the property has been updated, not before. I've updated the sample.

**Comment by msajjadh8411** [comment]
Thanks. I will test it soon.
