### ISSUE TITLE
Unable to run samples from Xamarin Studio on OSX

### ISSUE THREAD

**Issue by trevoriancox** [xamarin/xamarin-forms-samples#62]
When loading many of the Android projects (e.g. WorkingWithListview, FormsGallery), the Android project appears to be configured as a library and cannot be run (both for Debug and Release configs). Only the iOS project will run.

**Comment by conceptdev** [comment]
@trevoriancox does this occur with only some or ALL of the Android projects for you. I cannot reproduce this issue - the two projects you mentioned work fine in Xamarin Studio on OS X.

**Comment by HelenW2** [comment]
Craig,

Let me try it again. I was using Visual Studio 2013 on a Windows Server 2008 R2 SP1. I’ve just installed it all on my laptop (Windows 7) so will try there.

Thanks,

 

Helen

**Comment by trevoriancox** [comment]
Thanks @conceptdev, after getting your reply I tried again and got it to run. Sorry it was a newbie issue. Unlike some other IDE's, unless I select "Set as Startup Project", the project cannot be run. And Xamarin seems to show "Library" as the compile target for FormsGallery.Android even though you can run it.
