### ISSUE TITLE
The type 'Expander' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built. Error when putting <Expander> in XAML

### ISSUE THREAD

**Issue by eleehiga** [xamarin/xamarin-forms-samples#621]
### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by eleehiga** [comment]
I am using Visual Studio Mac

**Comment by davidbritch** [comment]
Hi @eleehiga 

`Expander` was released in Xamarin.Forms 4.6. So that's the minimum requirement. 

If you take a look at the [sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/ExpanderDemos), you'll see it works fine.
