### ISSUE TITLE
Error to publish app with hybridwebview

### ISSUE THREAD

**Issue by joananms** [xamarin/xamarin-forms-samples#623]
### Description

I receive this message from apple after publsih app:
![image](https://user-images.githubusercontent.com/12891938/82436406-10738700-9a96-11ea-9996-401b8cc353e1.png)

Somebody can help me with this issue?

**Comment by plucenio** [comment]
* ITMS-90809:

1 - Update the Xamarin.Forms version
2 - You can go to your iOS project, open the project properties and add this flag in the additional mtouch arguments field: --optimize=experimental-xforms-product-type this flag works together with the Linker Behavior set to SDK Only or All.

https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/

**Comment by davidbritch** [comment]
https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/webview?tabs=windows#uiwebview-deprecation-and-app-store-rejection-itms-90809
