### ISSUE TITLE
Native2Forms crash on iOS (Method 'UINavigationBar.SetTitleTextAttributes' not found)

### ISSUE THREAD

**Issue by kladis** [xamarin/xamarin-forms-samples#63]
Hi,

I've crash at launch:
Method 'UINavigationBar.SetTitleTextAttributes' not found.

Thx.

**Comment by conceptdev** [comment]
what version of Xamarin.Forms are you using? I just tested on 1.4 and it works fine (latest Stable Xamarin and Xcode versions):

![ios simulator screen shot jun 10 2015 1 04 32 pm](https://cloud.githubusercontent.com/assets/199373/8092792/479a681c-0f71-11e5-9639-0df88a4e1872.png)
