### ISSUE TITLE
MT0099: Error: The interpreter is currently only available for 64 bits. 

### ISSUE THREAD

**Issue by bhdxzt** [xamarin/xamarin-forms-samples#637]
### Sample

any sample code

### Description
ios sdk mini target:8.0
ipad mini sdk :ios9.3
device :iphone/ipod
architecture：armv7+arm64
visual studio:8.6.3(build 30)
xcode:11.5

when I connect the ipad mini to run demo,visual studio notice a error.
MT0099: Error: The interpreter is currently only available for 64 bits

### Steps to Reproduce

1.when I connect the ipad mini to run demo,visual studio notice a error
2.MT0099: Error: The interpreter is currently only available for 64 bits

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by aimore** [comment]
https://github.com/xamarin/xamarin-macios/pull/5772

**Comment by davidbritch** [comment]
Hi @bhdxzt 

Have you tried switching off Hot Reload?

**Comment by saamerm** [comment]
@bhdxzt it should be working now with the latest Xamarin.iOS version. Do you want to close this?

**Comment by bhdxzt** [comment]
it should be working now with the latest Xamarin.iOS version

**Comment by omatrot** [comment]
@saamerm I have this issue.

Visual Studio Community 2019 for Mac (Preview)
Version 8.9 Preview (8.9 build 265)
Installation UUID: a724e304-792e-4b36-9026-f73688b8aef0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 612000107

Xamarin.iOS
Version: 14.7.0.166 (Visual Studio Community)
Hash: d91932dcd
Branch: main
Build date: 2020-10-21 10:50:26-0400

<img width="960" alt="Screenshot 2020-12-04 at 14 24 43" src="https://user-images.githubusercontent.com/4366356/101168932-83141080-363c-11eb-9a45-af817f347f5f.png">

**Comment by farukaf** [comment]
I got the same problem @omatrot does. Similar configuration building to iPad2
