### ISSUE TITLE
activityindicator UWP not works

### ISSUE THREAD

**Issue by ortizbnu** [xamarin/xamarin-forms-samples#641]
No uwp o activityindicator não está sendo executado quando dele deveria ser exibido.
Em IOS e Android rodam normalmente.

Xamarin.Forms 4.7.0.1142

### Steps to Reproduce
![buguwp](https://user-images.githubusercontent.com/47483268/87812294-52227300-c836-11ea-80f3-4b89619f0c4f.png)

https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-activityindicatordemos/

### Expected Behavior
activityindicator deveria ser exibido

### Actual Behavior
activityindicator não aparece

**Comment by davidbritch** [comment]
Hi @ortizbnu 

Your screenshot shows the two `ActivityIndicator` objects - the blue dots, and the orange dots.
