### ISSUE TITLE
How to create a view whose positions can be changed by accelerometer in Xamarin

### ISSUE THREAD

**Issue by liutiming** [xamarin/xamarin-forms-samples#643]
### Sample

https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/ShapesDemos/ShapesDemos/Views/PathRenderTransformExamplesDemoPage.xaml

### Description

                    <TranslateTransform X="50"
                                        Y="50" />

### Steps to Reproduce

1. change X and Y value

### Expected Behavior

figure change 
### Actual Behavior

 does not change the figure. 
### Information

- IDE and IDE version: 
- Platform with the issue: 
  - Android: 
- Device or simulator/emulator: 

Also a relevant question posted by me on [SO](https://stackoverflow.com/questions/62985679/how-to-create-a-view-whose-positions-can-be-changed-by-accelerometer-in-xamarin)

**Comment by davidbritch** [comment]
Hi @liutiming 

[This sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/Sensors/TiltMaze) uses the accelerometer to move a view.
