### ISSUE TITLE
WebServices Security concern

### ISSUE THREAD

**Issue by hraz-msft** [xamarin/xamarin-forms-samples#644]
In this code:
https://github.com/xamarin/xamarin-forms-samples/blob/32bc9dcefd6c176db89c6d46759bdc38c849a794/WebServices/CognitiveSpeechService/CognitiveSpeechService/CognitiveSpeechService/Constants.cs#L7

Isn't it security issue to store the key directly in the app? I mean, by sniffing traffic or decompiling, the secret key can be revealed.

I can't see any usage of WebServices directly in Xamarin apps because of the hard coded keys. What is the best practice for such usage?

**Comment by davidbritch** [comment]
Hi @hraz-msft 

Yes, keys should never be stored in the app. However, it's necessary in small samples to show how to invoke a particular service. The best practice is to use a web backend as a middle layer between your mobile app and service you are invoking. API keys should then be stored in the web backend.
