### ISSUE TITLE
Skia sharp deprecated function correction

### ISSUE THREAD

**Issue by sarthak1995-26** [xamarin/xamarin-forms-samples#646]
Below line are deprecated with latest skia sharp nuget.

SKMatrix bitmapScaleMatrix = SKMatrix.MakeIdentity();
            bitmapScaleMatrix.SetScaleTranslate(scale, scale, x, y);

At

https://github.com/xamarin/xamarin-forms-samples/edit/master/SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos/Bitmaps/PhotoCropperCanvasView.cs

I couldn't find any refrence to make them correct.

Anybody know a way ?

**Comment by davidbritch** [comment]
Hi @sarthak1995-26 

`MakeIdentity` can be replaced with `CreateIdentity`.

[This issue](https://github.com/mono/SkiaSharp/issues/1415) explains that it's still safe to use `SetScaleTranslate` until the `CreateScaleTransition` method makes it into a release (see https://github.com/mono/SkiaSharp/pull/1431).
