### ISSUE TITLE
iOS Bug

### ISSUE THREAD

**Issue by mrj001** [xamarin/xamarin-forms-samples#647]
### Sample
https://github.com/xamarin/xamarin-forms-samples/BugSweeper

### Description
On iOS only, the double tap gesture recognizer is not working.  It is recognized as a single tap. Additionally, subsequent single taps on the same Tile do nothing.  It works as expected on the Android emulator.

### Steps to Reproduce
$ git fetch origin master
$ git merge origin/master

Open Visual Studio for Mac and rebuild all.  I've previously updated all the dependencies and Visual Studio for Mac to the latest.

### Expected Behavior
Double taps should work.  Single taps subsequent to the first should work as well.

### Actual Behavior
As described above.

### Information
- IDE and IDE version: Visual Studio for Mac, 8.6.8 (build 2)
- Platform with the issue: iOS
  - iOS:  13.6
  - Android: Oreo
  - UWP:  n/a
- Device or simulator/emulator: iPhone 11 simulator

Under "About Visual Studio", this is the details:
=== Visual Studio Community 2019 for Mac ===

Version 8.6.8 (build 2)
Installation UUID: acda7116-5881-49e3-ad26-52bf939abb41
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000106

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.106 (2019-12/77769615db1) (64-bit)
	Package version: 610000106

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks
SDK Versions:
	3.1.302
	3.1.301
	3.1.300
	3.1.201
	3.1.200
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.6
	3.1.5
	3.1.4
	3.1.3
	3.1.2
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin.iOS ===

Version: 13.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/mj/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.2
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/mj/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:42:50 UTC

=== Android Device Manager ===

Version: 16.6.0.96
Hash: 6e8b80b
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:43:28 UTC

=== Build Information ===

Release ID: 806080002
Git revision: e999e2934e8c771fdf6494b80361dacef9427565
Build date: 2020-07-24 15:17:52-04
Build branch: release-8.6
Xamarin extensions: e999e2934e8c771fdf6494b80361dacef9427565

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by davidbritch** [comment]
Hi @mrj001 

I just tried this sample in iOS and both single and double taps worked fine for me. It might be related to the fact that since you opened this issue the sample has been updated to Xamarin.Forms 4.8.
