### ISSUE TITLE
Bindable Picker don't show choosed entry on Android

### ISSUE THREAD

**Issue by TFreudi1** [xamarin/xamarin-forms-samples#653]
xamarin-forms-samples/UserInterface/BindablePicker/

If you choose a color and open the picker, the picker isn't positioned on the choosed item on Android. It works with UWP and iOS.

### Steps to Reproduce

1. Open the sample project
2. Choose Khaki color
3. Tap on "Khaki" to open the picker
4. Picker starts with Alice blue

### Expected Behavior
Picker should show the actual bounded selection text row "Khaki"

### Actual Behavior
Picker ignore the selectedItem

### Information

- IDE and IDE version: Visual Studio 2019 v16.7 Xamarin Forms 4.8.0.1269 und  4.7.0.1269  
- Platform with the issue: Only Android
- it happens on Device and simulator and emulator don't matter which Android Version

**Comment by davidbritch** [comment]
Hi @TFreudi1 

This is an issue with the `Picker` on Android, rather than an issue with the sample. There's an [open issue](https://github.com/xamarin/Xamarin.Forms/issues/3885) in the engineering repo which you can track.
