### ISSUE TITLE
Exception ocurred when running Xaminals UWP sample

### ISSUE THREAD

**Issue by cairoutm** [xamarin/xamarin-forms-samples#655]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

### Description

I got an exception "The operation attempted to access data outside the valid range\r\n\r\nThe operation attempted to access data outside the valid range\r\n" when clicking on one item of flyout item in xamarin.forms uwp shell

### Steps to Reproduce

1. Set uwp project as startup project and run
2. Click on Monkey menu
3. Click on Elephant menu. Here exception will occurred.

### Information

- IDE and IDE version: 
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
Hi @cairoutm 

I just tried your repo steps in VS2019 16.7.1 and there was no exception for me. Everything worked fine.
