### ISSUE TITLE
Xaminals UWP version fails to display tool bar item icons at top of catspage

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#658]
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

There are no icons displayed on the toolbar (upper right) of the CatsPage.
You can see the error "Error: Converter failed to convert value of type" in the output display when the sample is loaded.

### Steps to Reproduce
1.Set uwp project as startup project and run in debug mode

### Information

IDE and IDE version: <!-- Visual Studio 2019 v16.7.1 >
Platform with the issue:
UWP:
Device : local PC

**Comment by davidbritch** [comment]
Hi @davefxy 

Not entirely sure where you're expecting to see icons. Here's how it looks in UWP for me:

![cats](https://user-images.githubusercontent.com/8092460/90499547-96f53e80-e141-11ea-87e3-6202a9d213d0.PNG)

Everything is rendered correctly here.

**Comment by davefxy** [comment]
I am so sorry. I hadn’t updated my Xaminals sample. I was using the Xaminals sample from Sept of 2019. It had the following CatsPage.xaml code:
    <ContentPage.ToolbarItems>
        <ToolbarItem Order="Primary"
                     Text="Icon Item"
                     Priority="0"
                     IconImageSource="random.png"
                     Clicked="OnItemClicked" />
        <ToolbarItem Order="Primary"
                     Text="Text Item"
                     Priority="1"
                     IconImageSource="random.png"
                     Clicked="OnItemClicked" />
        <ToolbarItem Order="Secondary"
                     Text="Secondary Text Item"
                     Priority="2"
                     IconImageSource="random.png"
                     Clicked="OnItemClicked" />
    </ContentPage.ToolbarItems>

Sent from Mail for Windows 10

**Comment by davidbritch** [comment]
No worries.
