### ISSUE TITLE
M3u8 url not getting played on Xamarin Forms Android but it works great on Xamarin Forms iOS. 

### ISSUE THREAD

**Issue by samirgcofficial** [xamarin/xamarin-forms-samples#659]
Same to test app : 
http://xamaringuyshow.com/wp-content/uploads/2020/08/XamVideoPlayerTest.zip

M3u8 url not getting played on Xamarin Forms Android but it works great on Xamarin Forms iOS. 
This url might not work when you are trying out as it will expire. Please use any m3u8 url video for references. .
https://player.webvideocore.net/CL1olYogIrDWvwqiIKK7eCmUWcttrmpfWk1CLOwAWiHedzK6O5cOLfCnuy8hDKifAuUSy-R0mihNFzC6ddxsIv_Ydp-E431-PM_gnnoesNs=/a_70ihwwmahkg8.m3u8

**Comment by davidbritch** [comment]
Hi @samirgcofficial 

This is due to lack of support in the `MediaElement` control. There's a bug open for this feature in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/issues/11615), which also has some work arounds.
