### ISSUE TITLE
DragAndDropGesture sample when debug compiled for android gets an "Got a SEGV while executing native code"

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#660]
https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithGestures/DragAndDropGesture

DragAndDropGesture sample when debug compiled for android get an "Got a SEGV while executing native code"

=================================================================
	Native Crash Reporting
=================================================================
Got a SEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

No native Android stacktrace (see debuggerd output).

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xebd93dfb):0xebd93deb  cc cc cc cc cc 8b 54 24 04 8b 44 24 08 0f b6 08  ......T$..D$....
0xebd93dfb  38 0a 0f 85 4d 14 00 00 83 f9 00 0f 84 4e 14 00  8...M........N..
0xebd93e0b  00 0f b6 48 01 38 4a 01 0f 85 37 14 00 00 83 f9  ...H.8J...7.....
0xebd93e1b  00 0f 84 38 14 00 00 0f b6 48 02 38 4a 02 0f 85  ...8.....H.8J...

=============================================================

08-17 12:20:56.699 D/Mono    (24637): Requesting loading reference 0 (of 2) of Java.Interop.dll====
	Managed Stacktrace:
=================================================================
=================================================================

To reproduce, build the DragAndDropGesture sample for Debug, Android and run it on an Android device. Insure the Target Android version is Android 10.0 (API Level 29-Q)

- IDE and IDE version: 
  - Android: Android 10.0 (Q)
- Device or simulator/emulator: Failed on a Samasung 10+ phone and Pixel 3a XL Q 10.0 - API 29 emulator

**Comment by davidbritch** [comment]
Hi @davefxy 

This needs logging in the [engineering repo](https://github.com/xamarin/xamarin.forms/) so that it can be fixed for the 5.0 release.

**Comment by davefxy** [comment]
Out of curiosity, have you seen this happen? Is this an issue with my setup?

Sent from Mail for Windows 10

**Comment by davidbritch** [comment]
I just tried it against API 29 (emulator) and it worked fine, aside from the Data Package demo (which threw a `NullReferenceException`).
