### ISSUE TITLE
HybridWebView fails to invoke action on Android

### ISSUE THREAD

**Issue by firx** [xamarin/xamarin-forms-samples#661]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/HybridWebView/Droid

### Description

Nothing happens when clicking the "Invoke C# Code" button.

### Steps to Reproduce

1. Download sample code.
2. Run CustomRenderer.Droid
3. Enter a name into the text field.
4. Click "Invoke C# Code".

### Expected Behavior

Javascript alert should appear, and Result should be set.

### Actual Behavior

Nothing happens.

### Information

Tested with a simulated Android device.

**Comment by davidbritch** [comment]
Hi @firx 

It's working just fine for me:

![Screenshot_1597742602](https://user-images.githubusercontent.com/8092460/90495804-f3a22a80-e13c-11ea-875e-f28e7003de0b.png)

**Comment by gueneylib** [comment]
Hi, i also face the same issue.
Luckily, the solution is quite simple. The "index.html" in the Assets folder of the Project, which is used in the Webview, references a quite old version of JQuery. Just update the version from "http://code.jquery.com/jquery-2.1.4.min.js" to "https://code.jquery.com/jquery-3.5.1.min.js" and it should work again.
