### ISSUE TITLE
Xaminals UWP version doesnt show icons at bottom of shell like the Android version.

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#663]
Xaminals UWP version doesn't show icons at bottom of shell like the Android version.
The icons do appear on the flyout.

Interestingly changing  <ShellContent Icon="monkey.png" to <ShellContent Icon="Assets/monkey.png", the icons show on the bottom of the page and on the Flyout.
 

### Information

- IDE and IDE version: Visual Studio 2019 v16.7.2

**Comment by davidbritch** [comment]
Yes, report in the engineering repo please.

`CatsDetailPage` isn't in the Shell visual hierarchy (it's not defined in AppShell.xaml, instead a route to it is registered in AppShell.xaml.cs). When a page that's not in the Shell visual hierarchy is navigated to, a navigation stack is created (just as if you'd called `Navigation.PushAsync` in a non-Shell app) and `CatsDetailPage` is pushed onto the stack. The back button automatically appears so you can pop `CatsDetailPage` (and return to the previous page) off the navigation stack.

Hope that helps!
