### ISSUE TITLE
NullReferenceException iOS when video finished

### ISSUE THREAD

**Issue by FranciscoYimes** [xamarin/xamarin-forms-samples#671]
iOS, when video url finishes, app crashes. NullReferenceException in AppleMediaPlayer.cs:225

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
