### ISSUE TITLE
Android version : starting app gives system.io.filenotfoundexception

### ISSUE THREAD

**Issue by DutchZwolle** [xamarin/xamarin-forms-samples#675]
### Description
when starting the andriod app i got an error : System.IO.FileNotFoundException for XamarinForms101UsingEmbeddedImages.mp4

### Steps to Reproduce

1. Run code
2. During startup error occurs
3.

### Information

- IDE and IDE version: Visual Studio 2019 v16.7.7
- Platform with the issue: 
  - iOS:  
  - Android: 9.0
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
