### ISSUE TITLE
WebView How to reference js file

### ISSUE THREAD

**Issue by MarshalT** [xamarin/xamarin-forms-samples#677]
### Description

WebView How to reference js file
![image](https://user-images.githubusercontent.com/33778588/100495010-2d45f100-3182-11eb-98ef-0349dc5744d2.png)
![image](https://user-images.githubusercontent.com/33778588/100495047-7f871200-3182-11eb-8877-d20c125fce15.png)

### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
