### ISSUE TITLE
NotificationHub sample: Android push notifications no work when app is closed

### ISSUE THREAD

**Issue by nacompllo** [xamarin/xamarin-forms-samples#678]
The example of NotificationHub for Android does not include how to handle the situation of when push notifications are received with the app is closed and therefore the example is partially incomplete, could it be improved?

**Comment by KevinAnass** [comment]
i need the same thing any idea how?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
