### ISSUE TITLE
Examples about repeating local notifications

### ISSUE THREAD

**Issue by jiehou** [xamarin/xamarin-forms-samples#68]
Hello,

can Xamarin.Forms developers provide some examples about how to repeat local notification on Android, iOS and WinPhone?

Thanks in advance!

**Comment by conceptdev** [comment]
You can find details on implementing local notifications for iOS and Android in our docs:

http://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/

This must be done in a platform-specific way - there is no support in Xamarin.Forms. I'm sure Microsoft has similar documentation for the Windows platform.

We may look at writing some explanation for Xamarin.Forms in future - thanks for the suggestion.
