### ISSUE TITLE
UsingUITest.Droid is not compatible with net45

### ISSUE THREAD

**Issue by WillAutioItrax** [xamarin/xamarin-forms-samples#683]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UsingUITest

### Description

I am trying to learn UITesting using Xamarin Forms. Downloading this app seemed like a good start. I downloaded it and opened it in an up to date version of VS2019. I try to run the Android version and get 8 different errors that look like this:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project UsingUITest.Droid is not compatible with net45 (.NETFramework,Version=v4.5). Project UsingUITest.Droid supports: monoandroid90 (MonoAndroid,Version=v9.0)	UsingUITest.UITests	C:\Users\Will\source\repos\2101\Xamarin_Forms___App_Center_UITest\UsingUITest.UITests\UsingUITest.UITests.csproj	1	

### Steps to Reproduce

See above.

### Expected Behavior
I expect to be able to run the app and then the UITests.

### Actual Behavior
The app results in 8 errors that look like this:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project UsingUITest.Droid is not compatible with net45 (.NETFramework,Version=v4.5). Project UsingUITest.Droid supports: monoandroid90 (MonoAndroid,Version=v9.0)	UsingUITest.UITests	C:\Users\Will\source\repos\2101\Xamarin_Forms___App_Center_UITest\UsingUITest.UITests\UsingUITest.UITests.csproj	1	

However, despite the errors, the app runs. But the UITests do not.

### Information

- IDE and IDE version:  VS2019 16.8.3
- Platform with the issue: 
  - iOS:  
  - Android: Xamarin Android SDK - 11.1.0.17
  - UWP:  
- Device or simulator/emulator:  Device Samsung SM-G973W

**Comment by DeerSteak** [comment]
Seeing the same thing with device or simulator. The project template inserted into an existing solution seems OK, but I was hoping to mess with tests outside of the app to get a feel for it first.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
