### ISSUE TITLE
Empty FlyoutContent area under iOS

### ISSUE THREAD

**Issue by wlady** [xamarin/xamarin-forms-samples#689]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

### Description

When run Xaminals.iOS the FlyoutContent area is empty both in emulator and real device. Not FlyoutItems nor MenuItems are visible.

### Steps to Reproduce

1. Run project
2. Click hamburger icon in upper left corner

### Expected Behavior

Flyout and menu items should be visible under iOS

### Actual Behavior

Flyout and menu items are invisible under iOS

### Information

- IDE and IDE version: Visual Studio 2019 v16.8.4 / Visual Studio Mac v8.8.1
- Platform with the issue:
  - iOS:  14.3
- Device or simulator/emulator:  iPad4 mini, emulator

**Comment by wlady** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/13295

Bug is closed and fix will be enabled in next release 5.0.1. Currently it can be tested in 5.0.1 Nightly Build version.

**Comment by sebastianszaniszlo** [comment]
@wlady I seem to be having the same issue on an iPhone XS running iOS 14. My flyout menu is blank and so is my flyout content page. Has the fix been released? I'm currently running `Xamarin.Forms` v5.0.0.1931
