### ISSUE TITLE
ToDo WinPhone Sample does not compile

### ISSUE THREAD

**Issue by psycosyd** [xamarin/xamarin-forms-samples#69]
https://github.com/xamarin/xamarin-forms-samples/blob/master/Todo/SharedProject/WinPhone/MainPage.xaml.cs

MainPage.xaml.cs is still calling GetMainPage() which no longer exists as the newer paradigm just has MainPage be a property that is set within the Constructor.

This will need to be updated.

**Comment by conceptdev** [comment]
updated in a branch, will be migrated to master with next release
