### ISSUE TITLE
Hardware back button in Xaminals

### ISSUE THREAD

**Issue by BartoGabriel** [xamarin/xamarin-forms-samples#693]
I am testing UserInterface\Xaminals application on android 9.

I would like to know why the hardware back button does not work as expected (return to the previous view)

Example:
1. Start app
2. Entered the Dogs tab
3. Press hardware back button
4. The application is suspended. You should go back to the cat list.

Example 2:
1. Start app
2. Entered the side menu and going to monkeys.
3. Press hardware back button
4. The application is suspended. You should go back to the cat list.

I'm not understanding why the hardware button only works correctly for example when I enter the detail of a cat and then I go back.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
