### ISSUE TITLE
The page does not display correctly when searching in Shell.SearchHandler

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/xamarin-forms-samples#695]
### Sample

https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/

### Description

When tested above sample in devices 9.0  and 10.0, the page does not display correctly.
![image](https://user-images.githubusercontent.com/42464252/106423562-a1ab5200-649b-11eb-8514-a23f18f21273.png)

### Steps to Reproduce

1. download above sample ;
2. run it on device emulator 9.0 or 10.0;
3. and when we enter some key words into above SearchHandler, the page does not display correctly.

### Expected Behavior

The searched result will show correctly ,just as follows:

![image](https://user-images.githubusercontent.com/42464252/106423788-1088ab00-649c-11eb-8606-1d86707fddc0.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/42464252/106423562-a1ab5200-649b-11eb-8514-a23f18f21273.png)

### Information

The problem occurs  when xamarin form nuget is 5.0, and when I tested the previous sample (the nuget is 4.8.0.1821), the UI is good.

**Comment by PureWeen** [comment]
This will be fixed with the next release of XF 5.0

Thank you for letting us know about this issue!!
