### ISSUE TITLE
CollectionView is not displaying data when switched orientation from Landscape to Portrait with Xamarin.Forms 5.0.0.1931

### ISSUE THREAD

**Issue by pchandravadan** [xamarin/xamarin-forms-samples#700]
### Sample

I observed this behavior in the below sample
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/CollectionViewDemos

### Description
CollectionView is not displaying data when switched orientation from Landscape to Portrait with Xamarin.Forms 5.0.0.1931, downgrade to version 4.8.0.1821 and works fine.

### Steps to Reproduce

1. Install the CollectionView Demo on a physical device  
2. Click on one of the items **Vertical list** _DataTemplate_, **Vertical list** _Data Template Selector_, **Vertical list** _ItemSpacing_, **Vertical list** _variable size items_,

### Expected Behavior
Should see data shown before changing orientation

### Actual Behavior
No items are displayed  

### Information

- IDE and IDE version:  Visual Studio Mac v8.8.6(build 15)
- Platform with the issue: 
  - iOS:  14.3
- Device or simulator/emulator:  iPad (7th generation)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
