### ISSUE TITLE
Remove repository from xamarin-forms-samples/WebServices/TodoREST/TodoAPI/TodoAPI

### ISSUE THREAD

**Issue by Rick-Anderson** [xamarin/xamarin-forms-samples#705]
Remove repository from [samples/WebServices/TodoREST/TodoAPI/](https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoREST/TodoAPI/TodoAPI/Interfaces/ITodoRepository.cs)

At the suggestion of the EF team, we removed the repository from the  [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) over 3 years ago. Removing the repository:

* Improved customer satisfaction 18%.
* Eliminated all the repository questions and problems issues.

Also change ID from GUID to long. Much better for postman, testing, etc.

Use the same code as [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) which includes [Prevent over-posting](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio#prevent-over-posting). The [aspnetcore/mobile/native-mobile-backend.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mobile/native-mobile-backend.md) tutorial points to this over posting section.

Please assign this issue to me or close.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdbdf1ed-c52a-3be8-1f41-aecbdab0883b
* Version Independent ID: d06996cc-14aa-96e2-fd62-9d5bbc059107
* Content: [Create backend services for native mobile apps with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mobile/native-mobile-backend.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mobile/native-mobile-backend.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mobile**
* Microsoft Alias: **riande**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
