### ISSUE TITLE
Navigation examples are missing MVVM pattern

### ISSUE THREAD

**Issue by bartsipes** [xamarin/xamarin-forms-samples#712]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation

### Description

The MVVM pattern seems to be the primary pattern recommended for a real application, but all the Navigation examples do not use ViewModels. I've found a variety of dated examples elsewhere, but I can't seem to find any clear documentation on the https://docs.microsoft.com/en-us/xamarin/xamarin-forms/ help pages other than some e-books which are years out of date and have disclaimers all over about being out of date.

### Steps to Reproduce

1. Open any solution under https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation
2. Do a search for "ViewModel"
3. Note that there are none

### Expected Behavior
I would expect to have some more realistic examples of how to navigate within an app, not just the very basics.

### Actual Behavior
The Navigation folder has some useful examples but they are constrained to just handling events, not working with ViewModels and how you navigate from an invoked ICommand.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
