### ISSUE TITLE
CognitiveSpeechService error IOS speech_config_from_subscription assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by nickwood2009** [xamarin/xamarin-forms-samples#723]
### Sample
https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/CognitiveSpeechService

Running IOS version as is

### Description

After pressing the transcribe button I get the following error
speech_config_from_subscription assembly:<unknown assembly> type:<unknown type> member:(null)

in the line:
var config = SpeechConfig.FromSubscription(Constants.CognitiveServicesApiKey, Constants.CognitiveServicesRegion);

### Information

- IDE and IDE version: VS windows 16.9.2
- Platform with the issue: 
  - iOS:  unsure how to check
- Device or simulator/emulator: debugging on iphone X device with IOS version 14.4.1

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
