### ISSUE TITLE
Change PDB type to portable to avoid VS2019 compile warning 

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/xamarin-forms-samples#724]
### Sample

open SearchBarDemos.sln from this project and try to compile it

### Description

You get this VS warning about [old PDB format](https://docs.microsoft.com/en-us/xamarin/android/release-notes/11/11.2#deprecation-of-debugtype-full-and-pdbonly)

```
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(385,5): warning XA0125: 'SearchBarDemos.pdb' is using a deprecated debug information level.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(385,5): warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the project file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug information level.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(385,5): warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the library author.
```

### Steps to Reproduce

1. open SearchBarDemos.sln from this project 
2. try to compile it
3. look at warning in build output

### Expected Behavior

no warning

### Actual Behavior

warning about wrong PDB format

### Information

- IDE and IDE version: VS2019 16.9.2
- Platform with the issue: 
  - iOS:  
  - Android: 10.0
  - UWP:  
- Device or simulator/emulator:

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
