### ISSUE TITLE
Using Xamarin Dependency Service instead of Singleton Pattern

### ISSUE THREAD

**Issue by khaledbakeer** [xamarin/xamarin-forms-samples#725]
Why do you use the Singleton Pattern hier:

https://github.com/xamarin/xamarin-forms-samples/blob/4fb8e8c9e5aa9c1b7c9438411d2826bc71940f27/LocalNotifications/LocalNotifications/LocalNotifications.Android/AlarmHandler.cs#L15

if you defined Xamarin.Forms Dependency Service hier:
https://github.com/xamarin/xamarin-forms-samples/blob/4fb8e8c9e5aa9c1b7c9438411d2826bc71940f27/LocalNotifications/LocalNotifications/LocalNotifications.Android/AndroidNotificationManager.cs#L10

So I think we could use:
````csharp
// this:
var manager = DependencyService.Get<AndroidNotificationManager>();
// instead of this:
AndroidNotificationManager manager = AndroidNotificationManager.Instance ?? new AndroidNotificationManager();
````

and we can then remove the static instance in AndroidNotificationManager.cs:

https://github.com/xamarin/xamarin-forms-samples/blob/4fb8e8c9e5aa9c1b7c9438411d2826bc71940f27/LocalNotifications/LocalNotifications/LocalNotifications.Android/AndroidNotificationManager.cs#L30

because it could be generate two instances, one from the static one and another from Xamarin Dip. Service, what you need to avoid in you example.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
