### ISSUE TITLE
Possible sensitive information disclosure

### ISSUE THREAD

**Issue by oneturkmen** [xamarin/xamarin-forms-samples#726]
https://github.com/xamarin/xamarin-forms-samples/blob/e9792d200f56ef0260849b5ee16ed0b1c4de9352/EmployeeDirectory/EmployeeDirectory.iOS/iOSPhoneFeatureService.cs#L20

not sure if the keys are still or not.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
