### ISSUE TITLE
Mac VS - Load Failed: Unknown solution item type 

### ISSUE THREAD

**Issue by JulesMoorhouse** [xamarin/xamarin-forms-samples#727]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/SwipeViewDemos

Download this repo and try and open the SwipeViewDemos solution in Visual Studio for Mac version 8.9.5

### Description

When I try and open the SwipeViewDemos solutions in Visual Studio for mac I get the following error, Load Failed: Unknown solution item type 

![image](https://user-images.githubusercontent.com/361024/115207561-9effe680-a0f3-11eb-9ee7-e48fd3671fe9.png)

### Steps to Reproduce

1. Download this repo and open the SwipeViewDemos folder in the UserInterface folder.
2. Open the SwipeViewDemos solution
3. Notice the error and no code is opened apart from the project headers 

### Expected Behavior
The solution to open correctly.

### Actual Behavior
The solution does not open correctly.

### Information

- IDE and IDE version: Visual Studio Mac v8.9.5
- Platform with the issue: Mac OS Catalina - 10.15.7
  - iOS:  Can't get this far
  - Android: Can't get this far
  - UWP:  N/A
- Device or simulator/emulator: Can't get this far

**Comment by fodilo** [comment]
@JulesMoorhouse  Any idea on how to solve that ?

**Comment by gp-memosoft** [comment]
Any idea how to fix this?

**Comment by 020AlievIB** [comment]
@JulesMoorhouse Any idea how to fix this?

**Comment by yusufaraz** [comment]
Hello I fixed the problem by changing Default solution location. Check your default solution locations. Visual Studio -> Preferences -> Build an Debug -> Default Solution Location. change this to where your file is located.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
