### ISSUE TITLE
Cancel button in toolbar app

### ISSUE THREAD

**Issue by jjcolumb** [xamarin/xamarin-forms-samples#731]
Is there a way to remove the CANCEL button in the App left item bar? 
For the AzureADB2CAuth sample: https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/AzureADB2CAuth

<img width="350" alt="72616191-266d1180-3915-11ea-8390-e55203d48299" src="https://user-images.githubusercontent.com/22223689/115796595-f073d400-a386-11eb-92f4-8e7d62fac855.png">

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
