### ISSUE TITLE
The "nuget restore" command fails

### ISSUE THREAD

**Issue by MaksimZhukov** [xamarin/xamarin-forms-samples#734]
### Sample

This issue is related to the [ToDo sample](https://github.com/xamarin/xamarin-forms-samples/tree/main/Todo).

### Description

The `nuget restore ./Todo/Todo.sln` command fails with new Mono version (`6.12.0.140`) on macOS 10.15 Catalina image with the following error:
```
/Users/runner/work/xamarin-forms-samples/xamarin-forms-samples/Todo/Todo.UWP/Todo.UWP.csproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/qxkilfkb.j5z.nugetrestore.targets(315,5): warning : Skipping restore for project '/Users/runner/work/xamarin-forms-samples/xamarin-forms-samples/Todo/Todo.UWP/Todo.UWP.csproj'. The project file may be invalid or missing targets required for restore. [/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/hczm5041.2wn.nugetinputs.targets]
```

### Steps to Reproduce

I forked this repository and prepared the [workflow file](https://github.com/MaksimZhukov/xamarin-forms-samples/blob/main/.github/workflows/test-todo-app.yml) with steps to reproduce this issue. The `nuget restore` command passes successfully with `6.12.0.125` Mono version and fails with new version (`6.12.0.140`). Please find more details in [this workflow run](https://github.com/MaksimZhukov/xamarin-forms-samples/actions/runs/922555789).

### Expected Behavior

The `nuget restore` command passes successfully

### Actual Behavior

The `nuget restore` command fails

**Comment by davidbritch** [comment]
Any luck with `dotnet restore` or `msbuild -t:restore`?

**Comment by MaksimZhukov** [comment]
The `dotnet restore` command runs without errors, but skips restoring for `Todo.iOS.csproj` and `Todo.Android.csproj` project files and produces warnings with the similar message:
```
warning NU1503: Skipping restore for project '/Users/runner/work/xamarin-forms-samples/xamarin-forms-samples/Todo/Todo/Todo.Android/Todo.Android.csproj'. The project file may be invalid or missing targets required for restore. [/Users/runner/work/xamarin-forms-samples/xamarin-forms-samples/Todo/Todo.sln]
```

The `msbuild -t:restore` command restores packages successfully.

[Workflow run](https://github.com/MaksimZhukov/xamarin-forms-samples/actions/runs/1033962917)

**Comment by MaksimZhukov** [comment]
Hello @davidbritch! Have you had a chance to take a look at it?

**Comment by MaksimZhukov** [comment]
Hello @davidbritch! We tried to run builds for other applications and unfortunately all of them (except 1) failed with mono `6.12.0.140` and `6.12.0.147`. Please see [build logs](https://github.com/MaksimZhukov/xamarin-forms-samples/actions/runs/1097592796) for the details. 

It looks like this issue is mostly related to the mono. We created an issue in the [mono/mono](https://github.com/mono/mono/issues/21180) repository, please take a look.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
