### ISSUE TITLE
Calling PostAsync in Webservices / ToDo Rest via iOS throws exception

### ISSUE THREAD

**Issue by bartvanduinkerken** [xamarin/xamarin-forms-samples#745]
### Background

While running the following project on iOS devices I get and error when adding a new ToDo item. https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoREST. 

### Description

While trying to save the item the response is not return and the debugger shows:
2021-11-22 14:55:50.306 Xamarin.PreBuilt.iOS[3804:2270334] Xamarin.iOS: Received unhandled ObjectiveC exception: NSMallocException Failed to grow buffer.

I have also tried a simple app with a button and a PostAsync request and same behavior. 

### Steps to Reproduce

1. Download the code
2. Run the iOS project on a linked iPhone
3. Add a new ToDo item and save it

### Expected Behavior
The save to work and be added to the list.

### Actual Behavior
Nothing happens and I see error in the Output console. 

### Information

- IDE and IDE version: Visual Studio 2022
- Platform with the issue: 
  - iOS:  15.0.2 both on iPhone 7 and iPhone 12

**Comment by bartvanduinkerken** [comment]
It seems to only have effect while working on my laptop with VS2022, multiple people have tested the code on a different machine where it works. Any clues what setting could have this effect?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
