### ISSUE TITLE
Activity indicator take space even if, i  set isvisibility false

### ISSUE THREAD

**Issue by sanjeetakc** [xamarin/xamarin-forms-samples#746]
### Issue

I have a grid view it tab gesture but it not working where I set indicator, activity indicator take space even if its visibility is false

### Expected Behavior

If visibility is false then the user interface is working properly in the place of the indicator.
### Actual Behavior
Not working still show indicator take space.

- IDE and IDE version: Visual studio 16.11.5
- Platform with the issue: Android
  - Android: All android version

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
