### ISSUE TITLE
No URI images in CollectionView on iOS app

### ISSUE THREAD

**Issue by mcblacksea** [xamarin/xamarin-forms-samples#748]
### Sample

[Xanimals app](https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/Xaminals/Xaminals.iOS)

### Description

![image](https://user-images.githubusercontent.com/24685526/151664346-afdadd05-e4d3-4598-ac6e-933478779f85.png)

### Steps to Reproduce

1. Launch iOS Xanimals app
2. Only for on iOS app: Vast majority of images weren't loaded into CollectionView 

### Expected Behavior

Correctly loaded images

### Actual Behavior
Only for on iOS app:
Vast majority of images weren't loaded into CollectionView.  
Often it's simple blank images list with only descriptions. 

### Information

- IDE and IDE version: Microsoft Visual Studio Community 2022 (64-bit)  v.17.0.5
- Platform with the issue: Xamarin.Forms
- iOS:  iPhone 12 Pro on iOS 15.2.1 / 
- Device or simulator/emulator: iPhone simulator on iOS 15.2

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
