### ISSUE TITLE
TodoLocalized refers to missing package 'SQLite.Net.Platform.XamarinAndroid'.

### ISSUE THREAD

**Issue by nSolvePR** [xamarin/xamarin-forms-samples#75]
Updating gives:
`Updating SQLite.Net.Platform.XamarinAndroid...
Unable to find package 'SQLite.Net.Platform.XamarinAndroid'.`

**Comment by conceptdev** [comment]
Just checked nuget
https://www.nuget.org/packages/SQLite.Net.Platform.XamarinAndroid/
and seems like that package is deprecated. We've already updated the other Todo sample to use the official SQLite-NET PCL nuget package, so I'll update this project too.

**Comment by conceptdev** [comment]
fixed in branch, will soon be applied to master
