### ISSUE TITLE
Video is not playing in iOS Devices (Simulators) 

### ISSUE THREAD

**Issue by Sumit2668** [xamarin/xamarin-forms-samples#751]
### I used a video URL which is mentioned below and it is not working and in android is working fine.

https://vohra-public.s3.amazonaws.com/admin_root/images/2022/02/07/ab7d64bf-cd41-4bf0-96b9-0417b41b2ec4.mp4
https://vohra-public.s3.amazonaws.com/admin_root/images/2022/02/08/0a95921f-1936-4d74-a490-959275587741.mp4

### Steps to Reproduce

1. Install-Package successfully (Xamarin.CommunityToolkit V2.0.0 ).
2. Add MediaElement tag
3. Add URL directly in XAML UI

### Expected Behavior
play video on android and iOS devices

### Actual Behavior
android is working fine but not playing on iOS devices

### Information

- IDE and IDE version: Visual Studio Mac v8.10.6 
- Platform with the issue: 
  - iOS: Xamarin.CommunityToolkit V2.0.0 
  - Android: Xamarin.CommunityToolkit V2.0.0  
- Device or simulator/emulator: simulator(iPhone12 )

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
