### ISSUE TITLE
Issue in SilentKeyboardPage

### ISSUE THREAD

**Issue by devenv2** [xamarin/xamarin-forms-samples#752]
Touch issue in android app for  xamarin forms 
Black keyboard keys work transparently and when I click on them, white keys are clicked, sometimes when you navigate between MainPage and SilentKeyboardPage.

https://github.com/xamarin/xamarin-forms-samples/blob/main/Effects/TouchTrackingEffect/TouchTrackingEffect/TouchTrackingEffect/SilentKeyboardPage.xaml#L39-L49

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
