### ISSUE TITLE
Update screenshot on README to see the result after applying DataTemplates

### ISSUE THREAD

**Issue by jasursadikov** [xamarin/xamarin-forms-samples#757]
https://github.com/xamarin/xamarin-forms-samples/tree/main/Templates/DataTemplates

### Description
I do not see example screenshot where `DataTemplate`s are used. On the screenshot "ListView without DataTemplate" is shown on  example :)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
