### ISSUE TITLE
The Dark/Light Theme gives an error in a solution that has the Appshell.xaml

### ISSUE THREAD

**Issue by aproko234** [xamarin/xamarin-forms-samples#758]
### Sample

[](https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/SystemThemesDemo/SystemThemesDemo)

### Description

After updating or importing the (Application Resources) of App.xaml in the above project into a new xamarin.forms app, when you try to deploy, it gives an error ( "Object reference not set to an instance of an object.")

### Steps to Reproduce

1. Create a New Project in VS 2022 (for Android/iOS)
2. Copy the Application.Resources aspect of App.xaml in the SystemThemesDemo to replace the one in your new project
3. Build & deploy

### Expected Behavior
The Shell menu is supposed to accept the AppBindngTheme Mark-Up instruction in the AppShell.xaml file

### Actual Behavior
It gives an error ( "Object reference not set to an instance of an object.") and stops in AppShell.x.l.cs file.

### Information

- IDE and IDE version: VS 2022 
- Platform with the issue: 
  - iOS:  
  - Android: 10 
  - UWP:  
- Device or simulator/emulator: Both.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
