### ISSUE TITLE
I am not able to consume WCF Restful Service 

### ISSUE THREAD

**Issue by swa6589** [xamarin/xamarin-forms-samples#76]
HttpClient client;
var authData = string.Format ("{0}:{1}", Constants.Username, Constants.Password);
    var authHeaderValue = Convert.ToBase64String (Encoding.UTF8.GetBytes (authData));
    client = new HttpClient ();
client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue ("Authorization", authHeaderValue);
client.DefaultRequestHeaders.Add("Content-Type", "application/json");

  var response = await client.GetAsync(uri);

I am getting an exception System.Net.WebExceptionStatus.NameResolutionFailure
I an able to view the data in RestClient but not from code.

Any Suggestions or any solutions will help me.

I am getting an exception

**Comment by conceptdev** [comment]
**NameResolutionFailure** suggests a DNS issue, check the network connectivity
