### ISSUE TITLE
Xamarin Forms the problem of app restarting when clicking the deep link while the application is in the background

### ISSUE THREAD

**Issue by msandikli** [xamarin/xamarin-forms-samples#774]
**Description**
I implemented deep linking to my app. I used this document for this implementation: https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking

I have a problem on Android platform. When the app running, I put the application in the background and clicked on the deep link I created. The app restarts even though it is open in the background.

**Steps to Reproduce**
Create a New Project in VS 2022 (for Android/iOS)
Implementation deep linking. Document: https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking
Open app and put the application in to the background.
Click your created deep link.
And app is restarting, not resumed existing page.

**Information**
IDE and IDE version: VS 2022
Platform with the issue:
iOS:
Android: 12
UWP:
Device or simulator/emulator: Xiaomi Poco X3 NFC.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
