### ISSUE TITLE
Camera Android not show or crash on android 7 (oppo f5)

### ISSUE THREAD

**Issue by dimaskkp** [xamarin/xamarin-forms-samples#787]
### Sample

![camera page before tahe picture](https://user-images.githubusercontent.com/40069018/210221241-b331e8b4-2884-46fd-8ed0-9201e0b3edc8.jpeg)

[xamarin-forms-samples](https://github.com/xamarin/xamarin-forms-samples)/[CustomRenderers](https://github.com/xamarin/xamarin-forms-samples/tree/main/CustomRenderers)/ContentPage/

### Description

camera preview not show or crash before take picture.

### Steps to Reproduce

1. download CustomRenderers
2. rebuuild  and runn in android 7 (oppo F5 android 7 )
3. runing and allow access camera / storage

### Expected Behavior
only in oppo f5 android 5.  in other device runing 

### Information

- IDE and IDE version: 17.4.2 vs mac
- Platform with the issue: 
  - iOS:  no issue 
  - Android: android 7
- Device or simulator/emulator: device oppo f5

please help for this, thank you

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
