### ISSUE TITLE
Forms2Native Crash on Startup

### ISSUE THREAD

**Issue by Bobisback** [xamarin/xamarin-forms-samples#80]
When I start the Forms2Native app in iphone 5s 9.2 simulator it crashes at startup. Anyone else have this issue? If so any ideas how to fix it?

Thanks,
Bob

**Comment by PILLUTLAAVINASH** [comment]
You May Miss Any Package While Loading The Project Try to Reload The Project And If You Have Any Errors Try To Rectify It

Best Regards
Avinash.ps

**Comment by Bobisback** [comment]
Last I checked a app cannot install on the device if there are packages or projects missing. This crash is happening after the app is installed just after the splash screen starts up.

**Comment by mfick76** [comment]
Hi,
check if your are building your ios sample for "i386 + x86_64" (project propierties of iOS Project, iOS Build -> advanced tap [in vstudio]). 

If you only build for i386 then the ios device refuses to load the app and in the system.log of the simulator you find a "program specified by serviuce does not contain one of the requested architectures" message.

Best regards
Markus

**Comment by PILLUTLAAVINASH** [comment]
Hi markus,
Thanks for giving me suggestion according to the project. I'll make fallow up on this 
Thanks & regards
Avinash.ps
