### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by sdavies35** [xamarin/xamarin-forms-samples#83]
Downloaded project as-is, tried to build in Visual Studio 2015. Am I missing something?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MasterPage.xaml.cs	13	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\ContactsPage.xaml.cs	9	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MainPage.xaml.cs	10	Active
Error	CS0103	The name 'masterPage' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MainPage.xaml.cs	12	Active
Error	CS0103	The name 'masterPage' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MainPage.xaml.cs	24	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MasterPage.xaml	0	
Error	CS0103	The name 'listView' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MasterPage.xaml.cs	9	Active
Error	CS0103	The name 'listView' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\MasterPage.xaml.cs	32	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\ReminderPage.xaml	0	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\ReminderPage.xaml.cs	9	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\TodoListPage.xaml	0	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MasterDetailPageNavigation	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\TodoListPage.xaml.cs	9	Active
Error		Unexpected error - Please file a bug report at http://bugzilla.xamarin.com. Reason: System.IO.FileNotFoundException: Could not load assembly 'MasterDetailPageNavigation, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?	MasterDetailPageNavigation.Droid			
Error		Metadata file 'C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\bin\Debug\MasterDetailPageNavigation.dll' could not be found	MasterDetailPageNavigation.WinPhone81	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation.WinPhone81\CSC		
Error		Metadata file 'C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\MasterDetailPageNavigation\bin\Debug\MasterDetailPageNavigation.dll' could not be found	MasterDetailPageNavigation.iOS	C:\Users\Admin\Documents\Visual Studio 2015\Projects\MasterDetail2\iOS\CSC

**Comment by ldegrazia** [comment]
Inherit from content page.

**Comment by sdavies35** [comment]
Hi Louis,

 

I was expecting the code to build as-is. “Inherit from content page” doesn’t really help, but I appreciate your reply.

 

Shawn

 

Shawn.Davies@Outlook.com <mailto:Shawn.Davies@Outlook.com>          Office: 918-366-8986 <tel:918-366-8986>          Cell: 918-850-9570 <tel:918-850-9570>

**Comment by ldegrazia** [comment]
Sorry,
I'm suddenly on this thread in my email, i have no view to the code. I just
saw your first error with initialize component.

I see that error when there's a xaml page missing for the code behind page
or the class that's running does not inherit content page.

**Comment by sdavies35** [comment]
No problem. I’m new to Xamarin (not Visual Studio), so I thought I’d give this project a test run and discovered the build errors.

 

Thanks again for your reply!

Shawn

 

Shawn.Davies@Outlook.com <mailto:Shawn.Davies@Outlook.com>          Office: 918-366-8986 <tel:918-366-8986>          Cell: 918-850-9570 <tel:918-850-9570>

**Comment by Parmendrak** [comment]
I have checked this issue with latest stable build and latest Forms version and observed that this issue is working fine.

Thanks.
