### ISSUE TITLE
MobileCRM sample app is not building: resource directory ...\res does not exists

### ISSUE THREAD

**Issue by JorisZwaenepoel** [xamarin/xamarin-forms-samples#84]
Hi,

I am learing Xamarin.Forms and I wanted to take a look at this sample application, but it doesn't build.  This is the error I get:

_resource directory 'C:\Project\MobileCRM\MobileCRM.Android\obj\Debug\resourcecache\228FE4BE22572EC887F17BE4BD5A7583\res' does not exist_

Project: MobileCRM.Android
File: C:\Project\MobileCRM\MobileCRM.Android\AAPT		

Can anyone help me in solving this build error?

Thanks,

Joris

**Comment by alanbeech** [comment]
Try a clean and rebuild.

Alan

Sent from my iPhone

On 6 Feb 2016, at 20:34, JorisZwaenepoel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am learing XamarinForms and I wanted to take a look at this sample application, but it doesn't build This is the error I get:

resource directory 'C:\Project\MobileCRM\MobileCRMAndroid\obj\Debug\resourcecache\228FE4BE22572EC887F17BE4BD5A7583\res' does not exist

Project: MobileCRMAndroid
File: C:\Project\MobileCRM\MobileCRMAndroid\AAPT

Can anyone help me in solving this build error?

Thanks,

Joris

**Comment by Rajneesh360Logica** [comment]
Hi  @JorisZwaenepoel 
Thanks for filing the issue. I have checked this issue and I am no longer able to reproduce this. I observed that I am successfully able to build forms-sample "MobileCRM" successfully.

Screencast: http://www.screencast.com/t/lQO6ubBz2wgh

So as of now I am closing this issue, please me know if I am missing something.

Thanks..!
