### ISSUE TITLE
View Created Event Not Firing

### ISSUE THREAD

**Issue by MoffApps** [xamarin/xamarin-forms-samples#88]
Hi,

Im following the https://developer.xamarin.com/guides/xamarin-forms/advanced/cocossharp/

  var gameView = new CocosSharpView()
            {
                // Notice it has the same properties as other XamarinForms Views
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                // This gets called after CocosSharp starts up:
                ViewCreated = HandleViewCreated  
            };
            // We'll add it to the top half (row 0)
            grid.Children.Add(gameView, 0, 0);

HandleViewCreated is never called! Is this a known issue?

Tony

**Comment by Arpit360** [comment]
I have checked this issue and observed that HandleViewCreated event is called for me.
Please review the screencast : http://www.screencast.com/t/HuTtt190x1 
and check at your end and let me know if you face this issue again

**Comment by philllies** [comment]
I got the same issue using Xamarin.Forms: 2.3.2.127

**Comment by marcvannieuwenhuijzen** [comment]
Anyone got a solution for this? I have the same problem.

**Comment by olegoid** [comment]
Reopening the issue. @ivanherreragl please take a look.

**Comment by ivanherreragl** [comment]
HandleViewCreated is effectively getting called using XamarinForms 2.3.2.127, CocoSharp 1.7.1.0. 

Xamarin Studio Community (MAC) 6.1.1 (build 15)

Screencast: http://www.screencast.com/t/456YjzsX

**Comment by philllies** [comment]
I'm also using XamarinForms 2.3.2.127 and CocoSharp 1.7.1.0, on Windows, though. Maybe that's the issue?

Visual Studio/Xamarin Info:
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
Installed Version: Enterprise
Xamarin   4.2.0.703 (3b7df6f)

**Comment by ivanherreragl** [comment]
So, I tried it in Windows 10 + Visual Studio Community + iPhone 6S iOS10 Simulator and still works. Attaching here my IDE desc:

https://gist.github.com/ivanherreragl/bad40360a82ed506e001e5e6c1b177b6

**Comment by olegoid** [comment]
thanks @ivanherreragl 👍 

@philllies @marcvannieuwenhuijzen could you provide complete environment details?

If you're on macOS: Xamarin Studio -> About Xamarin Studio -> Show Details
If you're on Windows: Help -> About

**Comment by philllies** [comment]
For the environment details, please see my post from yesterday.
One thing to note is that I only tried to build the sample project for UWP and Android app (not for iOS), neither of which work.

**Comment by marcoferra** [comment]
Same issue (only in Android project). Everything's fine on iOS.

Xamarin Forms: 2.3.3.168
CocosSharp: 1.7.1.0


Xamarin Studio Community
Version 6.1.2 (build 44)
Runtime:
	Mono 4.6.2 (mono-4.6.0-branch/08fd525) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Package version: 406020007

NuGet
Version: 3.4.3.0

Xamarin.iOS
Version: 10.2.1.5 (Xamarin Studio Community)

Xamarin.Android
Version: 7.0.2.37 (Xamarin Studio Community)
SDK Tools Version: 25.2.2
SDK Platform Tools Version: 25
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)

Xamarin.Mac
Version: 2.10.0.113 (Xamarin Studio Community)

Build Information
Release ID: 601020044

**Comment by Rob-Houweling** [comment]
Had the same issue, but was resolved by installing the CocosSharp package in the iOS and Android project as well, not just the PCL project.

**Comment by CJACQUEL** [comment]
I have the same problem. I use Xamarin Forms. PCL System. Cocossharp on 3 Project PCL android and iOS. 
<packages>
  <package id="CocosSharp" version="1.7.1.0" targetFramework="portable46-net451+win81" />
  <package id="CocosSharp.Forms" version="1.7.1.0" targetFramework="portable46-net451+win81" />
  <package id="Xamarin.Forms" version="2.3.3.168" targetFramework="portable46-net451+win81" />
</packages>

>>>>>>>>>>>HandleViewCreated never called. 
Could you help ? Thx

**Comment by sktdeepak** [comment]
i also have the same problem...
CocosSharpView -> ViewCreated event not firing

**Comment by davidbritch** [comment]
Apologies for the lack of response to this issue. Unfortunately, we've now retired our CocoSharp content, so I'm going to close this issue.
