### ISSUE TITLE
BugSweeper: Windows 10 Mobile

### ISSUE THREAD

**Issue by wegascee** [xamarin/xamarin-forms-samples#89]
The size of the board is greater than the screen size. Furthermore I get sometimes ArgumentException (e.g. if I won). Also the PrepareForNewGame() seems not to work on Windows 10 Mobile (UWP). You can click on the button, but the old tiles are still there.

This issue is for all platforms:
Too bad/Congratulations are overlapping with play another game.

**Comment by Parmendrak** [comment]
I have filed issue with all scenario.
https://bugzilla.xamarin.com/show_bug.cgi?id=42216
https://bugzilla.xamarin.com/show_bug.cgi?id=42217
https://bugzilla.xamarin.com/show_bug.cgi?id=42218
https://bugzilla.xamarin.com/show_bug.cgi?id=42220

Thanks.

**Comment by charlespetzold** [comment]
These bugs have been fixed, although the UWP version still has some visual anomalies when the second and subsequent games are initialized.
