### ISSUE TITLE
xamarin samples don't work with VS 2015 and the latest Xamarin forms.

### ISSUE THREAD

**Issue by jlongo62** [xamarin/xamarin-forms-samples#92]
Tried to use Scale and Rotate sample. Does not work. Even Petzhold's  and the PhoneWorld/Phoneword (check the spelling in the sample) or whatever it is also does not work. It seems like every sample I have tried is crap. Xamarin needs to put someone on QC to go though the samples to make sure they compile/run. This should be automated as a build to smoke test the samples.

**Comment by olegoid** [comment]
Hey @jlongo62, sorry to hear that. We're working on QA infrastructure now to improve the overall quality of samples in our public repositories.

Could you describe what problem you experienced with Scale and Rotate sample?

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. I can confirm that the vast majority of samples build on all platforms, with just a couple of known issues that are being worked on. Therefore I'm closing this issue.
