### ISSUE TITLE
MainPageCS file in CustomRenderer Sample faulty

### ISSUE THREAD

**Issue by theresesango** [xamarin/xamarin-forms-samples#94]
MainPageCS file in CustomRenderer Sample doesn't fill the entire view. The xaml version of mainpage works!

**Comment by davidbritch** [comment]
Apologies for the delayed response. Which sample is the problem in?

**Comment by davidbritch** [comment]
I've not heard back from you so I'm going to close this issue. Thanks for taking the time to raise an issue.
