### ISSUE TITLE
Is this work with VS 2015?

### ISSUE THREAD

**Issue by alexsandro-xpt** [xamarin/xamarin-forms-samples#98]
I'm try to compile but a have lot of erros like `InitilizeComponent is not difined`

**Comment by apacha** [comment]
The samples work fine in Visual Studio 2015. When you build the project, it will actually work. The error that `InitializeComponent does not exist in the current context` is seemingly a [very annoying bug that has been around for almost two years.](https://forums.xamarin.com/discussion/17638/initializecomponent-does-not-exist)

I'm not sure if it is related to ReSharper or not, but try to ignore it, if you can. And hope that someone will fix it soon, as it is very unpleasant.

**Comment by Arpit360** [comment]
@alexsandro-xpt @apacha  I have checked this issue with VS 2015 update 3 and able to build and deploy xamarin.Forms project successfully.

Can you please try to update Nuget Package Manager for VS from VS  :Tools-> Extension and Updates ->Installed.
and try to build and deploy the application.

Please let me know if you are getting this again in future

**Comment by alexsandro-xpt** [comment]
A some week ago, after a long research, I haved success.

The problem is about unfriend Xamarin build with Visual Studio, new developers can't know what happen with a lot of build erros messages.

**Comment by apacha** [comment]
I can verify that this issue is resolved by Xamarin.
