### ISSUE TITLE
CLI workflow

### ISSUE THREAD

**Issue by esistgut** [xamarin/xamarin-forms-samples#99]
Please provide documentation on how to build this on platforms other than Visual Studio and Xamarin Studio, i.e. Linux and command line.

**Comment by olegoid** [comment]
Hello @esistgut, I think you can find the following resources useful:
1) http://www.makelinux.com/man/1/M/mdtool
2) http://www.mono-project.com/docs/tools+libraries/tools/xbuild/
3) https://developer.xamarin.com/guides/cross-platform/ci/intro_to_ci/
